apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-creds
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    vpn-private-key: ENC[AES256_GCM,data:NI7v2kgHlJ85/RPAIRSs5aGrircAT3JHZB66nsGmHrnPYsxFq6iFFXyYAqk=,iv:WuOBfzMQJf1xbj21xKmQ6agQWgMlbHDUMHHQw544UyM=,tag:6bPW/QF6njA1dL9QbIGWlQ==,type:str]
    qbittorrent-username: ENC[AES256_GCM,data:9Uv7DnBTJEjwwFo=,iv:kxxYSuaGNUs7t0IMwvdhXeN7e6xV9Iu32FD7sinrEqY=,tag:vdSQ6Y72oFM87iyByJLTiA==,type:str]
    qbittorrent-password-hash: ENC[AES256_GCM,data:27hBFT1H+TIVmXYksm7zi4HV4+6edH5jeF6IIm6rltlWSyzM2W2UXLgzM01sUlGF6V3JYH8U8Zs4ZfPIntvg9eNsAXFG4hjLUlRJfrpPxhpdPWyqOVJ/ZGTdn/MP6LpttF0zOhHdbzre4GFn+XtdlOXzERif1Mi7XLzYcAo=,iv:kGCzBoOvCEyltOR5yU2GsZeXOe+bAN4WdeLN1q0rHXA=,tag:70oPWc67YbMklPspLoxuTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYTlEbHpkN3RPdFNVaGVU
            NmluUE85aDl2MEJhK2lYbkxhVGY2Sno3TGs0CndnTG1GOVV2QkxpZ2t6Kzl2OHZF
            UW13MzlLWnBlejF5ejZOY2M2QzQwR3cKLS0tIHVzYmFIVTYzd3haUGhZYklIWWN3
            UXNuS0tBM1JHNmdEeUVQNnQ4WkNudjgKlf2tVh5f4Wo1vdTrmbREP9ua10hUh8xh
            QylmaIbOI2+Wkbnxz/AUqTKF9w4qI2KvgtuvWfQ1AjWEtVI1ibAXCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T18:00:41Z"
    mac: ENC[AES256_GCM,data:O/7odH/OycNO6SFuPPm12An0BfqHJCdIZeGSIOrBk8HJHtSvPfRg/MR2PlD9ycdLaXUO0pyZnAyNEAyV38KWLwYhdqiUi2G9xYUY4pqjtQqiF3REsC9iwD3SkPWjHJxjt0Gks4eQl/X4wg18zEaqbD3S+LEs3Wmh83yZR9Dt/+w=,iv:Rce/Dhpr4reAbPlT9WlHXzeJQjj8fOwaiz37ySeGDjE=,tag:06VG7RtJuJdy0ljfhFNSMA==,type:str]
    version: 3.13.1
