apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-creds
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  vpn-private-key: ENC[AES256_GCM,data:9O2kca1xWhMxw7HnPRxtYj6cxDxO5UpI2wZB24MzIZg+I6WQyTib6gA8mZI=,iv:u0RgYyngDb39lpHfiCFD1bI6EwYZR3P56JmhFVPUIhc=,tag:GsSQpIONL+OAUr+H7U/MMQ==,type:str]
  qbittorrent-username: ENC[AES256_GCM,data:6v+OIC5oA8ePFaw=,iv:qlpJljoIn6ytsVHfdS7sTfamV8OIjEtKuqlBf+UUqRs=,tag:V0uUcDcM+agsB7hQoUYXUg==,type:str]
  qbittorrent-password-hash: ENC[AES256_GCM,data:wyGiCvm4iFmab1ELh6mSbC14wKmN9kZA0iNm/lB3h9H2KZL5LEQdP4y88EPstt0nx9Xoa8kuCd1NqtXSPQScwHiuSYvUKsg8/6ESteJ5ovFrOIF4aXc1zMWzgCGymLDs4spMTTOEoA+OoWfRczLtwHWLd9Z9SNEPJwkzFIk=,iv:1TrHM1i8D5M6lhOOlpxRm9vw6qMgSmwRqcNwVAJvpFk=,tag:b2Z2RJXR5sH/DF3YpWUlsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZlZEL2s3WE9qem1ISnNM
        QU1PTUZ4c21OcUY4S2xNYURYVEdUMXFaZ3hzCklqWWlveGhJOTJsQ0xEOFBPVm1s
        ZWFxTkhyelNRRFgwSkpDYW9Oa1Q1cjgKLS0tIGdYUXFxVEZ5cTNEUndrbkU2UmVO
        bTRXeVhQQ3AvNW82OHpXSlA0NjRXMDAKo0JY9zkHSimnAYeshSXI/1yaC2TuMJM/
        czfjRYEkfcySz+hozT5IARYTP3DIpTFwR05ocIl8jzepUw/KzOFRUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T05:18:03Z"
  mac: ENC[AES256_GCM,data:LtX3/LsK60nc6b+NTKI7+I2Zu03n5yndicHHMI31+2uQb9AsFL4dWBmQkpibyDl9Ra7/jAlybeFfGyVWsuLdpAY16usshjnTw+X3IKoRqCxvTZA1XRC19VOHak3DOrQCOKdX0m53x25NbEOLVZfyuHWNadqbEZJZ3c8Drg8WDH8=,iv:KqLgGoHSvl7u9WHUU3kYn+Kd+ZIDAnG32IOp9eicNY0=,tag:VGed5hdM9inK2GB0F9j7lA==,type:str]
  version: 3.13.1
