- name: Download Microsoft Red Hat repository package
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/packages-microsoft-prod.rpm"
    dest: /tmp/packages-microsoft-prod.rpm
    mode: "0644"

- name: Register the Microsoft Red Hat repository
  ansible.builtin.dnf:
    name: /tmp/packages-microsoft-prod.rpm
    state: present
    disable_gpg_check: true
  become: true

- name: Remove temp files
  ansible.builtin.file:
    path: /tmp/packages-microsoft-prod.rpm
    state: absent

- name: Refresh DNF cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install PowerShell package
  ansible.builtin.dnf:
    name: powershell
    state: present
  become: true
