apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

resources:
  - ./namespace.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./ingressroute.yaml
  - ./secret.yaml
  - ./blueprints/secret.yaml

configMapGenerator:
  - name: authentik-custom-blueprints
    files:
      - blueprints/01_propertymappings.yaml
      - blueprints/02_providers.yaml
      - blueprints/03_applications.yaml
      - blueprints/04_users.yaml
    options:
      disableNameSuffixHash: true
