apiVersion: v1
kind: Secret
metadata:
    name: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:zKwSxp9try8q9MXoxYiHSGeG4PJmHHxpX49BNNfDeiw9tcBlRTMrMBm30uyo,iv:dOKDB6tdkyCXf6mC38YvTVTp7rtpuwuy4Xq2wP0XwZA=,tag:a31cAwsNRNgyAoL8Tke62w==,type:str]
    postgresql_password: ENC[AES256_GCM,data:iSaTnxJtWO+8PYI264DGg6SBXod7k3xCMDr+tmuZNdWxbJdVjnDYiuFUkWZrSRY=,iv:ysODDm9IOaN8HEp2nlov7El20JBGQctyPAXdWbKbQkI=,tag:qyqRj4X1StD6IVVPHvU4bQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNk9lZTQrVTR1WFZPUU15
            UjNGL2sxNEh5K0JqSVZ1VEVSWmNYd0JOOXhzCkg4M1NkSkhiZEhZWHh0RmVLZ1Zr
            SjR5YWxKa1VtQkNhMUEzY2drTklJcGMKLS0tIGdvOUZBUjMzZEd3ZE01cEdwZ3NV
            Yy95b2dGcjc5ZnpLc296UEdLQzVoT0UKjns9uPcCHfWHdGHYQoxtZ+SmftBFW9//
            tYtkM0MY1gGjGYUrPb6QESb2jzyBxeet+XkVTptRwGsTZEBJjmcGuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T03:24:55Z"
    mac: ENC[AES256_GCM,data:PsxZa/EsANZ6VHBg+WhSjDWN3C/kHz0a8XHkDufm4okuEs+ZMObXFEK8+aY5E1Avuc1Wo8QZNN+O85poamGmSL+XJ2GbfZ9IbaqIwpU+8v1Q7R5+NQ3zi1qUW2+QyXFEMk4rmpYPwh//ZwRtMcdWT15wWyV7Z7l3HWg/8494wF8=,iv:0HdYeBKqLyI3efP8aih+GjTWIslcwhDcY4EP8iv51Uw=,tag:Qs6nX1LFNQOCXOTtcnKDhg==,type:str]
    version: 3.13.1
