apiVersion: v1
kind: Secret
metadata:
    name: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:rlWUAGO00+OsspCgB7NcSvLnC0dFus3AiknDkgYklqvArW9DDt8Q1RE3RYcS,iv:MpTEQ1481H8sLjYXSJDkZoQriek+W28JQDiHDFOQK0Q=,tag:s30NgVhIaSZe0zZwY3onSg==,type:str]
    postgresql_password: ENC[AES256_GCM,data:aupKFp3lju2I6ZmkigeeMvKeWi8sn2Wgv1srSRsg90XXJyv882CYyRuZTyuBO60=,iv:+2dlBNOhkYrJr8EsPZwna4c69c37i6nZfOFhMZKoF14=,tag:d5G9Au+Q8YvptHe0qQsGxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc0JqZEJMTy9DdWdtMVhp
            S3VTOFFyeDZ6YlJOcXpjV3VVVnZjQmNNM2kwClVaL2NXVVl3dEpsSmY3RmlYTnRG
            N1N6SlJnTjBlQWMzSVJEOW1wbFFhSEEKLS0tIDJPUlFZWTRPUk03WGp3T3d2TllP
            c2g2OUNPUDBxV0R2dGVpcmhLK2lwbTgKeipese2nJ5IzwsSUTXjamGXIn6yM1Xg1
            KyYQEMc/HMAuMdrnoMNTeplhduE7y3UPM8qZGx37A0ZI0rNlZ8cUEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T04:20:17Z"
    mac: ENC[AES256_GCM,data:+JEFg1BGEIo7kHOmIbl34hLliDU+eoQHpCG4/EyJd2JMhOhCkmXgFfjgG9CTwwnybO5n9XfPHweIoZIfKgeIczZgeH5sNxBzA8snOWpLRlzegn6gQoj+Qb8T2utaaWV+Rhmv/a6NfPSFd6X9rYOdesafXN9qYcARNDhBaOrHEHc=,iv:jdTAlr8L1i4fp26Br/bfBeuAcvSW8OUjj0uHs8UjAb8=,tag:cSZyPMTYyuMZ/cePZjziJg==,type:str]
    version: 3.13.1
