apiVersion: v1
kind: Secret
metadata:
    name: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:pYqpBkSj6mafiqCeTRhMCNXaAflVFdDZzI1V84ps3Wuo1opyxAIIJN087NoA,iv:y5K6dvU9kHFKPDPw5h05BccR1egnImOE/NzjaZrgu54=,tag:7ppVO7WD8OvpUF22LUJM1w==,type:str]
    postgresql_password: ENC[AES256_GCM,data:wJ+3fSKM9xUtXXqzpfryOKQxJVhinDudQ2k6U2Yg3zyJhVFsEKq21Jw4dpbN8HM=,iv:89WHFd2trXDZ7szeZmZNAf0+3bCtJ6Pzhq00avnNdKs=,tag:1IvmCMSc6ie90qKKPKfxdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNEJNeGtnRHkxTHo0L0po
            Y1pZVHFmME9pajJhVkg4L1lJUHlLTXA1QnhBCjNFdlBYN0kzeFZ5elJxWHdTNkV5
            ek5hSG5BcjA0VlN6VWlvWmFmbTdSS00KLS0tIDVLaFdsM3U4WHBGV2RKZHY1czBh
            M20ySHNHTG9ReGc5eHNxaUQvU2dVS3MKjCMpH8HoyrtQ7wC/3scN+kYZn3VaLkgx
            5QkM8PZ1jaa4TEbmc/96++9wnDi+4kRVrQBTpum4mRIizgJNb2/6JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T02:59:34Z"
    mac: ENC[AES256_GCM,data:jKVS9UVPb/u78l8v931cJ3IMfDS8KpLH2ubD9aoXeKiBBJ2muSEvu0dURvcLOKXDrZ47Zn1q223u1OXs0HJ8UhxtG2owlAOBg6qHxuUH+TvqwS55RXHPMptGHYkfTYiSx3BZPWNJs+x92jU6u/cSibM9VwpnPkr0MxGfw83+xv4=,iv:otjBQ2O4VIE8TgNBSCnZcR+cEWsAnGExm/mrNZmE48U=,tag:Eo39IVM0Ti1S4Y1m2Wld3w==,type:str]
    version: 3.13.1
