secret-key: ENC[AES256_GCM,data:93JjprLYXI1e5+OCOCmKjzmoyK9RIjw=,iv:duxD+BLHx/47Essb3AL1Zwwp1TcP/kKePUcFjuWZna0=,tag:czTL/TO1z0sNheq843XsKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VzA1ZXhOcmQ0dUdPRWRu
            RGJrZldpRy9DNTRFdHJqS3pod2NwRTBQWEZzCkhhaUl4Z05YTnhWQWFrWHBWNkhs
            d2x5S3FrUWM4ZURDUDZNMG9aVWFWNlUKLS0tIGovVUlEMncrdWp0SThKZit5djky
            OU5YQlZmRU1kOFlrSGxOZk1tU0swZU0KYTcN+eXtdDWrX9oU9Q0gn60wtZYUJA1U
            TRBZyKSeHrh9JAKMmj5V5ThbzKnmQN2iA7joIxRmiSneP+xRcav8xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    lastmodified: "2026-05-26T03:07:14Z"
    mac: ENC[AES256_GCM,data:Z1ze79muj0VxpVIG1pp+iwuMh/4SzpVJnDsUhpT7BX0rFR41iPWGZJlOpiOB4hqenM6hnbLLZceTbAJoR1I3BaXQtl/vvvfFQg7VWNR6sIqUrT8/IdQAmoFpu0hOb4mnNHSr6IOT48/leiuIiqSw2lhTWfJYI26BdEtW3DkUhvI=,iv:i7hrTEV8SH7uAk2H8FgTPjzVXbdknQ7bl5hiiZpEmrg=,tag:QjayYQo4gmqbpbNwHPmATw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
