- name: Create external-secrets namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: external-secrets
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: create infisical secret for external-secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: universal-auth-credentials
        namespace: external-secrets
      type: Opaque
      stringData:
        clientId: "{{ infisical_client_id }}"
        clientSecret: "{{ infisical_client_secret }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

