helmDefaults:
  createNamespace: true

repositories:
- name: external-secrets
  url: https://charts.external-secrets.io
releases:
- name: external-secrets
  namespace: external-secrets
  version: v2.3.0
  chart: external-secrets/external-secrets
  hooks:
    - events: ["postsync"]
      command: kubectl
      args: ["wait", "--for=condition=established", "--timeout=60s", "crd/externalsecrets.external-secrets.io"]
    - events: ["postsync"]
      command: kubectl
      args: ["wait", "--for=condition=available", "--timeout=120s", "deployments/external-secrets-webhook", "-n", "external-secrets"]
    - events: ["postsync"]
      command: kubectl
      args: ["apply", "-f", "manifests/"]
