api:
  dashboard: true
  insecure: true
providers:
  kubernetesIngress:
    enabled: true
  kubernetesCRD:
    enabled: true
  kubernetesGateway:
    enabled: false
gateway:
  enabled: false

ports:
  traefik:
    expose:
      default: true