db_name: "{{ lookup('community.general.onepassword', 'postgresql', field='database', vault='the-black-lodge') }}"
db_user: "{{ lookup('community.general.onepassword', 'postgresql', field='username', vault='the-black-lodge') }}"
db_password: "{{ lookup('community.general.onepassword', 'postgresql', field='password', vault='the-black-lodge') }}"
