creation_rules:
    # Ansible
  - path_regex: ansible/.*secrets.*\.ya?ml$
    age: "age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n"
    # Packer
  - path_regex: .*\.pkrvars\.hcl$
    age: "age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n"
    # Terraform
  - path_regex: terraform/.*\.tfvars$
    age: "age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n"
    # Environment variable files
  - path_regex: .*.env
    age: "age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n"
    # Infisical secret
  - path_regex: .*infisical.yaml
    age: "age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n"
    # Dev kubernetes secrets
  - path_regex: .*kubernetes/.*secret.ya?ml
    age: "age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n"

  - path_regex: .*kubernetes/.*test.ya?ml
    age: "age1yubikey1qvep9uz5xzds4azvlrf5vatl5gmfj48qr8huw5009quwffzvwv80c9avq5j"