apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
stringData:
    POSTGRES_ENABLED: ENC[AES256_GCM,data:6CweKw==,iv:bwyn8wzoKxUbuEdlu6pmhyQiE8Z3Nwn02fR8FASoSV0=,tag:MA0jSxQthFkawO5olVlPIw==,type:bool]
    POSTGRES_HOST: ENC[AES256_GCM,data:C+CIIthCNRKUT8WXsTAKjbGoj2qJOTrfEna5gmjC/rkxiSF8ab/57+H021Y5yOg=,iv:4CtoWAqTEbzdDZFAKdRL9Dzfg3tpoMGg9V4RWUONLio=,tag:lwUIOkfvv51QuSrhRqQfpQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:aDeznA==,iv:wkd0W3pABIo8EaQyFVoFL6H2oKiY4bY0z24VFrhIuUA=,tag:q6KR162G/HlO4PKpwIf7dg==,type:int]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:SCYdKYc3,iv:ZgVsZ4JpyfRAtI6K+Qz6SjHWp4HVnzVwPG/3MJlzFdU=,tag:E/BYXt1WKQuhCRKCH2Y+2w==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:9Ix5CvbF,iv:0sUgEPjhJ45D7ZG45arHzQFaDFtsuo27bbsE9QoiPHQ=,tag:E6ozh5KcHoqvh7cq4kpOUA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AxSSnXYfDJ26k9vREtwAkaIIV2/MD+ijaTBFytud1GEaB/qsq30jU1564VU=,iv:FUArupRzfPspv6f17qjXk/R0jz0gg/YZkEZKJC1JbpM=,tag:xSy/gtw7aaF1XGNk4V+PyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T1hoU2dTaitqNlNRK2NJ
            clJtcUkwcDJZczZhWFRIcys3WWIya2lXN0dnClNQR0tyeHdKOXlHRE1QK21sUnlQ
            dlpxN0tNeWEyVUN5QlVxMWtEVHF4dlkKLS0tIEJvQ005VTYwNGNmWDdhQ0V2aUF6
            VU9EaWIrMDk0TWo5bDVtdHFNVk9KR0UKvS8wUBK3EipqOyfeMYSasCt1HplM5zrT
            cGXUXWk990fVn3Nj33SP/bjQzn7AcAHT6SYG9HTMJrPsECDvzIYMNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:22:31Z"
    mac: ENC[AES256_GCM,data:4LLOJYREDW5oPqWU75lcvJxpccdR8iKo0ANoVos06Mpllo6nvjxYDxnfn73MBWpsvxcvNnCICXE51kTczH/JJRewKLayuR4uM89F5/NToM+Ge5VUyADJbMFH7s+ncn0Nin4lc5SIYIAwzSSr+p7DfguTRt/TwCu5aYAVhWa1dvI=,iv:KPGB/WttOCQPIoJZ4qbNBzji24feukWocUy3tyybhJc=,tag:+KVl4a5XZVLrEX7x7K2onA==,type:str]
    version: 3.13.1
