apiVersion: v1
kind: Secret
metadata:
  name: headlamp
stringData:
  client_id: ENC[AES256_GCM,data:f//plGkTeqM+McWOGjg2gsh5rCE8d5cTT6X9SDy296RxMPtQBlH1hA==,iv:aGO+d54zLGR4PkfodBT+leFNrwn4TvufkB9IYmSCl7Q=,tag:efFrpwIOO/cl0Cmu//pdOA==,type:str]
  client_secret: ENC[AES256_GCM,data:WgcFUVdYy/M0AcI8D35FNy7Y6xjS9Ab5kPsK2eIs+GKE6l8Botwvgi74XKxRTiV+Ao06udVtr7vEBBUBTL0FechsziKDJljyfUkRY5qKW9Ii8BWKJVY1LzON7lIZg81GiimO3nMdicKh2tgX2ckSANV75Tej4hD4QDBeTARZ4pY=,iv:uuOFTCJSTmPlFlBO60btLU2mUm8+g8K4Bt01KZBj5hg=,tag:fT17Ay5Hk6QXDLZf5cQxKg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS2NSNzUzR2hOd1lCMDBa
        ZDNVWklMTENCTUw5WGFCVDg4MWY0bVlTeVI0CkswVUZFZDZPcWxxYmEvOCt1dUMr
        Q0hTbitzZHdJa3R4SlY0WmlPWjhwdWMKLS0tIG5DOFQ1Uk5qSi9QK2VyR0ZjSm5T
        aGtjQU0wRmYvQmpYcDN1SVdDOVMyM1EKuLx4dTwWpRvXjoXCu4w0p6PEB6JcWvBw
        2YO5O0V7MczWDR08oTpXfxfV208oC9M+fe/iZWeQlgteJuXEpl4zPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T03:18:13Z"
  mac: ENC[AES256_GCM,data:3xHHKJN7hlN+f389SU8NoemI1Fi1Etaz1yvzlhh3caqTc5J2sie4wy2Ejy4/kUW980/GxK4Zv17yFHNj7IKjtMScfAZqXgxOC0HPRq4NND7555uFNEgYrIupoxB2cwzOFEF8brqED3GKkq7DTfvvhvAkLL2wLmlRKX0AWI+xKRg=,iv:F0qKHflJxJ7XTpzJL5zl3ZOGgO8cmUJkK1ncNE0ycA4=,tag:2Fjsunxb3iHHnONevnZmPg==,type:str]
  version: 3.13.1
