version: 1
metadata:
  name: applications
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:

  - model: authentik_core.application
    identifiers:
      pk: 96b95f2b-2eb9-5bf0-be8c-ee5f9d66b9f8
    attrs:
      name: Headlamp
      slug: headlamp
      provider: 22acca9a-01cf-5e36-bf30-3ec104384e08
      policy_engine_mode: any

  - model: authentik_core.application
    identifiers:
      pk: 25b83442-3c34-50c5-8619-89c0ded6ed91
    attrs:
      name: Pangolin
      slug: pangolin
      provider: 680eb332-0436-55e9-bef8-2a2b7fb494aa
      policy_engine_mode: any
