# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: authentik-custom-blueprints
    files:
      - custom/initial.yaml
    options:
      disableNameSuffixHash: true
