
- model: authentik_stages_authenticator_totp.authenticatorTOTPStage
  ###################################################
  #                       MFA                       #
  ###################################################

  state: present
  identifiers:
    name: mfa-totp-setup
  attrs:
    name: mfa-totp-setup
    digits: "6"
    friendly_name: TOTP Authenticator

- model: authentik_stages_authenticator_webauthn.authenticatorWebAuthnStage
  state: present
  identifiers:
    name: mfa-webauthn-setup
  attrs:
    name: mfa-webauthn-setup
    friendly_name: WebAuthn
    user_verification: preferred
    resident_key_requirement: preferred
    authenticator_attachment: null

- model: authentik_stages_authenticator_validate.authenticatorValidateStage
  state: present
  identifiers:
    name: mfa-validation
  attrs:
    name: mfa-validation
    device_classes:
      - totp
      - webauthn
      - static
    not_configured_action: configure
    webauthn_user_verification: preferred
    configuration_stages:
      - !Find [authentik_stages_authenticator_totp.authenticatorTOTPStage, [name, mfa-totp-setup]]
      - !Find [authentik_stages_authenticator_webauthn.authenticatorWebAuthnStage, [name, mfa-webauthn-setup]]

- model: authentik_flows.flowstagebinding
  state: present
  identifiers:
    target: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
    stage: !Find [authentik_stages_authenticator_validate.authenticatorValidateStage, [name, mfa-validation]]
    order: 30
  attrs:
    target: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
    stage: !Find [authentik_stages_authenticator_validate.authenticatorValidateStage, [name, mfa-validation]]
    order: 30
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: false
