apiVersion: v1
kind: Secret
metadata:
    name: authentik-custom-blueprints
# Authentik uses 40 characters for id, 128 for secret (for generating new ones)
stringData:
    pangolin_client_id: ENC[AES256_GCM,data:yven4AIi0V8ia7OxF3EMy0vHSCEvA9o3kZdaQCmQNmUYAqI9RzhfhQ==,iv:M1yEKdOPW36KeK0WpfEgl9NmbMMKoNLVB4RpWfraQjA=,tag:tgj+TdH2w1idBK13Dw5Ucg==,type:str]
    pangolin_client_secret: ENC[AES256_GCM,data:eWQWZ1GIvsaI04CINvVaro6fD1oHviTOyBY82kEh3/Tx0FCPnNbRg5lUJ+M9F6XDD8L+TDmPPPe1+5P0P5oFgSSqeZjro5m7IV2AGdIYf5WBFSL6iNBZ/YMy5e+QWt5d/PiYxvbS+cmO+/CseR/+l1FRRYx3VHGhoTeB4hVK4Es=,iv:jGRtoq4sxwDaI2qNSB6/u7qdDwvhb452zkffcOiL6+s=,tag:l2bHUJ8/eYuCGkwr3oCKaQ==,type:str]
    headlamp_client_id: ENC[AES256_GCM,data:0iQ62T8MXcWvzd2rdDheETpy/VvgqDlefixYeXe/xzrYcdsHzPBp4w==,iv:XNrURRKLW83/gQOOu132BeFp/aQhdO/YZtCxMH7y0Lw=,tag:1YgGLq/gg/RHlkkzoB7GEQ==,type:str]
    headlamp_client_secret: ENC[AES256_GCM,data:o4wMW4EGMYz00uxno2OvGg7ROXLsYfQHq1m51TwVRvhsDgxd0ObjMHo4o93qbD6Fx8S5/gURvKIyjhEr3ZCrR6nlm94WzlQxOh1X5bmuhsTpA+U3e5Ie5tBZ8K8G3jQOD5bBHx9rizuJZLZtQnZdNtrxu+yUp6WUi/XuAaC0TlQ=,iv:8SpilY6/j2wGotVIbhek3wxMBsPH+FfM6+lw80m2eqg=,tag:E1WEzV4HFat5w/hWKTVhFA==,type:str]
    cloudflare_client_id: ENC[AES256_GCM,data:f7e6Y5v54pdALW//n/0ma/gZC9Sm4LF3q7kQaKMdfLHOs+kDzqvtVg==,iv:VrDSyq3Q4ZrhrdNDldldzA6IBRf4V7MW5pHk5xwYp/Y=,tag:W09FJgUkIeiRC/J5vIBXXQ==,type:str]
    cloudflare_client_secret: ENC[AES256_GCM,data:f9thIJQNvdcTuGEGdc3hAINjPDiFIpMViQyNL5XR5CVWn+cWg2TpLVWuPU8kGwxImcL4fyvg+41TufJITRRto6KO+xFtjg+Q8apJmY2i6qNWLvw95wgmF339Q75k4DVYhEihSHMeQ9FFi/pCPPavXj9NvufGgnnxAJzo4AEB9AY=,iv:oSMvcixUPlNxfUXtP1aSY9tEDfRpfy6+8IwkOKhWQ00=,tag:jwr2gqiFfnlSRxtjOIGQcw==,type:str]
    proxmox_client_id: ENC[AES256_GCM,data:5fePObk5wXepfw+PYTuh2Ad47vz1KC25b0PPm9oONztsJXFTqtscaA==,iv:ak6SfqxA0cc9Snhjk6T4HH0y54BZ9lQN5iMoVQl69Ic=,tag:2b2afOAPGSBuPe4FxIOaGQ==,type:str]
    proxmox_client_secret: ENC[AES256_GCM,data:Er351qVwRGPCmT3pIoYAeC4UiDDpjeJhdS06xJUNJsfp+T5OtGDYafo4G9h5OU4/IGaZJ329aUOY6yPYH4KpMP8UgPtF/+VFffFJN0zEqd7goCiNYx8nIaNSQcQlOuaQdu7+nbWiMwc2t0ST6ZXPMIlYp9/WqEaO2h3a6SVZ8uE=,iv:jSC+0vRZA7dyCCu9fkp7sZKJLYgmoLhz+wHcSOgDJds=,tag:aeh8c9DNjTDQQqFebQIPlg==,type:str]
    ldap_base_dn: ENC[AES256_GCM,data:gXKps+wWbF3PCKuB1jJfAbtt9TGokTo=,iv:ODB2/y8uaVB2GptSvwBQWdDLF7oRt6L8GPkApL4O4cY=,tag:EKGYajVzzgDU8PEi7zLtgg==,type:str]
    ldap_bind_cn: ENC[AES256_GCM,data:x80cRDzFDYUWQ/VujyuGCixcKWly9+beFsPKsgAAF8WiBzwqxQzXK8jCUAqCbtH+Ijl3zrmYRtFEFw==,iv:zch9I2/xVvlUtG17TgncBbQUPrEVL2ffWnoopjax7Y0=,tag:qlBa4BI5JlTKMWexPGx5jA==,type:str]
    ldap_group_dn: ENC[AES256_GCM,data:i2/L8Y4gBJvVy2fCx4uCNjc4hqc8,iv:7j8r2Vb7ZpB2bUgL5Te23uzkqX7Sy8Y/qVF0kqYcytM=,tag:VZp7FrTGLnta+oYzpi1/6A==,type:str]
    ldap_user_dn: ENC[AES256_GCM,data:+QluqwleNxqE3/Jn7GikifALIp0=,iv:xPCwuxKflI8BK8aDWn8q2dIUhbJfv37vW1QykeKqVLI=,tag:m7K1t0ZYokWqmD/fB+YO5A==,type:str]
    ldap_server_uri: ENC[AES256_GCM,data:nkCxRE7X0y4cUoCwpYnESnhQ9yw=,iv:yfwj8QD85nSMGQbTn9LKQw3606V9wVJnQAuD8rJWoRo=,tag:isoJy0XoPR2UVO/cv1cN2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbWJVMnJuNys2aUFpZFk5
            aVo5MGo4MVdCVU9ZUENNS1dEckEweUV4SmtvCnNtRjBEMHQ0UmVueXNsd0RiUSsz
            QkdqTGd3M1hmSGpib1JMbG1uTy9ENVEKLS0tIE9yTmN2NUE5TG1nTVQxc0UwR2JO
            Q2VxL0ZuZmtLY0xQcWdDZGhMdGVMb1UKyRo8jRe15tF8tvpsiSiDDGVKgjx2ZnLc
            kXRawtoZUUETB9fi2Kk31llslNVo3FuzOiU4IKUnKMffkwPRLNZc4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T03:28:23Z"
    mac: ENC[AES256_GCM,data:2ZhSQsbSDhrmJjqAl9/z53R4t416PRF7p01GYxYg/4HVj8s39mAGs2n9iAdsae97FphdnGbkPnsKQOdP8jpBmGdfKV2Lv0mF+rEaT66IZkXesxXpvSfII5oX+RVQlZxm9Y+f/2pe91+l1lTt0GdeadwFyUxBGivdFmOhJi1I3IE=,iv:fpa5ezvUtwuSPs0kjPVVmOJKuEwgK+JCx3KlpvYHd4A=,tag:DEBS49Sx533u8H0fBBzqlw==,type:str]
    version: 3.13.1
