version: 1
metadata:
  name: Users
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - model: authentik_core.user
    identifiers:
      username: austin
    attrs:
      email_verified: true
      is_superuser: true
