apiVersion: v1
kind: Secret
metadata:
    name: autobrr-secret
    namespace: media
stringData:
    AUTOBRR__POSTGRES_HOST: ENC[AES256_GCM,data:0PhnbCadNhzYaWcBwgfWOfbnb5f35HiioPwz3FEMrN/6crmkCIculTKz73XH55I=,iv:fkTd6k0AcKcErqzr4+LMru/5xuDodXlyQ8bKQ1zWLRs=,tag:GATkAgieLfvSTLYXB6WM6g==,type:str]
    AUTOBRR__POSTGRES_PORT: ENC[AES256_GCM,data:+P0wvQ==,iv:8D5E7ZJHnuSggCzfI8bpIBbDaXWHQBmbHnXbwtAjK28=,tag:/YuNlbUt43PlW7YjpRsfKw==,type:int]
    AUTOBRR__POSTGRES_DATABASE: ENC[AES256_GCM,data:iibccfxMdA==,iv:pefQKH3FCCN3btkBvWTQKEovWsYMBBLxfGo+jY9qukU=,tag:EjKkF5sLcDqW2jr5d+lnmg==,type:str]
    AUTOBRR__POSTGRES_USER: ENC[AES256_GCM,data:ETr3E+qJhQ==,iv:waACUBN/eL9e7tqjY2wjdDq+/VA3dEDLZr8ZYQx8Arw=,tag:Wd4wtU9jvnLMbcLZSz8R/w==,type:str]
    AUTOBRR__POSTGRES_PASS: ENC[AES256_GCM,data:rVnObuTHYGswJUDf4RlElSKSHtGw4m9J8pFEFoR2+wrasTgkbf2opdpqvOo=,iv:Wv7rBD1lKgcQz6OT3NsHVK3b7PV3ghilV74aa1BGk+4=,tag:pySbGbIvmGU4Yp+lz1tDjA==,type:str]
    AUTOBRR__OIDC_ENABLED: ENC[AES256_GCM,data:sOT3IQ==,iv:4XYc6aq31BEx1KkH6jEax4V2i03EscKy2M1s9IQ3JFg=,tag:Lfai5AQq6f3wmoEXgP/V9A==,type:bool]
    AUTOBRR__OIDC_ISSUER: ENC[AES256_GCM,data:hSQIFm9DkzQO0qbyNasGnyW4kYumfeiofJuCYBde/TjunHL1wi8kvOjartCn6nNNhHa274oc6ALORA==,iv:IBkdHwNEOl/59u71+tb3sconXY0+REHwgcFXhb/prgI=,tag:W5sakkS9U7IEcxG0PeNC/w==,type:str]
    AUTOBRR__OIDC_CLIENT_ID: ENC[AES256_GCM,data:QYVyFIpBssyFy0zo3+URc2xQcLKqef4jtOu3tghh3Wx0ALN+R0oV4g==,iv:bxwJJJtGMXt28qAorIbYp1aRodMeX5LFeEcfYwZds40=,tag:HPzEE4YHfSoyp4c34h4S1A==,type:str]
    AUTOBRR__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:iNF3hvw+QFerRzM7fZgc2zrJ3Ok3/AlDk6yyt/Grr7SKekhX7qIcLTGuxiXo5jFrPxVrLj0BPBjNszzUNJaHOPlHomrWJC+Q/vNhOJDDCZ5Ku0MPRRD4hnmZ23MnqSSZdf4gx6XnZdnBoHxbygYWgDlfRoQAQRiy6jRaktgi+hw=,iv:2qAeJaecOHPqR7WMnNrsvYAXelhhTWL427nkr+DGfzg=,tag:/MSJCaql0d5PTryAaS3abg==,type:str]
    AUTOBRR__OIDC_REDIRECT_URL: ENC[AES256_GCM,data:5tw8jciWINmR38yHvVTx0lu6m14k0sJWGVVcpLa5SDB636NOe6+HV0Zgq0xYlvKVQD68vMH45RA=,iv:BmPSpVMFagkDogsmUqaBlQ2G4+ugSAf/ZzsT8gRy160=,tag:trls+yVzVrnfajzI4wh59A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcWZwVURrd1ZQQ1VkUmdo
            MTd5K25qS2FFMG5hZWR3cEJkWWlqRlpUeTNvCk9WOHgycFFzcHRBWjg3QkwwZXZR
            Vm8wV3NMWjJJMkhpOUVJbU9nR1h5MG8KLS0tIEpwT1Q4anNUdjlQQlk4dW1iWEFV
            NW9QVmRPQXk1eEcxSFhkL1MzOFRoMzQKDJgIwTZ+BZiQvAiwZGOkPqXLD8FRWxUD
            1WJdjFFDImUzZPwOSWFxdGhMmJNe52xzsGUIzvGxRLPeZxTNGs+Twg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:22:39Z"
    mac: ENC[AES256_GCM,data:cCl+bS+TxfqWAjcR4worUc09o4ML+7fvE2MtWQxyWL8SoRDLtfiNDZnNcBzk6HXOzmr79wExqeegMFFSfW9aF5Jjw2JSq8nQlFrM2zce3qpko0JlmpajJ6uxCxuhD/du2cglxdtTj44hSN7Izb1xQOR5NbD4dq1ulOOFdIP92Gg=,iv:4hsH4l2yuP741EgCpRHpeCqaler+8MJU4Q29XpMZI0k=,tag:gnrjsnPTIPSY3+sFCDLnfA==,type:str]
    version: 3.13.1
