apiVersion: v1
kind: Secret
metadata:
    name: autobrr-secret
    namespace: media
stringData:
    AUTOBRR__POSTGRES_HOST: ENC[AES256_GCM,data:zfDBhfApWdb5ZO6Sy5eQsTIbw07Gw3QAGjQcEiLM/UHpseczk5w+Or4/UwWlOWA=,iv:K8FsSfGiMWaTbxE0i+cV4LLA/bbWfk5O6tlkZiS7vx4=,tag:7/NOGpHTe/ZT3eHBNCDFBA==,type:str]
    AUTOBRR__POSTGRES_PORT: ENC[AES256_GCM,data:mhbEow==,iv:K2xjwrmssJHE10SM0mWfbIhWDJyTomjjzcsGfo8fXBs=,tag:LWuDNi0xWD9jKil7FJGsug==,type:str]
    AUTOBRR__POSTGRES_DATABASE: ENC[AES256_GCM,data:m+7RRnDIpA==,iv:hTelhgVEfrAcqOSj4allg9njqSSwZo0UapGLoxEG+Ig=,tag:DiODXZTYYmjXLrjfIQH35w==,type:str]
    AUTOBRR__POSTGRES_USER: ENC[AES256_GCM,data:sCrHvhjhdg==,iv:uugMjRqgwHxtpkV46iLyqp7eQ9xP/Br15lpvwHIXYDI=,tag:RYINshlYL/oU2xfzfQSW+Q==,type:str]
    AUTOBRR__POSTGRES_PASS: ENC[AES256_GCM,data:WaHSqajmLRT3IpV4zsabxfi3X7THcjfwgsHGnLuhmSOJz0MAsURZ99Zhs2Q=,iv:okqTo5P92pHQqWOV86d2vSivQcpSV09h07HVBjrs/z4=,tag:OkDZUtVUZgjUpm2+pjxcag==,type:str]
    AUTOBRR__OIDC_ENABLED: ENC[AES256_GCM,data:QoioWA==,iv:8kbAR4K67sT+eVkza2kTconlgDx2AOQ9hZ9ag3c4jAM=,tag:J2B2DjUk3k+poAEkRcCi7Q==,type:str]
    AUTOBRR__OIDC_ISSUER: ENC[AES256_GCM,data:vnlsiv/CgyKYkMytBw67TiaB3mlr8FC4gPvIMsE+DkffBroDHbErG8pnbQQWLSOn/cIHGWl4R/0biQ==,iv:ZqZPbfkk97qVpNjXqbcPPY3TIiWJ1AMmBSeZpKIvhKg=,tag:ZcGz3ae/gpTz2YQGJxWSCQ==,type:str]
    AUTOBRR__OIDC_CLIENT_ID: ENC[AES256_GCM,data:gv35pljlOe8kiehJg2g+Njy/yBdsFz9RXcEV9wH6URI6fF6YnrdH+A==,iv:mv/im1ejCC6K4QJJqCNBpmczacxXIeFrR76cD2muonY=,tag:s/30dqFn+gc1+qmjtuNiXg==,type:str]
    AUTOBRR__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:NwPJAzyUpUt6oYjNaIpaQvKv/oSeEaIYy3F/nUlq1DLh5QovxEpOB4bDTgEx8vKEH6kO5AoxniOQWvzo23jCUnHe4g+j0hW/JtfLo+1W2U2gldIDsouUKA4cTTcpQyMZVz39sn3dhB8vOYFSRLiIT+lhOTCG85Wa9VtHeb1ahRI=,iv:H/rbJTQG2SFqP/Bm5pB5gasyKXL8ej5uIfX9Wd3zEBE=,tag:N/NXphRC5ZOquY+YgLRgtg==,type:str]
    AUTOBRR__OIDC_REDIRECT_URL: ENC[AES256_GCM,data:+J49FT4xsQfJkVKLkykqXewJlDFCY8sk6TewySfc47agZSAM/WCAZNif5L9eFnAjUrVFT9QIDJ8=,iv:+MSjNJDoH4gRpPNaHuLKnpQL4J2HKEF41uxT103XYMw=,tag:RZ8bvUk9BNXMEsYgpxYVVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY3h0UlZ6bVZwZjl0R1dx
            S2FxT0k5S3A3OE9oYlc0UE1qc3MzS3NQbFFrCjU5TDNaYUVGVmhVQVpKQzZta2JB
            aVJncjAyeThUdDQ4L0VFekhFTkhReGMKLS0tIDFWbis2WHhMR01KSWFhN3BGSDBP
            cEZvVXFoQVVzOUcydmFQaVdBYXdYbzQKn7aM8fGnyZkJHT5SDVi2tIRz/fYjnSH3
            BRViTPYGWsgFgnDePSKxUpzGfdzrubbSoBuBKXDGmypHzhr799u7xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:41:06Z"
    mac: ENC[AES256_GCM,data:rwWg5+1GijmLGVVlv1UcXIuJh+QLFCMe8xiDYdHtB1SryS0HCcNvFYIysu2pnQ1JTDOVRdXZOLPOcrioqa0mP8BROSGqqihGN39BDOq/n2hhotCQF9RNhgjy9QITEIQX8cnMaCp7hz0yps5hlYNRNI2Mo9iyHQ+mXtbTbz4m3a8=,iv:vZIyH3eio2PbUpM5n7p6Wy5xsw9ZhlRyQWpWi07z6js=,tag:2e71MCm/tKQA457oSx8Y8Q==,type:str]
    version: 3.13.1
