apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustdesk-api
  namespace: rustdesk
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api`) && Host(`rustdesk-api.example.com`)
      kind: Rule
      services:
        - name: rustdesk-api
          port: 8080
    - match: PathPrefix(`/admin`) && Host(`rustdesk-api.example.com`)
      kind: Rule
      services:
        - name: rustdesk-api
          port: 8080
    - match: Host(`rustdesk-api.example.com`)
      kind: Rule
      services:
        - name: rustdesk-api
          port: 8080
