apiVersion: batch/v1
kind: Job
metadata:
    name: rustdesk-api-create-admin
    namespace: rustdesk
spec:
    backoffLimit: ENC[AES256_GCM,data:nA==,iv:tZ0zEnEUvYdv5P1LNgkT0wArCWdg5c8sqCRLjws4Iwg=,tag:N1n7Xmay6bYfSsLpKi63Bg==,type:int]
    template:
        spec:
            restartPolicy: ENC[AES256_GCM,data:zl4NitY=,iv:7R0YNnEcbr5xVMN1ZBRvhWU3+xcX/n/rYHN9Zdnb+j0=,tag:eaYt+Zr8yGn1/mp4Ux6Mjg==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:oqlEGERz+MIJSEQa,iv:GAZvCUkjztyBrAosYohHkXtz1qxvigZeoqeL5khvOdM=,tag:CU8kb2km9EVQLWsixOc5UQ==,type:str]
                  image: ENC[AES256_GCM,data:zBzc6V04dYThk7WyEIChj6h0ZVjNxTAAkVLY9YAYHd0dd1CdTKW5O8OVBI0dT+JCCw==,iv:zpjimeYh9/FE1jqcXiMWqATelWTSqytSQlPrV/AofcA=,tag:rqnvxmsLUOfJClegLJJUfg==,type:str]
                  command:
                    - ENC[AES256_GCM,data:58NDiu9ULKlyVCNn+sQMuL0XFB0r7RXGZJQjTg==,iv:hk/iw+u+zcKn8torgNrBSNTR3BEIHa3rtbmBZtrT+vk=,tag:9qujNJT0b0AQQBPgFK+8TQ==,type:str]
                    - ENC[AES256_GCM,data:CHrftg==,iv:iUbIjURRy4O6kRWeeaeH0vTi7BmXfbtQzubX/gmT8vM=,tag:vUsZUdGNeq/Q9LmK09u8lQ==,type:str]
                    - ENC[AES256_GCM,data:tMSl,iv:w8k6CQjkRhc4SnxGdfRN45gB3X/RtVKBq82FJrn1SD0=,tag:HSkIhLFSSy0vbNOZz228/g==,type:str]
                    - ENC[AES256_GCM,data:UxSDdBc=,iv:/IMsWwAZMPpoVUeKSGzS61LjknIudA1SnRr4xhdKCRg=,tag:9TWMl5i6XdrG3aq0yG4JTA==,type:str]
                    - ENC[AES256_GCM,data:alNJhiYlwYM3Me6JSsfDLNyq02e0Rr4K6Uz61cQLt8Rswdkh9w==,iv:VW4xqCVKYGjTFpgXdqor/foIQ9+4PIh41axhXjsXdNY=,tag:bzcQcK19esGiLJoKl/5lnQ==,type:str]
                    - ENC[AES256_GCM,data:zSzNTMiBqQ==,iv:VvbldPypqudS7JvGPA3A+OaOQshrZI5lFwKkqtAXp+Y=,tag:0NTx6zTDObMHig7iMuAN4g==,type:str]
                  workingDir: ENC[AES256_GCM,data:etHAovR1OV9t,iv:I6HwI1r2+n8asUFjVz/ZCVhwttblrwMLYzoNlsqucoY=,tag:NF9srl9wtwVw95H9vIqGUw==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:7qrImQ==,iv:nI26dO6OY6+Tm1US3ic3jwBefaPNLN0yP6WBLQNqQck=,tag:lKIYG4C9i9kS8xRAsydVxQ==,type:str]
                      mountPath: ENC[AES256_GCM,data:79RcnBgX+oDK,iv:x29KsTw0X1BPjarUmIVbr540nw62Jd57H0vwK7DzXEg=,tag:F7GaEhAj1l57Mh26RHJfAA==,type:str]
                    - name: ENC[AES256_GCM,data:a9iYFuC0,iv:ftJ221r6DPswRcqV0wRkpkPaziQGdtGsCHLWMEJdw3s=,tag:yHcZ4wLa//OEFjMPtfJmOQ==,type:str]
                      mountPath: ENC[AES256_GCM,data:hGg1E04pgFx4U4xsEIAsOT1/Y1Jz,iv:eX/k4vIt5M5AwW2CgRSLEY06r/FneVYtbojcmKFJWLw=,tag:ntNrtxbX1AGp2F8b4ilK+w==,type:str]
                      subPath: ENC[AES256_GCM,data:bHczNjm53/dOXQY=,iv:Xk9dE1E0e+52ju013WSyK4beCVvdJDtj0n/Dt/VJv58=,tag:qRCmORg+lUciqKJCIKhlpw==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:XlZNOQ==,iv:B4kH+AgdLEVqa3HmgzjPG49lMFBE1BHJ9fzcUFRKEWs=,tag:D8YZjCLslKL4hXr8f7SiQQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:B2eAeVuZbMfRj/ZMKR+0ZaU=,iv:nlOBtPhVq3T07fl3t6wfKRs6dVNe6bNkQihGjJlKRMs=,tag:3U2PblYITGBZtOu5PKYJjA==,type:str]
                - name: ENC[AES256_GCM,data:AYbvyFE0,iv:Y9tWlsSDOi6qnw008IiLWTACUOoic+ZzQ5HjGTpb+WM=,tag:FYq0cDHDKgHoYoBFpI1lPg==,type:str]
                  secret:
                    secretName: ENC[AES256_GCM,data:e00LAivoj6FZ5hkwDW3uTwYuRw==,iv:k7hJ7UHiAotPUICKxMzeKbL2ja6cV01wLLBz2mu4AjQ=,tag:QA0nOQlBpmFZnHTiGZld5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdFRVRXQ5NzVKc1hBMmlM
            WW96dUJXTEcycWJ0cHBtalUwSXRzcVNDa2w4Clk3WndxN3F6eUNXbWhNOE1PTlN6
            S3A1TGk4aGZ5MjFBakFhWkxZSFdrNTgKLS0tIFB3L1MyNnR6RTZyWGU1Uzc1d2tl
            VnRxVXVJcFJ5Zk15cW1GTEI5NDA4dEUKRDDLqOxSJrIrY34aNRhCE7V5Vjh9blTV
            JSwXZ3NXuwuYC4I3fBc2rEDV8SZPi1t0XNjoRM3dN7zTfvIhlbbHRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-12T01:34:50Z"
    mac: ENC[AES256_GCM,data:V5jea70lxiWzwxbixa7gj64u/9Eg9XvSRpEsG+dCuiH3x3Akf8NeqS+01bDxAThNrvBCJmz7lmI6VQzhV14Zt2Upq0JasrVNtbferQOToJCQeVLKea6qHbWfhYD7T/QUj8WPDbQSoHL/um8U+Yeg2uq9on1MPF7XioBIMRYkWnU=,iv:l0Jd8BH6qrNT5NEB13vdh4bgOxcTDSsa53e5i1E+n/U=,tag:BUC7JkxoVKq4cmRJ5wfHbg==,type:str]
    version: 3.13.1
