apiVersion: v1
kind: Secret
metadata:
    name: rustdesk-api-config
    namespace: rustdesk
type: Opaque
stringData:
    server.yaml: ENC[AES256_GCM,data:8YuO4YbqWEpBnqfTNVHK0PYSTapD6OdgJGlNYrZxr32ii/yH5yEudyuSt0d+I7Msu5WEaFY9CMktvkveZz8lbHsapyG4ZT2CvCRF1KPX7e4GupS4MLmnpdzPHr3+dOrLBhUHeoznkr9zrjt1iaSNK+5H/t3dqHcOaGH2vWpKN+D9sEJFrUw9eIgGATrZ/r+mPvK9HyMPgloB+9ZQQO4kVphr8dQmTnnAPY5WqL5dftG1xfBc7jlfInMVhTdYLu7L9vyGbYfdd9VGBBD3rhqPfQkx73ri7giC3XhmdSbPeZ/PBre9qq7dTk3fv2RRR8jjpoKdfHXZA3y6s2/k8PLD/wftuKhbmbhAkZiAPgIGkCq3ZHv+zpi4bBZDevJxRLdL+VBxLWAxhLjXIVXRbtq/WD5Lv4EQn2dSicPxXsryfxhxnwwpR/X4kOX2LXHlaQ2XY/vtPVwoE3iz4C3lJUhWFiRVK6dZb46Pz4+mX3grrrJdANs=,iv:LLtDgp6qzWVA/vfBZFTkFTDYp24FZ6e1eghjS9arhXg=,tag:pcgzPJiixLwHmqZV9lBVmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZTNtcDhrTlR4T0Y5TjR3
            S1JyZndpUjkzb3JrWXl6M3V0TzNzYzY5em5nCld1YjcvNXNOcDRSUmQvYU1MZnJz
            Q0VkOThLVjlRb1VJZktjMkRiUjdKb0kKLS0tIHBYaXl1UmxqODAvREhWZXIycUF6
            WFVJYzg3VDhtbUFRZkxGVnovc2pKTFkKblBXb699YpxBQ+SZF/34qXvVQeg7f3m4
            PLV05QeomDdXEpliOpyMeAyF2jNo1Lurj7CmSGQGJSx6siTVHMc0Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-12T00:13:57Z"
    mac: ENC[AES256_GCM,data:cMwTcbHGqsc9Fo5NKkevy+79+kGL3d/BVQ0vlM623dTeLlV0XiMPVo5/rtmXhrYuzySyQG57n4yOkqD3Z3LKBfrb3aEv23FMqmhoaf1m27S9/sdGrcW1tPmsKHHEaD2HBwjDko5uLldXg1OT6sA15qfHCsSLowhY4iY6M/ftXhk=,iv:/POmCXvRfemI91grti3zzGkEa7K1gM1nqbBIsWH9e6Y=,tag:vGibAvT6MbVR4B3MMRp9ug==,type:str]
    version: 3.13.1
