apiVersion: v1
kind: Secret
metadata:
    name: rustdesk-api-config
    namespace: rustdesk
type: Opaque
stringData:
    server.yaml: ENC[AES256_GCM,data:G0I9y/TPZ16O+fCIr17/ZCXRhojeqbWXIgAd182yPTjV4cFOckn3orUuK/auAX/Qe2F44Q/pEgGNvCYszP838hns1jEP+DH8E+K2zFkopXV+5hO4AyOfTQfJ66ioOOmLw0wzN9ThCzzt4mhHP4Q5K5IVmA9lhhYaUPFLMAU/zNI58AZD81K8xp6oeLWcqSMUhiGBD2SlcUnSsD+f/yRf4cEuLqUsxPIgiZQ1uRlDOVsYVQh7DLO7qAwbszcm9M3HQo/a93U9zZq7oK5dCAWy7rn4QS5Bi+TgxpTvonp08SSW4hB9siQ9oYryHTe1WNkyURTlvCdE7Rjo/o2EAbzIYTR/bnXzgyHIlerv+ndMUAhYYdNEcrRdKQCOENBDe31oVEVC+ikG/Gh3f6ZNDBZRFefi2YuJlidvkbj6nNVumrZkOJTGf9idUif3vjU1t8SCU2NaGvyIk+2QIe4pNxigzsVX1DMhKiw1OSxovDe3EPidlDw=,iv:1uetR28gONxEiq0PTwyTDkDmrS++DBH8SkMdbpYs9+E=,tag:eAmBAvnyks8hI0XEDJlXdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MXViMlQwU21GVjlIN1hq
            ZlZVU25aNkJMK09WMVkrSWttbCswWWtTaWpJCkpDODZtdGl0cllHZ0gyVzFUeWJT
            cFpMTXdCTDlDUjAwN2pqcDVwQk14SzQKLS0tIFlIS1lUTngzSzFMdXVPbmNWb2lt
            K3ZJKzhHSWllMm1ZVk1kRVE5TkNPM3MKyS87ecYkcWdFyJ/8ucSSAa/r9KcXbrc1
            WK1TEtRxC2WSiNjFNWemlLzIcJaH9pWUGncTtmo1khvLjbk26uDKeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-11T01:24:10Z"
    mac: ENC[AES256_GCM,data:O3gK9rDd0bSVbRVe3GdXtd8Dv88puwowSzzQQRQal1NGqg5hcG2+D3ECFtUkab+AeNd+30SXCOI5Bfyz9jEAX57grd/6UJ1/6cQq+gOV68AIJZpsAvFX0ZwRY0z9h0A/UMVvFvsWq9Yt2UtV43RnGUHuPq/uUk3AgepsDt1n2Ec=,iv:fVI8jt1ftY3YO4eqDXYUPhcciUB+aSzeih9QVkcQIwg=,tag:pWXecangIP+BV+VizU3zWA==,type:str]
    version: 3.13.1
