apiVersion: v1
kind: Secret
metadata:
    name: rustdesk-api-admin
    namespace: rustdesk
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5LgwXPQ=,iv:+JjDsSznrpim/QdwRQbnrKKT+X64OF3H9YHhlPuG8WM=,tag:rzc/DSTMDMepwpdx4/MZPA==,type:str]
    password: ENC[AES256_GCM,data:fr27fxdG2xwmYjD4M3q+G0H3rCJoaSMDOWLJr28+CxGtj2ftGL9FEikX3O5otQ==,iv:EfucWG6czStKN8/fKmFjLg0aWqnk+j+sA86gUk9pPXM=,tag:crSuw8IJk1AMcXXfU6UGzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR1gxRmtTV3Z5eThCeFR1
            bGdEb1MxMGdzMkN1U0Zna095a2xoMkY3eWdzCkFYcmtQVlRiZkwwU1JPRUIwSTZB
            bG96MHVRZG11OG5IbWNLcGlBREYvL3MKLS0tIEIzL1ZGZWRQQWhvWWxFS2hmdFVy
            MVZJY2JRWjVLazBueGlVWWd5dGZTbkEKeDOF1UiBy+p19GedzP9vp7rK2NhVojuR
            zzN2v/ZRx+ThkJ/2CnnHBkEaTvhqQtVNGdoyTLjUOogxZB7Cx6DN/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-12T01:34:55Z"
    mac: ENC[AES256_GCM,data:I8LB7kjExxjahdLl+FpqWjsEUm6K6NuV96dH1ZZcb+02GgHVM9vYjOsJJ2j5pjhFyikRRoBVtZhCFjPt3xam+3GeRoFw+7oJCZ3ZmtX6zXDgGJsV13Lxse4qp59QHP4/PP9aAr48AnJChLH/APX6X2e6xo36gJ05EWqQ6ZY4YSg=,iv:4E7w1fNeFpg5iA4/35lUd2WzmTvHPb0w1JHoACY7XPU=,tag:4YbWALkDwNefgzYR7DQGoA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rustdesk-api-config
    namespace: rustdesk
type: Opaque
stringData:
    server.yaml: ENC[AES256_GCM,data:KVe1Qjn4GpzhteyHTcSx/Mb14gK/gfC/3L6TSBu/zDDGOakgfO2YlQETSzZxU9RPz+T7sbHOLseUL+bI7yasf3MSEYva7gWCfB+7grFBMuz4ve413V+NIUPyr7XCMOLpKIYhUEIZMx5MNyv19gO9IgmYy+OfX3KFeAI0b0fQZ2MJlaev6e01lUeY3jT1TiZFoKMSgbdhNDZhs0qU5T3maIafLjS1fHq8Wq8XxWqLzRkupYi5CTNq7Yx73elQwgCQQAQCjVwexIfTfJDQ8ttq5fZzHWIeYsFDIxtSRUARbsfRUDINdfMSM7J92XwwfGfs3wo2XAhJ6bCrSOAXEoP+m5L937+yACta6Xre7bdyk8kqxbQk+DtWglNTCG/ffZ+YtbQv/N5/7fLZ9y71mmi5s6rjd9BacWq6sjzICZEypfb8yOae9ao5HYYA4vZ/izPJoDThgbFAQc7G+CKuNz0Dms4vcwIngkM2Q+JX4gRi+bB4g4c=,iv:fL0pEIDPWR8VprfJsS+/o7JVoVVQjSU5S9nyFwF+YFc=,tag:GyxVGs1PuVRinka5DbNMSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR1gxRmtTV3Z5eThCeFR1
            bGdEb1MxMGdzMkN1U0Zna095a2xoMkY3eWdzCkFYcmtQVlRiZkwwU1JPRUIwSTZB
            bG96MHVRZG11OG5IbWNLcGlBREYvL3MKLS0tIEIzL1ZGZWRQQWhvWWxFS2hmdFVy
            MVZJY2JRWjVLazBueGlVWWd5dGZTbkEKeDOF1UiBy+p19GedzP9vp7rK2NhVojuR
            zzN2v/ZRx+ThkJ/2CnnHBkEaTvhqQtVNGdoyTLjUOogxZB7Cx6DN/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-12T01:34:55Z"
    mac: ENC[AES256_GCM,data:I8LB7kjExxjahdLl+FpqWjsEUm6K6NuV96dH1ZZcb+02GgHVM9vYjOsJJ2j5pjhFyikRRoBVtZhCFjPt3xam+3GeRoFw+7oJCZ3ZmtX6zXDgGJsV13Lxse4qp59QHP4/PP9aAr48AnJChLH/APX6X2e6xo36gJ05EWqQ6ZY4YSg=,iv:4E7w1fNeFpg5iA4/35lUd2WzmTvHPb0w1JHoACY7XPU=,tag:4YbWALkDwNefgzYR7DQGoA==,type:str]
    version: 3.13.1
