apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: overserr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`overseerr.theblacklodge.dev`)
      kind: Rule
      services:
        - name: overserr
          port: 5055
