apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: generate-tls
spec:
  secretName: generate-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - generate.austinsmith.org
