apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generate
  namespace: flux-system
spec:
  install:
    createNamespace: true
  targetNamespace: generate
  interval: 1h
  chart:
    spec:
      chart: ./kubernetes/apps/base/generate/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: generate
      valuesKey: azure_domain
      targetPath: azureAd.domain
    - kind: Secret
      name: generate
      valuesKey: azure_tenant_id
      targetPath: azureAd.tenantId
    - kind: Secret
      name: generate
      valuesKey: azure_client_id
      targetPath: azureAd.clientId
  values:
    fullnameOverride: generate
    externalSecret:
      enabled: false
    ingress:
      enabled: false
    mssql:
      storage:
        className: longhorn
        size: 20Gi
