apiVersion: v1
kind: Secret
metadata:
    name: generate-secrets
stringData:
    generate_db_password: ENC[AES256_GCM,data:Plp/bOStKKsLmptxJt6t0H3ZDGGXi1KtjxK5n/bokrRxKxd8DdrqaxvO8izq,iv:eZ2/ok7CGn/zmcz2zharHz9cPrtqaOrIjygZTw9To7o=,tag:auxawRCHrE1iu7xZwttzWQ==,type:str]
    generate_aad_client_secret: ENC[AES256_GCM,data:9gXsfHZCh1SNBEE3haxAHnKLbH8d2xWRUbnTPAM92jZeQifLZ0GmcA==,iv:xqJFZ++mrUAnCEwhebATpYwj9byBXh6cvtwsm/yctfA=,tag:XxVl6IIzda8qRhP/wIw1yQ==,type:str]
    azure_tenant_id: ENC[AES256_GCM,data:viaXt7OIA0g6anQtIoCTFtmgwZm/AlbRzfzCbhv+YwkQ0Au0,iv:ovy+qtu59T0sj+A2M+vSlyB6ue3PV1+mR2zmgwg/LWk=,tag:hN9oefJCojsA6DzPM3/pCg==,type:str]
    azure_client_id: ENC[AES256_GCM,data:FPh0NleEL9r8DTFSve5HZTb42Hb5ftYQGmhjkR7Cqc4tOIYV,iv:cS/EoKPdc7WBiSYWhhjdUX7by0SqB1gv4KN5ZIMHems=,tag:wduPhMl2EQajpv/FPzEhlg==,type:str]
    azure_user_id: ENC[AES256_GCM,data:3buCWSL7RJmbTEwxrK5jUV5A094/5i1Oueer2A3g6f66nzNB,iv:TwMHp4ppJaEjRfZZZd/Eytq1bht1QGdrBsqX2YyM+TU=,tag:PBc3AOj2wb4RIzMgLkFphw==,type:str]
    azure_domain: ENC[AES256_GCM,data:VdwRncO2oXwbJjjPOYC8wycWIpEA9Z7Af3hNr3JLI8guqwqD,iv:6IPXNYMhQcT6IikIuX1KyCQ9+6NQrdQcDBUZTnYCr/w=,tag:ZISi1x6rpElV0IO1dSeWWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYllSKzFEcmVaK2ZpNUhD
            OENtb3I2WnRWeXMwTlZJQVg2YnFreVlHMDNRCnFqWGQwa0o0akVkN1RMS0Y2SVk1
            OGlweHQ0U3hTMFZwZ2g5Y0JZeDd5VlEKLS0tIEtWMmNVdXI4UUc1REMwNUltUENO
            UEZhYzl3L1VjVXVVMDd6T0t5bWM5MDAKEJtl0Shg4EEJxXxkkEt4qPQtelb4GW3m
            FUzfEEQ7r1/IAqOgYdjUNtCYgO38/9cKymfbDzbH0aSTJBhxi1jS2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T03:34:53Z"
    mac: ENC[AES256_GCM,data:9dyj6RJlD+N0/liOobXtlD3czNZwDn+iBKCvRpf4ef6DEhVJ8LGr/BlB1diTa/qPOh+m81yiZx97fJqFi9k5ZXb6ErV1PthYeVRhJAQ/tt6xpD3EHig4d1duTV0dnU6ZBD91RJGP0IEErhPcFh16qccDKPe8xmAf53CUDSwfgwo=,iv:nc9QfFcaP1kZXBbsqi4mc+tRcRCr07ORsvTnrfpeurg=,tag:ecz91ISdX2B5aYhiZKaBDQ==,type:str]
    version: 3.13.1
