apiVersion: v1
kind: Secret
metadata:
    name: generate-secrets
stringData:
    generate_db_password: ENC[AES256_GCM,data:+JDJErV2BcYXrJ+LhlXLsWwrrDsW48DRRqGmWzzzzZyrkO9WkfrvOGFjY4R1,iv:Q0073yxXssGhiVDX3iq3jFuLS/aai1xUmAVY1lzelp8=,tag:ZeIoeyaGejgNWn2P6p84ZA==,type:str]
    generate_aad_client_secret: ENC[AES256_GCM,data:YoTDtiy/J34BJDm7qgtazRYAj2nYEsn5+7ms2bo+XiPW1IFL6wkn2Q==,iv:FmS63qRVE/V8jjO3BvXA1t6dgapCdScMktj2smCL1eg=,tag:aNtbmHLudlUQo9FvUsl29A==,type:str]
    azure_tenant_id: ENC[AES256_GCM,data:jRY/599MbgLwodx4VW7xTagzhYpgu3UMq95jeswlWoQ5KRya,iv:KEB6eJyYV1seWF9CAx9amXZvm0q/jfYEhXdROHYanvc=,tag:8AHH8ICD743YbEtPMoDsIg==,type:str]
    azure_client_id: ENC[AES256_GCM,data:+kn17QaABkd8WVli0W5/d8UpnUXaUcZ9gMaOsH3gKgb9yFol,iv:3EXWb+GPzD3e14SRs0ZFOJM247SY/XRUzh5vqYhJS74=,tag:vtucoLUJhyna45RNAJcZMw==,type:str]
    azure_user_id: ENC[AES256_GCM,data:3G4VDu3bZ2E70kWJB7Bp87bKiZEuhDL2J8vY38sqDNaVkeoC,iv:ByYCmSi1uzNy/1C2Qz0DcUNZeenwsfcr8fv7aclz3nc=,tag:0B5jxdMKEW6LPdiKd1gc7w==,type:str]
    azure_domain: ENC[AES256_GCM,data:/b/IVehQ/VeXxd/vSOBa0JOYfq6Q94XrZzcgViKJBNs8KXsN,iv:Y9WFJMZwVigWIybULKr3hjH4N8lCMJRok5/kPvjOLDE=,tag:kI0eAZ+0BWBfzjS0+CcwYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbWhxWEpHZkFtaXh2M0di
            Z3orYXBiSVdydFNzODhPdk1IVCtiNm5ZY2lnCk1HSEFkOGJUVG5BekJRckpsRnVE
            NzRWKzlsRVhCK3FhWWJaSC9PYiswY0EKLS0tIFd0Z0dnTkFNNW43RGk4Mm1ZTHM5
            Vkh6U1hISnQ3R3A2b0I4aG1GbXJ1ZE0KTiGbW4h3g9vETP6QoZI2oSPYewHIB7+W
            rcnpNVN+DoqPetUgG/RQY3kqrB8xv6scCBL43Kz1M8Pz3vx1kz9fUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T04:06:44Z"
    mac: ENC[AES256_GCM,data:8fVkBVskKGC8kOircvhMx380saJrWAzIWiba+vA3hey59/inSkla43UpyDfQs4g802mRKEN/GzHXop73odZMDot+4SHZ2iLWZidmV/jbW3HzyR5+pfveDh30u5t1lYxSr82PDYfqo2ES+/F55+KLi9jbgOJRpjK1jVHVr3RT9vs=,iv:WrKuWJKDRdEEJvi2bvIIr5n17j/C5GwyPU5tOpJQ1wE=,tag:whG244Vk/T3sS5xJTjYrwg==,type:str]
    version: 3.13.1
