apiVersion: v1
kind: Secret
metadata:
  name: generate
stringData:
  generate_db_password: ENC[AES256_GCM,data:4BwOR3lC95JXW1LrHF8x67V380FXyvjR7QEKFJH6Y17gGclkXLUv7+P+ebVe,iv:o/i1wqhbj5GTaJ2z8pUJr26zd2num7YTIoNgrSXBO9s=,tag:tx5RHlgtaWnrl8A57E6Hig==,type:str]
  generate_aad_client_secret: ENC[AES256_GCM,data:h/WAMpeg4X+u0ujYyLhY/EY07rXYg1HfGHUHRqf6uNCfQ/ymaVCukQ==,iv:UyJXYUNK9Pl/CEWqqSlMP5lEsI44HuS815baj0O6500=,tag:IZxd0mld7xSnnNQMr/YH0Q==,type:str]
  azure_tenant_id: ENC[AES256_GCM,data:4/Gtwm0f0DZ0LJm0yGpwa0fslZi0jark9itPlF/UChkDirAX,iv:KnfNyq5tA65DbPWTxsgx5alG7Qd21guk5LJDo1ij9RY=,tag:1tYZK6TlRVhWO5tCjsBh7g==,type:str]
  azure_client_id: ENC[AES256_GCM,data:Wvyy7lgz+uVWVYEFgzq9NWT7/MZx2CkcMxDvK7NspmxHeOdu,iv:HoM/ec5girPcoyDpR68CYpkPiRLVAq7lVDDO/CLRoE0=,tag:EA7bSP/MW6Qz9OlaDCUcGg==,type:str]
  azure_user_id: ENC[AES256_GCM,data:mBQ6TfxqjLF55yTRVrWAW08GYSmbPXqiHmWOITU5j9ifUUYP,iv:QBrhP2AcYNnLRvSTi0dh8iPMnqSD1475aFUK5p8xh/Q=,tag:N5imh5oDZ9tiehXwCvm3cw==,type:str]
  azure_domain: ENC[AES256_GCM,data:YKTFGbNmqyWTVVAcyODc8QHNuR24Qvu/c/VWQDr3Uly6kpje,iv:wDePulQ0qOvsaSd2iLHO6pULnHkWFmCZgYBE3UiI2uk=,tag:ElFm/JNw1vOGmEB7xnEVTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZStPU0VyaFRjZ1BQQkp4
        QlF2NU96TDVMdnJnNnh4VWFOYy9Zc2liY0dJCmgzQlowS3BVdEJYTmlaRnhqQ3pr
        WFpYRlM2YjZNdHduTTZzWFJZbkxhZDAKLS0tIGZoU2t2dEJQSmN2d29LTUJacURq
        dzczNm9YemVJdTd2RUM2eDhpNWpWKzAKLhw4uRtGA8OamDaUwsVB4ntwnvN7sf8I
        nL0CLyOMQv/MzlkwphjAclzeHNxcn27VatDsub28hSkisa4e+o/8qg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-04T02:53:12Z"
  mac: ENC[AES256_GCM,data:1/Um6jsNycT6iKR28akDwMAxby+8OXSphCZbAULcnV098zQfbufgwX/ahGteMal4wMkB4l4sgZKnNWdlKLYxJXV3a/cq3yVKIF90wDoIgjk4iJdWNfXAiO9WmocofeNGQiqC/zZKmWavxnTs4VCRdYVf+1JlLo343gxN8TAdIK4=,iv:AA0EU3EoDrdiTurwmg8p0mx8oTacmwpHVtQ936c0uyE=,tag:oGzAWaL6qpSbJwKCJ91JuQ==,type:str]
  version: 3.13.1
