apiVersion: v1
kind: Secret
metadata:
    name: qbitorrent-secret
    namespace: media
stringData:
    QUI__DATABASE_ENGINE: ENC[AES256_GCM,data:XZTRG0/C+zg=,iv:E6OQ6gW0YVJ1I0WjK8dVt8C4Ph/Am56rJZ+7BAdjqxg=,tag:mwLZBiOJ2FOWNw7XvY0ixQ==,type:str]
    QUI__DATABASE_HOST: ENC[AES256_GCM,data:uNNOHve9N1CAu7yVXXEZirKU/UQ9xSJx22ZqNTbihJdxi5IeC9whyEDNg2NjGCc=,iv:qdAoZLluEydYUbrCJ+MWmgE0Vauiy5h4V4tBg/4KduQ=,tag:u7W53xxQlN5p21S3htNMIA==,type:str]
    QUI__DATABASE_PORT: ENC[AES256_GCM,data:M9BSoQ==,iv:gdT3+KADFxh6vbxQnnKBKIwdu2EkZAZe9Vh0cbw99Qg=,tag:/NLo/V8naMLOzxQUbzFg5w==,type:int]
    QUI__DATABASE_USER: ENC[AES256_GCM,data:4x4m,iv:Twl8BInfTcZk6tsMmNqD8A5viNyIiquiYFyQ79UveWM=,tag:jk1Erl6BVFxlqKNggabY5w==,type:str]
    QUI__DATABASE_PASSWORD: ENC[AES256_GCM,data:hchOclsKkix3AMvfa2L5eZ+wrx1Oo1g3KyXRhJh74Ns65zOGiOHsIyfvzg==,iv:Y3l+CpWe/83+WdIXNuvSsf0fcyg1ei41RBe8rD8h21s=,tag:h7BsUcPpdN83o4qhE8MQpg==,type:str]
    QUI__DATABASE_NAME: ENC[AES256_GCM,data:C+PQ,iv:EIONPuM+duJWzbXse/muZJlMQsb+zB2pC1++l+KNKs4=,tag:9kKekHTea4aX+XVkNTCErA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNklBN05DN0NTbElqbXEv
            UFdvbVNkMUpIbkFwaUUweXg4UCtQYTdYemxjClgzZndxOGlMN1NBYklUeFdSSmNr
            VU5GVzRDUGZkemRjMExjUnM0dkc4eU0KLS0tIHhoTkhCcjYzcnJxWTk5NHVHS1Ru
            UGYxWDBrV1VXZi92bW4wdUtOc0JlL3MKbM4rEpu/2XW+zmZUPgemVGdM5crYFAVV
            TWaWFiTMZhYD/sTdzXm3ov3lHQGovouiFHxDAXDuisParKRhNhHI8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:40:21Z"
    mac: ENC[AES256_GCM,data:0hlyuBKwU+GDpmbzfH31+1u+M66ToSkl+jvglPOZTjyWN+N8/vkH9f0vut7sp2gGg+01stdOprkCkBvVWfpMtseXPE5O3B0SdmavRqtRoI4ZP6KUFUwqigg5t+MwwhTL9YWbtWTQ4E9lVWAEc7Ke7TXqe9ZtbyvpWGy3y62q4uE=,iv:9k60tiXw3ijLNtGDw2ANS7es4y2FBRsXb+xj0lrJEGw=,tag:IpY1eFuqEB8kGV0ffC5Tzw==,type:str]
    version: 3.13.1
