apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:f1Iqvk4Mf+/qaDiiu9jGbySZKXdYB3g31FEFbZaTnw==,iv:NwcmgcVaH1QnZ2NKfCJ7ESXssowEdUJWD6NC4Etxy+c=,tag:K61bw1xucVgL/PdJiPCl+g==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:BbtM7mujwyadSt+2C9twBH18qsTwiJUgefERJrSlGJ86+SZOUlcKkwNd+yo=,iv:kfQIxYKA8ifQE5wTJMSSi+P1dMcfWEG0MOJ+LWQI54M=,tag:slfeI3kDIkU4UCXOZ4ZjLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLczJhM05HMFVubDU3bXZv
            VlJ1Y2VUeEpSVy9HT1VTa2RCdkkvNDVIOVFjClo4WTBQTWd6bTk1cncwNFgvZTM4
            RmZGVmwyUm9KOXRkOC9UVlhaMlRKcXcKLS0tIGlJNmFUWWNOZFR0akFrbE5PSEdm
            RGx5M0V6M1VmdmlCLy93VUpSdVVyYXMKtR5FDoljOBM1tSo/Uk1KcPCjvzn+G2Vj
            rxcTQUxNAFXQ5SDS6gw8fDbFRSBzwpEYjrl2Jngc4eLqlV9yn6NExw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T01:31:26Z"
    mac: ENC[AES256_GCM,data:hrvEVzp63oi6dt6PwUuFrIUCSHC3fvG6/fBnG2ljNTHJeFWUVTgiDIoTI3Ezq7gBukYqnO42TDYniYknEes5uNUBxhLpYb7sC/yoYs1sHnPwcLf/beCX+L9O326hlW9FOZI/5ALo4HPDJYguzhgDroiXnzS6tjReAjIB4Hy6fMQ=,iv:HwqPactxZvnkK/5GKnYzjS0ZRXrnTxKOpe6ibOKk4Ss=,tag:pPODD6nr4m+jF4aRjKch8g==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-seed
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    qbittorrent_password_hash: ENC[AES256_GCM,data:AdJQBIxPh9Vb0YWRRyYq3KmoAYkF3doIweQ3OMpAI2IBS5eRoLL51jKve9EgJllXDkVWg5fCzxOrUoplK3BZoykonBaypPw3vhaFRX9eqa/QV3EDlIdz7g89naWDNzrUYegsMhG7LFGLjhhAI67ncRCDpnaGdMkBTTBhSFs=,iv:IgxhuqTGf4d0LaROraLyxEhEaQHuIV+5fMLzlkK6CA4=,tag:FkgiVZM+VueQWuigwBVeBw==,type:str]
    api_key: ENC[AES256_GCM,data:BNg74DLbSyf5PXlSXjrvDw47ZxV3dwVm3m0cnmxpnKs=,iv:/eHaD0dQy08JogsD5shHjkKc6OhpDx5j1MpjoPMYZ/Q=,tag:D6UlTR92PMJPIe6oL1/VCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLczJhM05HMFVubDU3bXZv
            VlJ1Y2VUeEpSVy9HT1VTa2RCdkkvNDVIOVFjClo4WTBQTWd6bTk1cncwNFgvZTM4
            RmZGVmwyUm9KOXRkOC9UVlhaMlRKcXcKLS0tIGlJNmFUWWNOZFR0akFrbE5PSEdm
            RGx5M0V6M1VmdmlCLy93VUpSdVVyYXMKtR5FDoljOBM1tSo/Uk1KcPCjvzn+G2Vj
            rxcTQUxNAFXQ5SDS6gw8fDbFRSBzwpEYjrl2Jngc4eLqlV9yn6NExw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T01:31:26Z"
    mac: ENC[AES256_GCM,data:hrvEVzp63oi6dt6PwUuFrIUCSHC3fvG6/fBnG2ljNTHJeFWUVTgiDIoTI3Ezq7gBukYqnO42TDYniYknEes5uNUBxhLpYb7sC/yoYs1sHnPwcLf/beCX+L9O326hlW9FOZI/5ALo4HPDJYguzhgDroiXnzS6tjReAjIB4Hy6fMQ=,iv:HwqPactxZvnkK/5GKnYzjS0ZRXrnTxKOpe6ibOKk4Ss=,tag:pPODD6nr4m+jF4aRjKch8g==,type:str]
    version: 3.13.1
