apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Tn2kYr1v6Ekvn/caMtfxr9CkITc4UR6qQ2GTs2hLec5phfb9AyTt47p5q5o=,iv:HxGD5/6zRHdZBZqSd0wcCGkiOvuhPSuV8JPSKGx4ERE=,tag:NYC+Irb8Q9wKY+CGKo29+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUFF3dmFHbGpLTUp0Y25x
            RjhpdTVNcDBjSkNFUFlaWkhzalJ5M0lIR3pZCkJMZGptTUc1UWdPcFdmb0wxMFo4
            YldUSUR0WFhmSCthQ0dCTUoybHF6V00KLS0tIDFLcnl5Q3dwL3M0SE1sTDdtQU5I
            a2xLWVM0YWlCN3YvZWk1MWpWK29qTmcK01UTsUN/0jQfC8ofVl1gno8Gl7hhnC1F
            4C78CZ2QmwABdgn8av+1dlad4qVaui35eIDswbZB9iqehDpaXWHOVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T00:12:08Z"
    mac: ENC[AES256_GCM,data:EXLRXK27WOa8k6/Yl3HcTb1XlP6SnMwtWN1rrNZX1YCpHQVE9fppz1dBo0YifkjtJD+cW4RdcKfwL5S4pRGMxLOhNGsua/pNAs26ZzAfUEfH0JoNaY83Z+9upuZ0rE/v5lYIwva2fbVbh9cSREiTQW6I+AwCxjjpU/bszeUtEs0=,iv:O/DiweOeKBy46mhmGz8wjpetdXUDMBl/h6kPe4k41SI=,tag:ApSEYTkHmU1caR1zVtGtXQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-seed
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    qbittorrent_password_hash: ENC[AES256_GCM,data:Qon6XigjdOCSKBxlEhHA4PB8rtKHLU+vmUQtEsBV7Z2OF6tL2nA/P1HFxN8xOmxwlwTJfWquS4C8Mei+S9uur06+NGUBUl1fTgVGO4sbrzDomUOm8RpByQT9HJ/g1us5T5jSBDMeLMjqiZrSI9A5YsCtBjbqmdPupIKIHiE=,iv:7qsD79VB6APnzJdtNbIgk6d+r8/Mepq/usQHcXlLzLc=,tag:QBo+y14D2CKS7rYR5PKoIw==,type:str]
    api_key: ENC[AES256_GCM,data:HPB2LOCjvwTzCDkoT2TIhtBFImhYRxNK/aSSqDV7pqg=,iv:4lc7UsArbcR43MVYzN+ygw9D0adKvFQ+iQOafQCCpKU=,tag:nR7ILL05RmavPr6UUuZs2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUFF3dmFHbGpLTUp0Y25x
            RjhpdTVNcDBjSkNFUFlaWkhzalJ5M0lIR3pZCkJMZGptTUc1UWdPcFdmb0wxMFo4
            YldUSUR0WFhmSCthQ0dCTUoybHF6V00KLS0tIDFLcnl5Q3dwL3M0SE1sTDdtQU5I
            a2xLWVM0YWlCN3YvZWk1MWpWK29qTmcK01UTsUN/0jQfC8ofVl1gno8Gl7hhnC1F
            4C78CZ2QmwABdgn8av+1dlad4qVaui35eIDswbZB9iqehDpaXWHOVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T00:12:08Z"
    mac: ENC[AES256_GCM,data:EXLRXK27WOa8k6/Yl3HcTb1XlP6SnMwtWN1rrNZX1YCpHQVE9fppz1dBo0YifkjtJD+cW4RdcKfwL5S4pRGMxLOhNGsua/pNAs26ZzAfUEfH0JoNaY83Z+9upuZ0rE/v5lYIwva2fbVbh9cSREiTQW6I+AwCxjjpU/bszeUtEs0=,iv:O/DiweOeKBy46mhmGz8wjpetdXUDMBl/h6kPe4k41SI=,tag:ApSEYTkHmU1caR1zVtGtXQ==,type:str]
    version: 3.13.1
