apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-cluster
spec:
  instances: 3
  enableSuperuserAccess: true
  postgresql:
    pg_hba:
      - host all postgres all scram-sha-256
  bootstrap:
    initdb:
      owner: postgres
  superuserSecret:
    name: cloudnative-pg-admin
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
      - name: cnpg-default-monitoring
        key: queries
  managed:
    roles:
      - name: authentik
        passwordSecret:
          name: authentik-db-secret
        login: true
      - name: immich
        passwordSecret:
          name: immich-db-secret
        login: true
      - name: n8n
        passwordSecret:
          name: n8n-db-secret
        login: true
      - name: nextcloud
        passwordSecret:
          name: nextcloud-db-secret
        login: true
      - name: mealie
        passwordSecret:
          name: mealie-db-secret
        login: true
      - name: paperless-ngx
        passwordSecret:
          name: paperless-ngx-db-secret
        login: true
      - name: semaphore
        passwordSecret:
          name: semaphore-db-secret
        login: true
