apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-cluster
spec:
  instances: 3
  enableSuperuserAccess: true
  certificates:
    serverCASecret: cluster-ca-secret
    serverTLSSecret: app-cluster-server-tls
    postgresql:
      pg_hba:
        - hostssl all postgres all cert
        - host all all all scram-sha-256
  bootstrap:
    initdb:
      owner: postgres
  superuserSecret:
    name: cloudnative-pg-admin
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
      - name: cnpg-default-monitoring
        key: queries
  managed:
    roles:
      - name: authentik
        passwordSecret:
          name: authentik-db-secret
        login: true
      - name: immich
        passwordSecret:
          name: immich-db-secret
        login: true
      - name: n8n
        passwordSecret:
          name: n8n-db-secret
        login: true
      - name: nextcloud
        passwordSecret:
          name: nextcloud-db-secret
        login: true
      - name: mealie
        passwordSecret:
          name: mealie-db-secret
        login: true
      - name: paperless-ngx
        passwordSecret:
          name: paperless-ngx-db-secret
        login: true
      - name: semaphore
        passwordSecret:
          name: semaphore-db-secret
        login: true
      - name: bytebase
        passwordSecret:
          name: bytebase-db-secret
        login: true
      - name: dbgate
        passwordSecret:
          name: dbgate-db-secret
        login: true
      - name: radarr
        passwordSecret:
          name: radarr-db-secret
        login: true
      - name: sonarr
        passwordSecret:
          name: sonarr-db-secret
        login: true
      - name: bazarr
        passwordSecret:
          name: bazarr-db-secret
        login: true
      - name: prowlarr
        passwordSecret:
          name: prowlarr-db-secret
        login: true
      - name: autobrr
        passwordSecret:
          name: autobrr-db-secret
        login: true
      - name: deduparr
        passwordSecret:
          name: deduparr-db-secret
        login: true
      - name: qui
        passwordSecret:
          name: qui-db-secret
        login: true
