# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres
spec:
  instances: 3
  storage:
    size: 20Gi
  managed:
    databases:
      - name: vaultwarden
        owner: vaultwarden
      - name: authentik
        owner: authentik
      - name: terraform_state
        owner: terraform
    roles:
      - name: vaultwarden
        passwordSecret:
          name: vaultwarden-db-secret
        login: true
      - name: authentik
        passwordSecret:
          name: authentik-db-secret
        login: true
      - name: terraform
        passwordSecret:
          name: terraform-db-secret
        login: true
