apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
resources:
  - ./operator.yaml
  - ./cluster.yaml
  - ./namespace.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./secret.yaml
