apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-admin
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2l0Sog1q8qU=,iv:fZzEmBwM/eeMV4u+SFnZdeb5oD44nuRJqaYurVY2m8c=,tag:Zw3JtsEQZ/5rwlBt0JQ9mA==,type:str]
    password: ENC[AES256_GCM,data:YyW1jY74YjTSfZwq4D41/Ps1w857cNJ+X6zmXFZA1uSI1A8yKCoVHX08ZT9VKh2PZbo=,iv:SLTweqmgmXMkhptKOCLLS5wRpZVTVzhQIVH6ASvkPik=,tag:l7GgVC1+qXa66S3a3IsP+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:YXOxnHFxcdJd,iv:Xi0yESljy49is4JhWzYMbe5KjrRhKYQIeN4cBAURtyc=,tag:71EMZe5xt+BnsKUq+sLdAg==,type:str]
    password: ENC[AES256_GCM,data:L9XPxr0IhZysxzSRlprmNBO5mzb25z3QCbyJ5mMuCirtPjEq,iv:lehjmn986aDXHK1cVsEQvHrk/YmD1zPQu1oZXYngzF8=,tag:4gXXNMu1zLLwyBxcJlNxdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:L0dvckjy,iv:k9r5SmYVNI136Qa6v59fBpMzIrnNHfk8bb5VRHX/ITk=,tag:YojLyQzIuepPwFt3QmMG+Q==,type:str]
    password: ENC[AES256_GCM,data:ADveNVACn+boR74NwSB5uxnFODhH0Ot2oH3EJy/IgV+ecHpikSt+mnaJ,iv:jduskE1MY5niONnAJSWnvT1gvQakjf0RlYB2b7tHFyM=,tag:p3vHAkI/cRBzuvwrkPmEfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:QHzl,iv:7ESvCnHxcEkiPF1QJ8bEyLnvi/wI68jyt/k48Lqlrtc=,tag:dVSJfdDTtIliiLdZMMkIMA==,type:str]
    password: ENC[AES256_GCM,data:aKWdZ/WZQtIqYz78pSX6of2ebIR678MA/j24SQ2nWGOW0h78tFyZtIXFGr61,iv:oV/kOhiZ9RCSo2dhHUJAZ2phFBSO0T0BjJqEqEFI/KM=,tag:/J2UwvckWZK1sK1Mv2vVtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/GG4Pn25JdYX,iv:jaTuscyHbAq3IBopvWEJINY8x8rEbrnq9mhsAZNcvfo=,tag:YEroxTKzhyUQ2ZHvcdKR/g==,type:str]
    password: ENC[AES256_GCM,data:gqJ9wWBqPGik74SSBRJBeGxrUaAyOz5EX1SV+m3RJO9sXV2jwJCR+ozr2GCO8OHC,iv:nFnXSwR8pbtMzVbpuLxYFfqJtz3UraY2iqKcbgpLRXU=,tag:AuYcIQ1D/Em76FSbnXXczg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mealie-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vaFlN80O,iv:BDnpIgPRcmRYppPJIxlKk/aqKCBWqivLPLvspn3vKjA=,tag:/GXeMCDADjO7Px2smi5Kpg==,type:str]
    password: ENC[AES256_GCM,data:QWo/B/ZsHkX06Rl/fB/JKGEmwLwE7ndzFO0UjOtHpRSwo+OCrPLF,iv:evBydmeNNz36bJDxqRbBn3BT0gIHTH+teYAPB6iuxrE=,tag:4ZGJC5U8oXEjSlNcJrroPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OhgeLUAz5K3bePnI/A==,iv:CXLQZtYfg0yAsgB+m5cmpn7K8K0yWBw+qXbzWwiCoWo=,tag:4aD8KeyT7qvsSdb1x+y9Xg==,type:str]
    password: ENC[AES256_GCM,data:gIP4+0NyfmWWzOnA8jqCVrMPHpw5oowk1ixXF10Tsg7kpIRGmdlBE71AA9wL1EUO3Q+3,iv:KyY1PvfOD5KsLeCTB8vx213OgG9y7gllVrjqSb6iTQo=,tag:CvJAAUtLyy/kBD1paYnemQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: semaphore-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:MKTBWFadVmGc,iv:ROMXF+nWM8wKF/9URDE68XC5IgCUFtM2qmpGj7B2gXE=,tag:Xkvr5ZgqPn7elXho4XVx0Q==,type:str]
    password: ENC[AES256_GCM,data:28PcGr/59E833noWZbGouSb1/TrKxnauUS6HIHK+PDlAuimbykkeM/tBT1ZP898=,iv:5ThyA1533MOlBnh7828BWB78oT+YhZkxcHSAwULNpS4=,tag:6J7WWaOyE+o0Obxvov5qgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-teleport
stringData:
    token: ENC[AES256_GCM,data:gbZcKFH7upWXv7gkvnxpvev+m9IK2NcWlK99JgA7q+NYYiCH/E+ZapSUIyGaztE=,iv:XDrAflU8yOPTlha5Psw5bIQRphMAEmbeOarP9BjqW9k=,tag:5/vW6cOit83ftybM0x4/SA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYStlZXRBQ294R2ZGSnV2
            ekg5TktUZlUrSTN3RndhaHFOWmc2ekVNZlZvCnJkQTkzbFk0U2E2NEtsdTlMWnBN
            eWZaSVY3dk1UYjV6WHA4TVZsY1Nic1kKLS0tIFdUL2VKNHNwK2FLOFpVTURYNUpm
            M1VxaldBYXp2eWVQWXRoQ2xlZVgzSVUK9LKVwSeHDXG2le3hsQ9KeMlYtqgNTDMr
            Q4ByAFSTBq8p7fUNMKM/frWnpFR/lp5eqnTig96L7P5QHBFs0vPEsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:01:17Z"
    mac: ENC[AES256_GCM,data:4sNORIqXdzluWIcXzL/M2lPERKXjq2oX0ruoQ86T+n7E93THtPn+OSeosF9ZhdLHnjwm3zoBXTQ3qdGRXxsdMcoWO7QgfAdnYYgN3pZzefYqzTAgxkhl2nduUpZj+l6Ws58v1pHt07GCrTICH00BmX2ck2CU1WexMn7qN5SKxGE=,iv:NQ0Faxk87ddxs2gCT0EypWMrY4xG6cZxsqZFIF+m8Zo=,tag:rmc3CKJPkMZBYoXl/iq47Q==,type:str]
    version: 3.13.1
