apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-admin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:H8eDkYESwBw=,iv:IEzjFgHTlcTuoAIdsSmDetiHmcJuL6aHTmqNWKUbQjA=,tag:toa9nvEg49TukGAaXVEbpw==,type:str]
    password: ENC[AES256_GCM,data:G/2kQGr/g+YIQ5BcfG/bd1WaBzZhMZOiJ4+tP3T1A1jy1avqznlYBL46jRNLqZ/QiTw=,iv:t7J23Y9UoTEdKcCut99mFqz5nvHXO7t8Ds7WI1GMDZw=,tag:YWxW90dX9mnNT6JH5e0upw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb1d5cnU1Zjlzbml2aGp2
            ajV4cXB2M3JqeVF5OHFZTk5qejZ4QmtVZmw0CjMwdlVlWUN4Y2prS0hzMkhOck9s
            OWszeW9IMzdMbk10STh4dTVoQndWTkUKLS0tIE1EMWZPZTNzcytjckswVVNxVnZk
            dC9DQUpMb2QzSllJMnlGVkxsRHo0S0kKEO/sFl8Y1LyWhrLYJMBEMs7eGRvlnVqj
            3nx7WjVmL4bW2be2mWvT78eV/z6Y+ZyB5dEUWsdyunD7Ko8PG3f1Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T00:00:58Z"
    mac: ENC[AES256_GCM,data:r5GAK0U2daTO2Kb5va/0ZVIPG877XPuIw0jS6qAJaI7Y0OZAefWJpPHDkzzdqMvtfuNV1SaCgBKwPP+Auv+byylSy9KifDH23k+jp6BoZ4K+J38XchTmoKvPB5qVOcUEBYB85Ed6Gyhww63VRoNmuWZ/n+D5n0YpxBfKXRBKFzs=,iv:ZUKDkuNATkJ8IW/Zm1Tc98+5vFjDdGjv6VhrRaiZlng=,tag:FQif3MGSFMa0qp+akxdKNw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg
stringData:
    username: ENC[AES256_GCM,data:MEQoS1rmsos=,iv:CfEmO8AoRsrMG99GPlk7Rg857BSR/6e5ELOWZKR5WSY=,tag:1EWnsIX5pgauN/2UBErqeg==,type:str]
    password: ENC[AES256_GCM,data:f1yQqZTVotPubY1GqnLZNB1Fl1QztlsWBd/4v2sLZvOK76b5Twx4lwOSle4pAZzPOvQ=,iv:dOtKKsTUWyb4sU5HsOcaMjJ8zFrrhGeHuqY8Gpik84o=,tag:58URilXJ3k/Gg4KHMRTBSw==,type:str]
    authentik_db_user: ENC[AES256_GCM,data:fuKJlTSPTClc,iv:0odj28q7lR4B8IPPYAyJJNvOdtd9UNVBP84m3A2IaWk=,tag:oQObRreuBeFUIaOQ+bYLPA==,type:str]
    authentik_db_password: ENC[AES256_GCM,data:Hq1DcxVN1IT0qJfkxHoehIfglHxQBPVx17tliazQfYUjd22f,iv:NVSua7/kWtJJD/w2SQ5aJQmq2hnuHUSCBEoV4O3ZAf0=,tag:MRTBbthuis3UPOQ3dQcnQQ==,type:str]
    immich_db_user: ENC[AES256_GCM,data:m53WvPoy,iv:g0dgoYsc1fAoa0A47vrBqxtOicSLN2T3N3O6VK+hrDU=,tag:LdnhIgG8G/z70kmMrXyv5A==,type:str]
    immich_db_secret: ENC[AES256_GCM,data:tQILKZ+PHYeb9xFaxGOWkEOMiSxeL7IJQsDEAENjxsctpEfpLfJ8L3m0,iv:4TtqGGyjzmA5kSLKJ4HtP7TsA9IjHLCj7Lu9vgYKVOg=,tag:o9ioepwqqAxd+k6+6M/tVA==,type:str]
    n8n_db_user: ENC[AES256_GCM,data:bDbx,iv:EBHXaHnf+nTZ4QoDm/HdQyAk0IOsLwowh2xaHjta6D8=,tag:czhzNq17ocEVb+jEg3P+WQ==,type:str]
    n8n_db_secret: ENC[AES256_GCM,data:Fgfr8Woa70HI2z0lJrN/OHRMwSXnq47mUtFf2qrCPeQs6TvRLQaA/LgbULAU,iv:oakKl0/VhLcXyPDycnwt/RoXnBGKnepHGamDePkNO+U=,tag:Y8Lpuaf9Bl+f2/mebk61Rg==,type:str]
    nextcloud_db_user: ENC[AES256_GCM,data:uFgdjJa/c3Kf,iv:qukRTK6w3hCWsypMSQpNUR0Z7s2nAQw5ZsmTpSmsdbs=,tag:a0zLCbRqpI943lPjWDfa4w==,type:str]
    nextcloud_db_secret: ENC[AES256_GCM,data:4P6cU20+FL1N8bIz43edJzLgiVzhclFZvZxeEBpQG6NOwVQ59ljk2E1HL7ZvhBBJ,iv:5vSwQTrgQpAXwSd8sLuATXs62Ohg0KIBJPXPMNMz8rw=,tag:38MwQbpXQDfR4HL/Uv7mZA==,type:str]
    mealie_db_user: ENC[AES256_GCM,data:FhWw8v7F,iv:d8eS2jVi6dYSmga7uRebBZjKBGef2Sm8g3ACL+GtyC4=,tag:LSLwhl5QiYrhzPu9tKQBAA==,type:str]
    mealie_db_secret: ENC[AES256_GCM,data:w/pLbl61PZcxlLB2UgnWIUrfd7To0+ns51sDAAoivRLllK0zyq+M,iv:h3//+p6JJ8Dyf/Rwis8RPStA544LDC63suTraDVlKRw=,tag:IrldotUCiAUz26PWfy+gmA==,type:str]
    paperless_ngx_db_user: ENC[AES256_GCM,data:FlqRToSBe/nyZdDDSw==,iv:qWu8cfdgJgWh6EP+bJkcKqSvpgtBMzFqv6EEQfNkZ+Q=,tag:wSRe/lAuAIrqp2bKiGhdnA==,type:str]
    paperless_ngx_db_secret: ENC[AES256_GCM,data:sMbTyA6AkqNSOgrj8TEC3aZHJvOxNQlAsZ9vUJWaPx14yS92vaonOaVIsG36ovdYEHCC,iv:tmS3ugjd3ZpIqo90g4gjWwlddyS5R7GkU3P+kVd1pbA=,tag:z8273CyPgMHovbKbchgdIg==,type:str]
    semaphore_db_user: ENC[AES256_GCM,data:1F/L9AhVXqVQ,iv:VW5lheNFS9Y5eau/OhX1tCEY1q1xyStPF9MyeDMdXQQ=,tag:VaOC4l0SwBcpsIbm7XcgzQ==,type:str]
    semaphore_db_secret: ENC[AES256_GCM,data:07mC1oBvayCI229xP/dlpySTlm3fZ3wErJtDngjylvVtwal/6j2q/PG6qc8oj4g=,iv:37XbwUAvxWRgknSz/Q0UcfdUU8sZxD35CTk8JtYcX7I=,tag:KtalM71nMG66+oqvTourGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb1d5cnU1Zjlzbml2aGp2
            ajV4cXB2M3JqeVF5OHFZTk5qejZ4QmtVZmw0CjMwdlVlWUN4Y2prS0hzMkhOck9s
            OWszeW9IMzdMbk10STh4dTVoQndWTkUKLS0tIE1EMWZPZTNzcytjckswVVNxVnZk
            dC9DQUpMb2QzSllJMnlGVkxsRHo0S0kKEO/sFl8Y1LyWhrLYJMBEMs7eGRvlnVqj
            3nx7WjVmL4bW2be2mWvT78eV/z6Y+ZyB5dEUWsdyunD7Ko8PG3f1Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T00:00:58Z"
    mac: ENC[AES256_GCM,data:r5GAK0U2daTO2Kb5va/0ZVIPG877XPuIw0jS6qAJaI7Y0OZAefWJpPHDkzzdqMvtfuNV1SaCgBKwPP+Auv+byylSy9KifDH23k+jp6BoZ4K+J38XchTmoKvPB5qVOcUEBYB85Ed6Gyhww63VRoNmuWZ/n+D5n0YpxBfKXRBKFzs=,iv:ZUKDkuNATkJ8IW/Zm1Tc98+5vFjDdGjv6VhrRaiZlng=,tag:FQif3MGSFMa0qp+akxdKNw==,type:str]
    version: 3.13.1
