apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-admin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:z6Ylf5A9wTQ=,iv:H7tymhYO2mkVs7k0FdH5dJKTNVI4uvzqobPTMtvaXXQ=,tag:mvvb0cQANdvHvJlawQahrA==,type:str]
    password: ENC[AES256_GCM,data:8PNb1hdWCzJ9nYIOWRN48Kr/W1iixzJ7H89f158yTWhc/yq5wqtx/Llso1R7lx/b2qY=,iv:JeOAkGZXyP+krmSROPiXQHi/MPoio9Sgf60pzODO35g=,tag:kR4Uz8zuwB0A+3nr+F8zhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ3BaR1BFSFBpeWVHMWtr
            VjF4VC9wWkx5Z0Q1c3IrVzNROU1QcTkvZlRFCnJ2VmE2RHJvSWxIbzdEanVlYXVY
            MVVkVzVEZlhJYkJOQlhZZzVvdGFtQjQKLS0tIFN1YnVudGZXNloydUtKaldwU3Bx
            K28vVGtyN3hFVmlNeHArSkF6NHp6ck0KJQ8CHMhNbMRoyOiLyA9BKgM9U+Odx6N2
            e9Fl5LYV2h6UtXMBpd2RetJQSmnjcmSmcZcAOIrwd/J9NkJYCMsF7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-13T21:18:11Z"
    mac: ENC[AES256_GCM,data:X2jv3puppRV7hCTCTU8Omx7oDaNJaF7z3jKUQpW7nxRGeCAFtJrBwJitQJDHxEdq5yijlgZQIOPFVeStSS67HkPzL6DZ5G+LKU0Xe3z0aT8b41zTLx9+WSLFXd9zfmTQTT/bpn6/yuFuIbO4i5awmXSzcLDV/oC8DKSzQCAhiV8=,iv:m0qqyzMnBjk38onrLdStpk7QnAg5K4VAUfRJvr9TJV0=,tag:bDSGpVhrs0vF8HQ3DiXSQg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg
stringData:
    username: ENC[AES256_GCM,data:7rjvi1otDPw=,iv:mrfugTVKIReZlRJb3GeCB4NRi+Bt+abWdmNqix4RHxs=,tag:JDUEjHOOfOTbYAX8dQxD1A==,type:str]
    password: ENC[AES256_GCM,data:Bw8fgDCoUpYRIYk7r2UNORD1hWOyu7NiJg0QGC0p2JiPNrouVXczQeztOorCERNh4ck=,iv:Pd4knEeUM0Ysp9UST/W+N61+A92jeeHEbXZnqksMECY=,tag:/UrtSwHIl7wvqYWN3X/20w==,type:str]
    authentik_db_user: ENC[AES256_GCM,data:n/va92s9yD8M,iv:SY3dYRLn4vQ2P16F2GAiSCqPCl+yk6Lhn0XFLUZNwQc=,tag:34j+0A/F0UNrSY+A+QVceA==,type:str]
    authentik_db_password: ENC[AES256_GCM,data:1GB5hOqta6esPcDUotXz1KIlqWrC0Zlcxf7jjIKiP3bW8tmT,iv:B9tmzLg+oGu7Tit72lHKpPK/kttHdxyTF3qqMgOg/uU=,tag:a+sW7C0dNNmZoEN/C/14ZA==,type:str]
    immich_db_secret: ENC[AES256_GCM,data:TjbPQaskHCo80UsO5Pq0+Kk3z8MJ9ikDevVvCuymn3CLKErmsVLEr1iP,iv:WI97Zehewj0kRSWCMck67ZTfAL7RlBUGW5wbVmIx3fA=,tag:Blah9zGbVFV5KFeLlckafQ==,type:str]
    n8n_db_secret: ENC[AES256_GCM,data:c2nztW8Touo0sfwf4hz1FPQpSV+br8qhpMsWVWivWZ8ssAInpWL6Dom0tsV/,iv:bXIecMk4B2u9geD1O8ID0uYsWuUMeoF5jQAX8UtNQpM=,tag:NUtVSSX5citGX1w33EfE/g==,type:str]
    nextcloud_db_secret: ENC[AES256_GCM,data:gBRFrdxCuUcQLksT9xQiQ3Uvr7qZiX+GEBwucEj3qQeWqE9o8qXZ3cHdH0YOnXQL,iv:r/4NZFh/SQo5SfN2/EWLdsOrSOrGY+IUqa3ZDKUgwqY=,tag:m0UFSe5XVZiLLlohXDv+2w==,type:str]
    mealie_db_secret: ENC[AES256_GCM,data:w8xs/e02BWH1hH2rvK/376WtLSKI5AE7jt8nprghr/Tx2MZnHBog,iv:mHhAzyXbeEjAiZN0Ce8RvfG9cAm8sWf+Bx2IyPQQ0Dg=,tag:4EBnGf+Zy9kxW2TVga5e9w==,type:str]
    paperless_ngx_db_secret: ENC[AES256_GCM,data:q4p3oM0v85dK7lyWy90946PX5GJ226ykzleNYeRYwTRCfCWC3ZSKJY3SjidjGZQbpSu9,iv:EX3KW5/i4qIFIA1ZlYFinMaVOZlk3iDXHQiAIh2ZfyI=,tag:1ql86UqRTUDI6bkK+1B47g==,type:str]
    semaphore_db_secret: ENC[AES256_GCM,data:LeM9TKyhma0kR2CjUE4eKvj1Qt26+zfxZTriLESGW0jDGMHvTFscN6h0HFAw8Ao=,iv:4GDZgv8NW4MiJhXdGOiDU8lOAiqw+Skd4qkOv73CBOs=,tag:AB1wlWTHF9H4tC8TNVdRcA==,type:str]
    terraform_db_secret: ENC[AES256_GCM,data:d+jHo0SkPjIvkj0maWaBlZSFisJYcdttGmHxTLw7UQmYmFNdIfM9bMaEiEot,iv:aE6UQFboijW45e+KJeM2iblSQEHfrPQtNAG1WlYSZBQ=,tag:cuYMt6BXN4YgHxBY9/v1VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ3BaR1BFSFBpeWVHMWtr
            VjF4VC9wWkx5Z0Q1c3IrVzNROU1QcTkvZlRFCnJ2VmE2RHJvSWxIbzdEanVlYXVY
            MVVkVzVEZlhJYkJOQlhZZzVvdGFtQjQKLS0tIFN1YnVudGZXNloydUtKaldwU3Bx
            K28vVGtyN3hFVmlNeHArSkF6NHp6ck0KJQ8CHMhNbMRoyOiLyA9BKgM9U+Odx6N2
            e9Fl5LYV2h6UtXMBpd2RetJQSmnjcmSmcZcAOIrwd/J9NkJYCMsF7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-13T21:18:11Z"
    mac: ENC[AES256_GCM,data:X2jv3puppRV7hCTCTU8Omx7oDaNJaF7z3jKUQpW7nxRGeCAFtJrBwJitQJDHxEdq5yijlgZQIOPFVeStSS67HkPzL6DZ5G+LKU0Xe3z0aT8b41zTLx9+WSLFXd9zfmTQTT/bpn6/yuFuIbO4i5awmXSzcLDV/oC8DKSzQCAhiV8=,iv:m0qqyzMnBjk38onrLdStpk7QnAg5K4VAUfRJvr9TJV0=,tag:bDSGpVhrs0vF8HQ3DiXSQg==,type:str]
    version: 3.13.1
