apiVersion: v1
kind: Secret
metadata:
    name: sonarr-config
    namespace: media
stringData:
    config.xml: ENC[AES256_GCM,data:mZ8+H0NmESdBra9KPkOdid5JrQcfGAfhWQKZhTaVHObCGW3SPIGWrXs39WoWzzyTLGTeyLSDqItMMsYE37Z+hYKKWpMC+x8UpbdpX5paTe1/6vzeMFVu0mXEz84FEm6a6l9DoUvlpH6Bs41kTy/3HnRlv9hW57lY9zItp0HFaAoEiLjMx+tTx5env24UX8XYigWGi7GMvKNpoc58TEUbjEuvhf8LIlt4ub1mOhOwfCVbppkppvwUwGGp+VmSdE7DmYu+XfPNoBK+bYHEoFYigUkhzIp9IXHXQSjFjYUowY2hi16kMt7YD5WXpEHp/b93jtSH70+64DYQOCsUoUDoo1o9JAs9I3erpcBHTPk6SPrdK9/5J8zdzz0MrHieLXwiPiAlQERkXxeCeKdKN/7tYJyKGuo3uf3E7eL+oTsYIVFkQ4o=,iv:P1G5TXF/dvL21qW8c3LqUrjZ7XFkqd162KdJQKo8WkY=,tag:DJtXc2y0t1WpucipFw0uBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaWZhOWp1ODd1eW1IUHJW
            TUVVa0RuT1UwOHVScWlUOGdaRGZrV2VhWXhjCnlUd0dyY0FRVFViYkRmemF4N0Qx
            OCtrazVhRHBUU3JHZk5ZU0M4OHovQjQKLS0tIGYvaG1VSWhldmFtM2pLSXFNTUw3
            cUNwL1lRQW5tdFgxOXd4ZWkwaUtuK0kK6ZE+W+6/kqJmCZr2tHJeLzh8ueRt9oGC
            7xdn+4odUS5gvlPDd9uTDzDLZBfkvDtGo2Odjd8ZBOYUaxDurWHTyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T04:46:52Z"
    mac: ENC[AES256_GCM,data:21r3zGB17Q4NZ+clP4tg0MXHv5DwjbPELI+jtVabnzMqyFsvZNAPr59dErb0g5cvu7XTYQDU4mH37+gyWcbNYQ6RIUxAhSnMrrrm0kEvjAeMzmPN2eTCwsxkXoUoHu4qNxgpgSDTX79I/1P1i+jJ2EPhFlU6n1KX/tbgFL/r+TA=,iv:wHlwgE5Hs6wBZJV68XmTuCzaV1JF4S0NZnc+0t0JbHA=,tag:abVroMVBLaRIpoGchWND6Q==,type:str]
    version: 3.13.1
