apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:ugd420v/vcMFOU7MbGfltdSOC2BFZaCmUTpM7icffEo=,iv:FAypC3KcIDrdye2CWY8XqeRilhBpPsWgHTvwTWuKUD0=,tag:AIJTDRzwE8qMlXaTWkYEjg==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:j4dDHf76budi9LP6WxiY9og2N+j1oP9UDTRQw5YS+l3UHF2XAJ6U/M/agtt2GnI=,iv:8edY/sdeyxu8XOZjoD7GAXrFN0Rb6VPk7ZUBVb4+pOU=,tag:pFliZ0CccA6d6mt7PQ1DwQ==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:yzFcu0Xu,iv:Q3oZ2hpYtqW0QyNmlVFh268SwMd9L9MfLpGTHRlHKSc=,tag:msqPuEO9SzTAlr/vLNVmpA==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:85L10k5Xc1gftqEmen3/eZVsvp894H5mDov/hPIMyvlf0pu8T5ufiWg=,iv:thzElmPbf4ADjU3T8r83zRvKiLvr/3VgJJ9nfRP92qY=,tag:WpUU0UfIIlQT5fJBf6MpIw==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:B1ocVNBf,iv:trBALjP8BfCov5XmGhUg8BBs0qtW5dB02l5KRyqk79s=,tag:cHGylYCjIyU/G40suDX6ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYU82ZTkyZjl5a0QrdmJu
            dStISzEwdDdHQjdEbjNXd3EyT1AxeFhSQUI0CitqUEFpSEZ4VnJVdFlFNGl6TmMy
            RXdCWmZEL0RlbFpJT1l3U0I1YUFha2sKLS0tIEUzMmljVCtaQjV1dkdjeHFMYVYr
            dEJITTFMK3FyWS9vRVBpMDBkK3pCSGsKbfRggvjH4oQAvCFY6xEYXo/R8JHjF7Mh
            1/0XTsjRCmaovF30cSOAWuQ065N+gGnX4EvDjLq2+e6cvNJotniW5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T15:14:58Z"
    mac: ENC[AES256_GCM,data:xUUZ+n1jJdZsonjTSyA//AmF84VXu/799+ZWDU/0CWUf9o2mApRnaOKqI/u4LcSyvwoQI94bQ3eH9A0m4ny5uQMTRIqv2z1jvAIngshzpmuZ1CO0+undCGF+KKubw+HGb3Y0/mzwmNYPiPGVb1OIph7rjPb63UCA4Om1nb8BMao=,iv:ANjyVJxfElCeDvTxLe9l/Q5vgSFbWRW4FIROwlyBNu0=,tag:ama0TVQDLa4gvSWHlL4htA==,type:str]
    version: 3.13.1
