apiVersion: v1
kind: Secret
metadata:
    name: sonarr-config
    namespace: media
stringData:
    config.xml: ENC[AES256_GCM,data:ozWSkOXyQV0d2c9jxcEX83BrmJzcSk8B58J+4UgyhGWEz5bu5JXuZMqB7L5YG+TVWck3SOZCppz/KEAaVsdrYv6T0WvT+13E5vK6rmUJgWBx0GqUL4OonB7QLMBZoh89xeAe57jiLqFLf1KuSNqCQkoQkzDzFeaGh2JOaMQugCleyi/ZmIL4OPtd8pMYb3JZzRyhYkPQpGzVhgXgqTZ153+/8cFA1KOv2aHJLatoz3QD4Cx3oy7DuZ6PaowAsW2PvkPzcOv0f1yl29OOfkt/VWZB86Mp5MaXM4hJAgRdyF82WkymHo0cGedY6JFPGOb+UuQZ+qXK0PVDUXgwxzoR3sqEnzEJrtvr8G4p1MyUavWOhcVWXS9B094cq3DtVOwWSkY/kALN+oQ2v6tFE+lTqxLeMNpaKMQIxTJ0YbyDTEK1R9n7mzY=,iv:7B5PXy8R87QQR+QDt9T3V0bsZHUC9AXgzkEQxIW4YOI=,tag:iyxvZyUSVjPX52f+DJzs+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZjNNR0tSNG5BOTQvQlhz
            am96Q1F5TjNua05Ba0p0VjFhN0lQWmRiZDNNClJsZ3FBMkVuK21CY0JJL2x2dUZV
            elNVT1Y0eGFxaTk5RDhrNEJOemVWVzAKLS0tIGRPZXduellzblZqUFU0VS9sM2dG
            R25qWDlvK2dpRkdoMzBHVlBpTmtMNXcKY47JBbs7MKFtm5SMgpNArBnFoMJ98WBu
            /CfbsiG6gE3Gr8FgYlpYem0tL4lOFs+VCopzFCuhFBcYWTutGbAF4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T05:17:41Z"
    mac: ENC[AES256_GCM,data:9gy8SXsrSVk16/8QJVtWTYDsoq7wynx2/zDxSQzkPDM+AR6Z+U2HhI+CQV1xN03qlyZYyJ77GmHu7J3rqAKsAcrH/rd1nQE/KSA1pzY+RdLG590vX57xkOsexQLFxvV/TF7cMJtXNFzb6HLwDCa3ZtGADjSBgzDcejdoTx6B5zU=,iv:dHsA3oQLjxWr00GPP7nLpQKvLTRJxk0hryahOu8PRG8=,tag:EilxCpCSLB0/ZZdNKcUjuw==,type:str]
    version: 3.13.1
