apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustfs
  namespace: rustfs
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`rustfs.theblacklodge.dev`)
      kind: Rule
      services:
        - name: rustfs-svc
          port: 9001
