apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
stringData:
    access_key: ENC[AES256_GCM,data:7ybWV6JkCQvXZIBynrismihZIJfNykB4T4LSKMMzLN4eWm0vp72oGpHHWqCB,iv:Fa0KjUpyYVJnuxG/1SGtUOjL2yEjTRAPY1pJple5/jk=,tag:RHDgCYLWsDZW6OAob23Dug==,type:str]
    secret_key: ENC[AES256_GCM,data:tFYWaZj9aGqQMJiWie51feCfdps8hcCPIBbPENjnIGfRdIuqTZUrqVQXzkY61w==,iv:AvWYhuhXwkEbkYfC6VXxkykz8lfbxvjCjlcys0TQ6os=,tag:ylbzEseS0wl5EckMa5E+Cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMkVMaGc3RHRlVjhsRG9l
            RjFLL2FWSUZNN2orUVpFRUJUdi9VdlJGckFzCmU0QVl6YXZoNXNLS3RjMzJJL2ww
            d01sOHNKZDc0UDJMNUI1dk56bzZEK1kKLS0tICtoUkRsY3N5Rk1mQmtWcElnOTNs
            NEpWNTYrVVVpK2lPRG5CSmN1aUlod1EKKHgMC+OyrMYPjjZbh7THEM7dHc+ZgDSD
            yX3HpXfwiGAb3f9l6/g54oQMDaSbMPrOZVKI/ZtA8cBS/RpvpF+LGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-18T04:12:54Z"
    mac: ENC[AES256_GCM,data:4etnOLTWQGOZxk1Q8qvIZ49WapfUk6KeLrYG/4bqW4uL3GvkFL7F251AY36c1mGWg+pRz73wP1DY/qja2MXelXVFvzi0zxKnqktH3QZbyAng3Xj+3/HCUqzGAQX+LyF+T1vqurZbj3yG3x33mKIa/WrdRJ4YRsBssuBw5Pbnjd0=,iv:GvjEiYlOMHbGaHdMXol9tmGo2lDKgkYu4EnCVaxK+g0=,tag:zQuN86XJujIlnnsq9+4ADg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rustfs-client-info
stringData:
    client-info.yaml: ENC[AES256_GCM,data:ZzJ8KMY1GAcVoqGlxV/klv5SI76dA9gXyTJpbiZf6fbPWyJ41x3WBTnJNXYz5CfZVH/igZpMcxR/hdp4+yz4sVBuFF96EggcmnzLcbsE+uRoc3dPxL/lEIPRSVTO3RpcFb8h9rEseKAAhndpdgF2Fv35yzW71hrmFSxpNj958xgTDlwkU/LgW7Z0xFIzNp1Pog==,iv:UR0TfLLnPb13nY82/f2Hyb6H6AIYsBRNnrIooGKKJiA=,tag:sEEDBwowntnUEy0Iw8LefQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMkVMaGc3RHRlVjhsRG9l
            RjFLL2FWSUZNN2orUVpFRUJUdi9VdlJGckFzCmU0QVl6YXZoNXNLS3RjMzJJL2ww
            d01sOHNKZDc0UDJMNUI1dk56bzZEK1kKLS0tICtoUkRsY3N5Rk1mQmtWcElnOTNs
            NEpWNTYrVVVpK2lPRG5CSmN1aUlod1EKKHgMC+OyrMYPjjZbh7THEM7dHc+ZgDSD
            yX3HpXfwiGAb3f9l6/g54oQMDaSbMPrOZVKI/ZtA8cBS/RpvpF+LGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-18T04:12:54Z"
    mac: ENC[AES256_GCM,data:4etnOLTWQGOZxk1Q8qvIZ49WapfUk6KeLrYG/4bqW4uL3GvkFL7F251AY36c1mGWg+pRz73wP1DY/qja2MXelXVFvzi0zxKnqktH3QZbyAng3Xj+3/HCUqzGAQX+LyF+T1vqurZbj3yG3x33mKIa/WrdRJ4YRsBssuBw5Pbnjd0=,iv:GvjEiYlOMHbGaHdMXol9tmGo2lDKgkYu4EnCVaxK+g0=,tag:zQuN86XJujIlnnsq9+4ADg==,type:str]
    version: 3.13.1
