apiVersion: v1
kind: Secret
metadata:
    name: rustfs-client-info
stringData:
    client-info.yaml: ENC[AES256_GCM,data:yCXX8nSzzlSmZL7w8VO024FemKYuuxxmlORRE/l5tnqHEjVmOetiAGkGHaK9txe1BPdzohMw2/nnqNE9pr7DZcpbRG0p27ZG6F9vxehaBZlSKBGFtGr1wPlo7wv9xCIrJODhTk2dzHDP1mr+zNV91hQBWBwsfml5O6IK0qcZjUW+sjwcMq6W88cTMrpwvZKnuA==,iv:qoOijfuwuDkANyAPsb0IpLJ2PbwCnJwMOS6LPPykv24=,tag:iZ3tga+Ipc/vQQubnumEZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L0NUYWpwNkJOQkZMMzJT
            V1hoMkM5dC9iT1pKSHN1WlNOT1hPb2NHNUZZCkZETk1zdlBZdnUvMXl2a0llSGl6
            eU5TTFo0VlRtQ01BWm92YVhacHZtMDQKLS0tIHdHK2hia3UyM1FuRnlNMFFUc1Fj
            MEZ2S1orMWdZdVdJZXBtNVJaYnpVS0kKgZEc0ArhuvhyfUOxtfr546/MEjDfFXJ/
            PA37braWMQxzOdZXRR9XHL7rGeHSRJPszz9/aewHsAVz3Bm1o8cK8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-18T03:13:42Z"
    mac: ENC[AES256_GCM,data:epVkty1YF8mN7WWCqaRfmlWH7Py9tDofmKp/75+jbhcrwW5VNU7xZqqnv6Bz5MApv/k0U00TtWVA4BIzHK4LnGuRa8QzoXcnS0tLn+JGzHXxshh2mfSy3Umipf5V3zuxuT/oAbVbNBsKLrdN1U6Ctb7FxZLgHiLuQ//5E0MKgGk=,iv:6jMyfKJbVnf7oA/IYM2uSFbTuN3Wyj5KpGkpZPq+zQk=,tag:RHEm6mE2MWSX868bLJYD1Q==,type:str]
    version: 3.13.1
