apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
stringData:
    access_key: ENC[AES256_GCM,data:Q7wZa9qpkVcgNcAXLkXlNm7GKu/aOXXdqvc2KNIiZhWqn1rksmUVFAuqPAvg,iv:WS8S3yeC2Z7EzBt4meWnfcYzAyjEP54PlMUHlC9fH1Q=,tag:wusOG3ivB6MFAYa6IqOaYA==,type:str]
    secret_key: ENC[AES256_GCM,data:PhVhmm7PvavizcSBgnujUg0OV2X/2028uPhIZRa0Rq6Xz2sUuO/y3JnaNqOhjg==,iv:i8TvOGpHMcTOCBn7HkKwUcHEIR/bYAUIAYwLxSHuE2w=,tag:NW36YDdZXmBRmeEfae3nmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SXhlalgvVVVlV2E0bHFw
            ZG44WVovNDgyVGczb0x0YldpQitaYVVMcURBClVsNitQS1UvSVpNb2p2SDdTdFhj
            aHN4L09KdDQvUjVYVVJvclZvZGdmUXcKLS0tIFBmSEhQWHZ5Q0FHMGZ6bUpnS0Jy
            aVE0L1h0bnNURVFhOXZzNHV2Q3BMWWcKoUaqwPgqeBvhzK7bise9JOwOmyHKVHCZ
            JSvTvvfGbf8wJXfnI2TdeqiFHcG8jJ0n02o+QD/lr5+GekZrBVE4cQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-18T05:52:45Z"
    mac: ENC[AES256_GCM,data:eTobFrjgHGuK9EjuTLfqej40i5tQzbvgI7jMFGpjYFMKifFIjTFYecharLpdadu/T4AQPwV8AdONuAMqRnirJ+5bQxwujRbhTfu6ihM8hQkOEjYOF+oPrUy8a2txQE1++/JFX362DVwl5IisNkLL/oUy3KKSmsGkWwsMMGR26WI=,iv:yzSl8QqXnQG5HYw0XaeLhx6S1ZFWSg3un6Zw2VKburA=,tag:lCQ+PfzsmRWQ9bhfHB489g==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rustfs-client-info
stringData:
    client-info.yaml: ENC[AES256_GCM,data:yWyPZli5WDqbNInjuPz0c8fYyMoBH7hemmP22or6NE63aZbws0fQAtJ3cm9qEzFI+dznLJJjAwarw7/beiOoMOBfl5hpO9h/+P5KywZhpaO9jYSu6qBigtEZzFdQnb55gej/nzuiudfso83jDDnc2WXmkcYhuXStTTFXJ6dJxRVoXqeV1P36JhFU6aRJdjN4NQ==,iv:ApKJYmGwVQzYK/w+RmIMTILf9GK6kA7fnpY5+ll+NhE=,tag:gCcSYorpd9rW3NG+e6/TBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SXhlalgvVVVlV2E0bHFw
            ZG44WVovNDgyVGczb0x0YldpQitaYVVMcURBClVsNitQS1UvSVpNb2p2SDdTdFhj
            aHN4L09KdDQvUjVYVVJvclZvZGdmUXcKLS0tIFBmSEhQWHZ5Q0FHMGZ6bUpnS0Jy
            aVE0L1h0bnNURVFhOXZzNHV2Q3BMWWcKoUaqwPgqeBvhzK7bise9JOwOmyHKVHCZ
            JSvTvvfGbf8wJXfnI2TdeqiFHcG8jJ0n02o+QD/lr5+GekZrBVE4cQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-18T05:52:45Z"
    mac: ENC[AES256_GCM,data:eTobFrjgHGuK9EjuTLfqej40i5tQzbvgI7jMFGpjYFMKifFIjTFYecharLpdadu/T4AQPwV8AdONuAMqRnirJ+5bQxwujRbhTfu6ihM8hQkOEjYOF+oPrUy8a2txQE1++/JFX362DVwl5IisNkLL/oUy3KKSmsGkWwsMMGR26WI=,iv:yzSl8QqXnQG5HYw0XaeLhx6S1ZFWSg3un6Zw2VKburA=,tag:lCQ+PfzsmRWQ9bhfHB489g==,type:str]
    version: 3.13.1
