apiVersion: v1
kind: Secret
metadata:
    name: tautulli-secret
    namespace: media
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:k4jhVDeXcw4WMprcC9O+flf0ZohXrkDJsRrwlGoU6fw=,iv:0BCjweZO8O+26PaHt2Tlgh7HjVjCSDsT8b1pme8TcRE=,tag:4qVAuSusY458q49fZezpnA==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:HOV1CHK/xXbnp9XrzygbLdockUh5UmW9AeWO44tUoZUV6GPbyxXVVg/aKglRB8I=,iv:0UQsmLIklWN3ypNljrHQFRnayQC4XfzhNnsuwmrNIC0=,tag:3cjfjYf+FbggyNhrYVI+Pw==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:k/zDOAIP/5w=,iv:QfzEHYcWSADv4bQDgfd0UOGVLacMIXSkvoZsXQmybHg=,tag:InGPTjLHpOl96+qiP4OA9g==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:9+rZNMkGoO+sX1lToaKFZRusNLyLPqtdkugSdbuiP20ZWq7EG57xZYPx5Cs=,iv:gZ/lLlZzLBbXw8pSyeaPMOlnWu8eUioPLG/Oga034vM=,tag:zkzUAWh2TQrVq+gvX0rhqQ==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:405uRREpDvI=,iv:DmKV9wUwsmDrQG1VZCx8KF11FKzyJujWLhxhljlhFyg=,tag:5de8dJO9bphvTzOKD2KQ6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWHRFZ3g1VDJSaE5MYnNw
            aVFXbzQwT3N4VXpYUTNlQnRka0UyM05OSW00ClpMT0J5Yk5zZDFSc2pVVllCY0VO
            WDNEcFl6Yjd4aW9mQWVHNkxhbmUreVEKLS0tIGhRa05VcGhMOTdxak05WDBoWmND
            djhyVzlHMExrdmJhcHIwQWNRcXlBTFEKHyiPjMBPTISiBmXbMR2QzpjbGgEMYQzQ
            +JxZCB916d8OoNNLgQhhGCwV2t2LK/mBV0tlMz6NmsTED/wNbYEZzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:23:59Z"
    mac: ENC[AES256_GCM,data:M6eGp1Wpudz2HY1+O8DonfU3azWXsq6x50NdE0G0EnI4LWDmvD+o+4VaYkrwPdoE54SXaEmkKa7vOuuNGdCOLabzO8yR85fdd76i5rppfH4HBUUn3HuOKDwGVS568lNIaUaM7Uce6WXNmc3aeDwe6+HOypYucDtMcpUdfNvMbAg=,iv:pgB6xewlKvntpwTJ2ZGozhnuAHZ7a6Cum4UeGw4lpJ0=,tag:+7u4JZdxdqTkSrVXlaporg==,type:str]
    version: 3.13.1
