all:
  children:
    servers:
      children:
        freeipa_servers:
          hosts:
            ipa:
              ansible_host: 192.168.50.20
            freeipa-server-01:
              ansible_host: 192.168.100.254
        kubernetes:
          hosts:
            k8s-cloud-01:
              ansible_host: 192.168.2.5
            k8s-server-01:
              ansible_host: 192.168.100.15
      hosts:
        tang:
          ansible_host: 192.168.100.5
    clients:
      hosts:
        primary_desktop:
          ansible_host: 192.168.1.235
          ansible_become_password: "{{ vault_become_password }}"