all:
  children:
    servers:
      children:
        kubernetes:
          hosts:
            k8s:
              ansible_host: 192.168.100.15
      hosts:
        tang:
          ansible_host: 192.168.100.5
        ipa:
          ansible_host: 192.168.50.20
    clients:
      hosts:
        primary_desktop:
          ansible_host: austin-desktop.theblacklodge.org