- name: Gather Docker containers
  community.docker.docker_host_info:
    containers: true
  register: docker_info

- name: Save container info locally
  delegate_to: localhost
  become: false
  ansible.builtin.copy:
    content: "{{ docker_info.containers | to_nice_json }}"
    dest: "{{ role_path }}/files/{{ inventory_hostname }}-containers.json"

- name: Gather container details (including mounts)
  community.docker.docker_container_info:
    name: "{{ item }}"
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
  register: container_inspect

- name: Save mount points (host paths / volumes)
  delegate_to: localhost
  become: false
  copy:
    content: >-
      {{
        container_inspect.results
        | map(attribute='container')
        | map(attribute='Mounts')
        | list
        | to_nice_json
      }}
    dest: "{{ role_path }}../../.ansible/files/{{ inventory_hostname }}-mounts.json"
