- name: Mount NAS shared drive
  ansible.builtin.import_tasks:
    file: mount_nas_shared_drive.yml

- name: Prepare docker files
  ansible.builtin.import_tasks:
    file: copy_srv.yml

- name: Discover docker containers
  ansible.builtin.import_tasks:
    file: docker_containers.yml
