- name: Create mount point
  ansible.builtin.file:
    path: /mnt/shared
    state: directory
    # mode: "0755"

- name: Mount NFS share
  ansible.posix.mount:
    path: /mnt/shared
    src: "192.168.1.131:/volume1/shared"
    fstype: nfs4
    opts: rw,sync,hard,noatime,_netdev,user
    state: mounted
