apiVersion: v1
kind: Secret
metadata:
    name: authentik-custom-blueprints
# Authentik uses 40 characters for id, 128 for secret (for generating new ones)
stringData:
    pangolin_client_id: ENC[AES256_GCM,data:3j3sM1MOvuBNP2KZc2v4EegleFZCbgkGQpv59Uh6Wx+VspHa27yEfQ==,iv:U6iVtcldcO1c6vG8o+GlMCtmNaxiafK96x/Zc8Kepf0=,tag:eZrvwR8PYIeUvpIhc4nOlQ==,type:str]
    pangolin_client_secret: ENC[AES256_GCM,data:b6F4+FVBSxPgMdEg/y42jbgVnVzzJJuKB132Nxh6Zm+QM6o2DWRqYhqo/pMAUmsGEvPjhEeuiwYLvq30laHjNli8WQx3FDh3Br10lgBxScQ4AiX2nYHDnWJ0A+B1036YbTAmJD943HzZJ9pZMFWkU+R7P4qbGDgPynJmYpSknGE=,iv:oVmjDrep92x/2pmA+HFxA6ruhG0Ac/UV4zVurRVFRck=,tag:Zw+pVvSRoSLs68lqAMBjDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NVJwK2dtUmthYk5GYkVL
            S211NGV2TVZ5Y0VQVndnSStwbE9qUXhFN3o4CnI1TC9hc1k0Qyt6N1UzYU0wS2dt
            S0dIMENiMEZ2NkpaTWxlclZSMkZBM1UKLS0tIEtrMjNxa3ZwRTdvUlN0UlJLcmZ0
            UjljNzhDTG52MEJlbDdxanZGL2F1QzgKWM86i0OPsn/RWDp8yvEG3Qhdw1bJsWia
            Qd1Ee3SXS0wXPg1JdZz1c1ZwXhTD/PIADpoG/fFdnUa7oP3dYQkBSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T22:25:41Z"
    mac: ENC[AES256_GCM,data:dF0vMHioDlYJHyzyIIRVohu+AQqXCAzUoN4eNRqI8POFB71quH3aDhfwwCsuedzAYPlaozTpbHOtPscqpA/O7UB3n9QtABE3SOMANQKoLLLFA/7WuJcMqlwyidkepTWdWQUTHMDCLC/VMgseGXLWCoMIeCwLfibpqK+1EWbf/eE=,iv:CiKNGVxJap2KTR59wBVfaybI0nmfpRr8U1bU2xVHz04=,tag:ZOdG8hYuoM867QXE2bhjRg==,type:str]
    version: 3.13.1
