apiVersion: ENC[AES256_GCM,data:QwU=,iv:PEQE3meBm/bfLxCYJbil55WAol3ihQqy6SNa56/YEqU=,tag:d0+x6BCtp/AwVamUoUTxmQ==,type:str]
kind: ENC[AES256_GCM,data:pePSN2X5,iv:0zklv8KONrvfwGkGUIyBCpxyDMtSf1dw2XzrxoZhRTQ=,tag:PFAvdbO3l2l3FJ5VGkXfxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i1aAMS0ElQRbQXboQFJwurtS8fI/K6KtcUM=,iv:FuA6T9zK8TcRhhIZYvMfAXacuMDFmZtSYhrx5ufiN5A=,tag:TgfU/Mm24s7TmcuNQ+QUog==,type:str]
type: ENC[AES256_GCM,data:54gnpEK/,iv:EoJphXOKMY0OMEpn4c6VhB+6eJFUg7NL0BF2Lf8IB0Q=,tag:VOnNsPb/NGsUElB5c+gPxA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:5yhJD91X5AtRKVzAK2qMNLKuKLdvxpwwEglc+z5S+5UZc178,iv:TAZo97JtjickK9B8EX1akiPEPO4YI46Ki8hvsOIeY7w=,tag:j2EU6jG9Cq9wUCfFglHcrw==,type:str]
    clientSecret: ENC[AES256_GCM,data:jLsPkDxCqyHkqyTtiq/z6QLakRUyxqqeWVvaRpU82J0Vbar973HRjdBU70vRfFVtQn/Hl0rWR5ec0bqyrI/oQw==,iv:o+7ns73fcLxM8uHt5zKqGOSM5wSWtPEcHK776zXDi/c=,tag:dpqzn4IbQWEqWDkcH058uw==,type:str]
sops:
    age:
        - recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNzN0ak94YkVISlNtZzl1
            WmYzclNBQkVHekxJQkNCK1ZLMDExYUtnK0I4CkhHTHFTbUxJemRHaXNvZnMwRDMx
            S0NXN0lkb3BtK2FPc0JPS24zZWRST0EKLS0tIHB5TlEwMEQrNkQwbkd3TFJEOER2
            RHVWU243aG9waFF4cUFHS21Gb29hcW8KYhjECqJUR530kpWYZizzxzKwo8ISKZYl
            9C3HaKjeSwKs/xONK0vooxAUx3PXyQ7dD+5TgJvdEXKyJWp6zAqFrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T01:32:53Z"
    mac: ENC[AES256_GCM,data:kiAgGSMSu4Hegc3xI0oRMzgd/dDqh7qDcmT+MKrawLxljS0nWZ3DrucPXWfM3Z49FtoSPLudyiVhKWycg9t/9LxlIphDGFRqABd0Zq0Rtbtlz0xWoL+2WxWaRbAq1VNh9OTQv2yRcj8e7i296QQeTP/wQxV4mFXryZfaHQTc/Y0=,iv:clBTMwIwjZZS3UeWXW0EziuZp7KJCOeBCYbc8KVsIok=,tag:zKYc/hvFFOkdyuRfOvBnJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
