apiVersion: ENC[AES256_GCM,data:n0U=,iv:2BOQiZOH3TCNtl9jVRcMGy9XcMlVScjdG793KSYlcBo=,tag:PUdWaqEQo8Z/jTE6zDjvVQ==,type:str]
kind: ENC[AES256_GCM,data:ijUu4OTS,iv:arp4AEy07UL+wCNWMFlDZadFZ21xsZQVB/Im2ekERnY=,tag:HWQOZ4bNZqMxRMBcO/EBjw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rRj7nW/KsVSgwzAAS/IIstcqYcbVGd/qokA=,iv:QArFUH9JJPpkQXzG5/HPZV3cjLFu+6J/HAMnGGuAB/E=,tag:+WFk5DnmWVX5WHCl5Xa+bQ==,type:str]
type: ENC[AES256_GCM,data:yKQ/CdMA,iv:j9Ek6JG7NZpLAmyWNT/uvEynyLx9mNYseI6r4Tbn4Xc=,tag:TiHIsqQdQUdHPtmLnjdcvA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:+RDEm4JTe0Ya0BewTViMc+Z5c2LglJwOcPbIibBWPWwtUE3f,iv:CxYw5EstorYtVqfA2GLsyG/TxsNdgDIHUI3OwsPGnNU=,tag:LqotuYY3tltlJjcPgRoLSw==,type:str]
    clientSecret: ENC[AES256_GCM,data:Q93l5RODfvPyRkr05ivhzYF+S4zRVIVyeZn1SLV5RZgl2HLJVV/tzHIlqVQpvoxNagopkeE25WfZ9cV6MhzP1Q==,iv:8OIBYVnUyQHcwCx0KdBluDyJKO2yUbqnPuW09O0JMHE=,tag:tVn/8XcpLEIC5E7Kcm0hGg==,type:str]
sops:
    age:
        - recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjBtTjVHOXZrU3hNTXRQ
            RER2NG93cDhUMFBjRnVvbUZLTnBUUS9NSUZZCkhCcHB3dm9QSzJwelVCSHVmdTQ2
            a2ZJRWR5QUs0dHB6dUx4MHRvSFI1TkkKLS0tIFZOSGZrU1VnaDhYeStXc01jVVVL
            QTdQM0FBWHZMazlNUG5ZR2JnOXNhdVEKE7thYAT1imUMoj8Nf402YpypZUIChHdx
            1YK3wCWGzbOaMI/6Pu1TJveW63vpCers+l63lWHrWrTjQcuj7zSsGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T01:28:52Z"
    mac: ENC[AES256_GCM,data:xQokPo94wBSjczfk5YJYIcwH20NaFWGDsLpdr/OvhhDoBjxuOWrAkLcoVZl62mQDN2CS9XruJRKpxx4SsE6pzyd1/UYNVoyxdZm2xfBmVuRJMBt9+kPDZ/cy+0QUawQICAUQ351deWcLdWNBQa/6pqc0UcLzgTFkbptXDGYbCf0=,iv:WyMQGVxYwteGVpE+UmIYUbr85R64wGZDtMF+boAogx8=,tag:XK1XpN2/lSOHtH0g4rAbZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
