apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart: teleport-cluster
      version: 18.8.3
      sourceRef:
        kind: HelmRepository
        name: teleport
