apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - serverstransport.yaml
  - secret.yaml
  - serviceaccount.yaml
  - teleport-oidc-bootstrap-job.yaml

patches:
  - patch: |
      - op: remove
        path: /metadata/namespace
    target:
      kind: HelmRepository
      name: teleport
