apiVersion: resources.teleport.dev/v3
kind: TeleportOIDCConnector
metadata:
  name: authentik
spec:
  issuer_url: https://authentik.theblacklodge.dev/application/o/teleport/
  client_id: "secret://authentik-credentials/client_id"
  client_secret: "secret://authentik-credentials/client_secret"
  redirect_url: https://teleport.theblacklodge.dev/v1/webapi/oidc/callback
  claims_to_roles:
    - claim: email
      value: ".*"
      roles: ["editor"]
