apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+bIvRHhxysQmtuYZS/PBx3Szh1eYmHlu576D7GiCOTB9i3q2,iv:j8fenoYdU9w2qsE/3rFt6Rca5JegmyWfcJettI1aWyw=,tag:LEs9rYo/QN6ytfBKvwb1Ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZWE3clBMNEtZUTAzZEV4
            RjBPWU1xT2V2V0V6eFhRK1hyQnoyVHRERFJrClFrK0Z1Z0RPTmRQQU4zMTdYMndM
            clFZeEpIa05KNUo4eHVBQzdOc1lTYkUKLS0tIHFvZldnWi8zVDh4TjRiUTIyRWVu
            SHM5S2R3dU4vN2Z6RHppL0ZiWFhlVHMKmN5lMcwzSG0K9qJ1EwojIyvWL4uHIGl0
            +OHM+dX+5q9qS9d+4zafBzkVdzhwnQiXzMZyyS2qPmbzzY+Yl/KUeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T04:43:25Z"
    mac: ENC[AES256_GCM,data:N6UR8/BeZ7FMYkYkqIBwOTfIOOGpVZdgM7mdS5FX+/LlWKgKqe5bsrm/h7lWHUtas4yOQRoeVchf2+9mtBE0EMtwp+L+J8VhZwagSmTJr152IzuczJAhRVE2MpxSirZQjibRwiFOxsrHclW0iX1IWV9nmOxP5AgT5U/XXaajlAY=,iv:z3XHDGlHhCMnc3kYJEB/JNfnrkHxUaKrmPXZjerazLI=,tag:EyemX+Z2SxI2Sh6tLFl3eQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: app-cluster-server-ca
type: Opaque
data:
    ca.crt: ENC[AES256_GCM,data:12QdsRRUd0XGDYuBm1xyQFotrxjWMe/vUcIdIjXAi/XLOAExGpUYuHX0MtMdLyYX9yB7mCb96Z69ScUUe9T1EM31ZtPSW426AzT+fNjTrTaXdQvLXi6eH09u/xI6yNRIR8ggR+14ID6DEFnxfBcNqw2DE/tX54mw9xigY5KaUNyQfsxyaBVQuTnbJaVrsDC4A+ohceMjELTh76hej4f9Fu3unFzyTtbyHPCCoC/TnOwSEJvLES+YMrE60oTwcGswEQtkYRCjAZcUOjygfAXEqslNgJxicU5Omi3GdnpHCjk2fsnITiKsr+V5fgoVM4qZ0Rcci2g0o3lacPO0NYX86GhTuZhwXUd/AAwdETUXaK0zBlgwOZVDYLoAHun3GkQdEytZ6rnr1qJRsqH4q4lRCKuUDn07LnE40AAFJC7JIp6SzWbtjGl26Lb2GujKjcGBeEDTKshtswyLuwmayKV57scLMH7SWqTrYCnmoUEhtGiCmZ0K6MVeIF4+8kPXVnm9STzq5R38HQdPTkFM37Tbd21JVNw9d5jxDXx7eAbjsPOXuDHdLdLwg3j2Fv4BMYXogbKkWKJtUsTGrIuxLAwL2DzSJA2Ri6DjUZLMdPzJiaohH779RaZZ6a3A3hQ63elk0DM579CcMA3qxqYKYOg877n03Hs/xDNZEreEx7Sj5PiRO2BYlZsNbxd92Q0wZGoeGe9FeBRUIzP5vNUq235lY0b4ikqNgAB/g0l5i7l/7pgDcpaCAlDMwsQas6KN4PqCfyt/dJrPwQ43ZHQXbpJBcsuw0ms0tV5e4fKgzaksI031BRF5l6OrPG+O5qwhvsIR0cydEA9loeegBkfc98APAtUbE/WWxi/FHYNV4OEQuOhjpy7/Ezw7F1gyYd4Z2FYxbeESw41rL2ZvBC3R9UayWdC6W5I5EFFt6ARTJruuov6K4CX00eKmw6MgcOsS9g6nLUUCmqYhoDfVaGMBmlXip0yHYXc=,iv:vbuslsoYxNSPAWHplJWmZeOHi5FhrDo4y+BHsB9A1so=,tag:cl8RP24e1lMjkd2KRpIKxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZWE3clBMNEtZUTAzZEV4
            RjBPWU1xT2V2V0V6eFhRK1hyQnoyVHRERFJrClFrK0Z1Z0RPTmRQQU4zMTdYMndM
            clFZeEpIa05KNUo4eHVBQzdOc1lTYkUKLS0tIHFvZldnWi8zVDh4TjRiUTIyRWVu
            SHM5S2R3dU4vN2Z6RHppL0ZiWFhlVHMKmN5lMcwzSG0K9qJ1EwojIyvWL4uHIGl0
            +OHM+dX+5q9qS9d+4zafBzkVdzhwnQiXzMZyyS2qPmbzzY+Yl/KUeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T04:43:25Z"
    mac: ENC[AES256_GCM,data:N6UR8/BeZ7FMYkYkqIBwOTfIOOGpVZdgM7mdS5FX+/LlWKgKqe5bsrm/h7lWHUtas4yOQRoeVchf2+9mtBE0EMtwp+L+J8VhZwagSmTJr152IzuczJAhRVE2MpxSirZQjibRwiFOxsrHclW0iX1IWV9nmOxP5AgT5U/XXaajlAY=,iv:z3XHDGlHhCMnc3kYJEB/JNfnrkHxUaKrmPXZjerazLI=,tag:EyemX+Z2SxI2Sh6tLFl3eQ==,type:str]
    version: 3.13.1
