apiVersion: v1
kind: Secret
metadata:
    name: teleport
    annotations:
        kustomize.toolkit.fluxcd.io/ssa-force-apply: "true"
        resources.teleport.dev/allow-lookup-from-cr: '*'
stringData:
    cluster_name: ENC[AES256_GCM,data:4ga2qfLEJgkv+Lg/Rf9pku4i/S0v4goCJaw=,iv:xL3qaNSOmM3oxjHyf/3Ragkzdm5BwUjHiuvYlNgpEP8=,tag:9600DAkMWZSo6RzuteZoGQ==,type:str]
    email_address: ENC[AES256_GCM,data:LTr8wkAGIqhq7KOH+YDO8WiGK+T92HHJpeIybi2moA==,iv:ZH03lI8IDdKItKnCK2FlQtU41jTs7D3cScgFi+H/foo=,tag:RPViicUIf+kmsl6rUqGlrg==,type:str]
    client_id: ENC[AES256_GCM,data:z8ji+WxwTJ4eifEdb22lmTWHgCsMvmEeuuhrKG9LCY0NM7exK1gSmw==,iv:X5qWahMCoTDQ6d4vcWA0NLnBWTIhS1bk6KSW3k6wLWE=,tag:GJHuPpDcxowK7D+1EIQXyA==,type:str]
    client_secret: ENC[AES256_GCM,data:ibhELwjK+OzSYUEKCxvOHQ6JZTVqfDBLIksDQ11TpRRxsqMrfLqzatODeQBbHHu5n+kUQOJjjs3RUqyb2lplIiK8R3JHfBQUeTumOTsIzM65B88/PgGf6LTb/3CI5OY7FknrjWF/lJI+qSgTGde4t7lbCuilXJYhxeEgHzhTC4M=,iv:oMvWkWlJeQ5xGKYwWc3528DpjMnx/GJmndb/WW2bsmk=,tag:F6oaQqdd6m3QBoE5p9yJtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOVkxc3E4cExkOTMrZHRT
            c0tSVTV3R1ZSZ0tlVFNkWGxjdXk0c1dZUVM4Ckh3QS9lM0UwVTlDVVYxcmtCTEtu
            VlF6bWFXbURoRHZTa0RHTjV4Z3Z5Q2sKLS0tIHh4WUlwdDNwOUlISnV4QVZseHA0
            ODFsOEpRQ09LbGdldCtMbGROS2lIYlkKFFzZ/8XoiIQBKltCQn96lH9r5chktRb9
            ZOca1kT3akVeiVQbbqMM+lQFbuNqmgRhtWsb5xzyMK57RLG1PK72KQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T00:29:47Z"
    mac: ENC[AES256_GCM,data:gy6Rz5j4MS+5OYKKAGhDUeoxL+XBLCqCnDlQZsYqC5qQxuBVm2bS1sMoa8is2K+ifWzKbEDaeUhykWtB6jWbfR6ONi5fz6vaJ84BFEK9tqArlKgxviBItR0o8MttS/PJIKmZa0a/2BF3vDIk9CPjq33g/Hbq1ib1nHwO+jY1mc8=,iv:2aWUd3CgcX8TIY5H+VPPU+dunrAPb1wsjLVBbkFod8Y=,tag:HD7KjEbG4oHXjtTwm9HwuQ==,type:str]
    version: 3.13.1
