apiVersion: v1
kind: Secret
metadata:
    name: teleport
stringData:
    client_id: ENC[AES256_GCM,data:P2rWmydJecfR/LVVCk6Hn2tj5cM5h8uPd6aqH2Qdaifzep8w8rEiHQ==,iv:xND46WPeW34Ua26Sk3ZYIsEOCMJXkEATUf/EqyQ2Nws=,tag:X53GJL5As40Emd4CwISNFQ==,type:str]
    client_secret: ENC[AES256_GCM,data:3Kw035OgAVyd1os6XKFdu2J1yJZxPHWIc8oxnuRWmzGPRKzBboeK6LMlocy0d58JoaGEsGnEbWtSsDMMIsoFNEYc+0ufjm/RWXNRVKjANHElZZSUqGad8d/cXIFdwFYRSAtnz4L0TncyQmLo6NCGeiODJlzIOgI5EhTZ9XKtrZs=,iv:tdC6Z5nISctAlR7FJrql5jRGPrGQ6akOKXZTv4SLAHQ=,tag:rM3P1gEdpkMZiq+D6S7dxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPamt1MVduZnZldTVDbTVu
            ZzhxL1FUbU13Z3Z2Ulk2U1Rub2wydHJyVjM0CmJPblpSdFo5aDdPNnQ0UlVvRVJS
            WTVqeFZLczFVZUVUb3YyQmpFVHJHdVEKLS0tIFJTVlNlWmdIbTdlc2NmbmRvR1hI
            Nis1ajRHbGZSS2FSL1VyMTdleGJmWGcKRmhruxv+BQXZLFTYfcs/37FaCuLzbjDI
            RUkqe5CqQzpoqAIko4jZu0JP/J8eGA4L31MNkoLaD65bKGoEPt5myQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T21:51:35Z"
    mac: ENC[AES256_GCM,data:tifsEhh8lyMkOvbJTlMpNZ/wdyYL4QlqPX6eWCNnIhHQjhSnwhZiJLPoMV541ewPwVJF6hNq0eF6gg8KVs47xmoRyL2WgPfI4hMzmnqCZ9Us+4HWXPFV0ZOUIgXpsNkJKgb/DMuFgk7zQ3SUt2G4CWjIZsPlCSnHRMLlrWRx3r0=,iv:f9aGnFyBrwc+GGLFFXDHMOsY9R4I7SisXkOldBRNy14=,tag:Idi9W94JRZIEOfFobqmSlg==,type:str]
    version: 3.13.1
