version: v3
teleport:
  log:
    output: stderr
    severity: DEBUG
  data_dir: /var/lib/teleport
auth_service:
  enabled: yes
  cluster_name: teleport.theblacklodge.dev
  authentication:
    type: github
    second_factor: webauthn
    webauthn:
      rp_id: teleport.theblacklodge.dev
ssh_service:
  enabled: yes
  labels:
    type: node
  commands:
    - name: hostname
      command: ['/bin/hostname']
      period: 1h0m0s
    - name: teleport_version
      command: ['/usr/local/bin/teleport', 'version']
      period: 1h0m0s
    - name: arch
      command: ['/bin/uname', '-m']
      period: 1h0m0s
    - name: os
      command: ['/bin/uname', '-s']
      period: 1h0m0s
proxy_service:
  enabled: yes
  web_listen_addr: 0.0.0.0:3080
  # the public address is the public hostname/port that can be used to connect to Teleport from the outside
  # Cloudflare listens on port 443 and redirects via tunnel to port 3080, where Teleport's web UI is served
  public_addr: teleport.theblacklodge.dev:443
  # (optional) Paths to certs from certbot
  https_keypairs: {}
