apiVersion: v1
kind: Secret
metadata:
    name: radarr-config
    namespace: media
stringData:
    config.xml: ENC[AES256_GCM,data:bhCFYNJZLrPT13BiVJHl9r6JmFhCxVNppOFNZRlt2K9oAEIe9XSoq05dbZ/tUSwAn+hXRi21r6Ny/FDkGGNtGQWJYD+VZwmonw3JSA74OsKS4AA6Ov2lzytdzPGjw6Qkcy4qQa9nrp2OG/lW9vBeyiDapmpuSN6HmJkop4BMGy1rzFTqqd/AOTJ1iRA30Vy5DPQVyLWkK1uDAifA3Lw+Omo+5DhjehZlhZXwbc5kEeMXUd4Z14z6vra1Ai2ygV5tvuKwWuY6xEKuO3s9haSz116MLB16KgWWUAEjlW7I/39SKz6B80rdOVuJK7xVuAWrF3lHypLHOsJLkW6Ya/towz16pXX1pyhmql30I90/IJQd1Zg7FrxPscLmOHj+FKub6U6Uo31/qeAkF6dxIxrvTj42X0lFZsiEBZfnBdLJEiHKJRbki7I=,iv:qHBnUJ1XC3ylXFVrbC7c4/XGC5S2vLuG3NweOC7QEiU=,tag:QIlUkbqqdrmK5F8bIz+v0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSjNJVG5mQ09tdDQ2ejhn
            eDhuSmF4VkxwMElnaGRBVk0wMThobTJZWW5zCmNtdkh6WlZNcm5EemR1RGRkNXBw
            MnNib1FJN2VIdnRhR2VPRU1MNWN4QkkKLS0tIEU4TmFmMHNoamJOY0FOemo1aDJy
            WmJFdnUxQmwvZERQRWN5a2hpUEZPdEEKOHyL/+VZxuEQ42tWhqEZry9uNDGyIGue
            qHN9SDm04jbzsG9EeRSIoYp5XtfNurcV1YdBocs+qhUTCUuETX81Vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T05:08:36Z"
    mac: ENC[AES256_GCM,data:Bu6CQbkitvZGo8fhaXOrET/cMGEepW5bo6vUj1Fte2MlPR7DdFdUaIG4rVmNGIT7WsgVNt6hk2iHTKhCsUVi/GRDNXT9jU5FfUHxYclereWBV0B27VkChZXHJ7Du8n5AYXhhORQSZBkkGR3uywrgDF9sNaMn4ff167AUnAQ67H0=,iv:uvEP16iy5ogxWHLDvg2xnZEmsZeEtTpP36oUUuVrLYc=,tag:/0+dTBFMLBzqrPPLebRtAg==,type:str]
    version: 3.13.1
