apiVersion: v1
kind: Secret
metadata:
    name: radarr-config
    namespace: media
stringData:
    config.xml: ENC[AES256_GCM,data:R8xBHUNAfKhr3Nvd4fKLy20e8YiRpS1TmjOKUiaGzf3J96KWzTSNqDVHOgzISq6BJsO+AeReKkPm+Pu1AYB4vUY64/zD/2hGpUNI5rcVlO+NlURWPdsd2Vydmi0JtI4RkXGU15nZpP9LgRqbdiFiJ/RfydUNvHRZ7k5R3wH/vvqm2A8/iR3L9eGg7wvfAXLYd32iBu/KvaSO0vpnshr0qJ06VhlYRJ7VMhob51ypIjBTgId2IYXYk0Ld9t88ByziT4UUZg9lkE5mTkWJSADYFWi9TGTyHWaqNgg11PnF08XUSiZ7rOCoVHr8SOnm+BJ1CZZpStK6RzNCq+k0SRQy6R3JfzxyRbCdBSqE9BoFgjykurvibsMheSzgO8lnJL1jZ8d/0gK4AOaLwkt3jEc8q6kqjoTj0fivVjfqWPLlsXbKvv32pIs=,iv:lP/zsMgkxrH9Vn1Tgv5G6aUj8tDselgsS4ydIcCHlD4=,tag:OH4yfFmd64qIo2erGAOpiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd0JUSmVDMUV6cnJ4b21K
            TGVxYnJGTFNacGVsV2VDeUR4MitUK3lrZENjCitUL0NFMVZQdHJXbmRwVk5SaVNX
            N0xMUFE5RExFbHNZZ1dsRXU5QnNXZkEKLS0tIGhHL3lvdGhsbW9hRUxTdVhORnRO
            c20zZHo1VHZmMWc4WVpWaXRSUnJxU3MK03Z9QSiclVQwz7HxMmKbyo95ia28BWKM
            k1ZnH4pr0ckt58jErkmTp3t8m9PX39zIjJ2whPGjVRaXQY0H83IIag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T05:17:23Z"
    mac: ENC[AES256_GCM,data:BvMJxhMTIB2qeqZYrScC7xxh7EoSgezoJKfDZAOJDB2uZcnCWtMmXgH2monaG0ycWu5LM5B2ABjBL6PcgtLLLCGS3YMMKF72ZsUs+7+vCJy1sn++vxwTifTlHYyw3i3cHEM6vOwVwCj1LIaWNv690aqACwSmmaXPNb8+5Rn/ZpA=,iv:AyUy42C2JPgKcMLDRI/1E9HY++tqkxSivPsTONNcd6g=,tag:cUoP1hQDs76KAV8aCn+z6Q==,type:str]
    version: 3.13.1
