apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secrets
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: my-app-secret   # <- Kubernetes Secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD          # key in Kubernetes Secret
      remoteRef:
        key: DB_PASSWORD              # key in Infisical