all:
  children:
    k3s_cluster:
      children:
        server:
          hosts:
            kubernetes-server-01:
              ansible_host: 192.168.100.15
        agent:
          hosts: {}
      vars:
        ansible_port: 22
        ansible_user: ansible
        k3s_version: v1.36.1+k3s1
        api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
        server_config_yaml: |
          disable:
            - traefik
            - servicelb
          kube-apiserver-arg:
            - "oidc-issuer-url=https://authentik.theblacklodge.dev/application/o/headlamp/"
            - "oidc-client-id={{ oidc_client_id }}"
            - "oidc-username-claim=email"
            - "oidc-groups-claim=groups"
            - "oidc-username-prefix=oidc:"
            - "oidc-groups-prefix=oidc:"
        cluster_context: k3s-ansible
