apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
    namespace: media
stringData:
    QUI__DATABASE_ENGINE: ENC[AES256_GCM,data:cR6I4utkNzk=,iv:LSYBepFZDg59xXTkWb4vus0CSGzG62UmpioeypFRn2I=,tag:U1zWFanF33xSOCYUurNSaQ==,type:str]
    QUI__DATABASE_HOST: ENC[AES256_GCM,data:OtEGgu+gHD6VJHOjMUp+3e8x30vVnKkHd5E99yZ4Z9Dm7zE0yqECNcnLIgQwOho=,iv:MP0rI0sWEE/9IiGDyENf0gohmaBhmqA5S4KS3ee9If0=,tag:4H2pkzZtuhGdZ3ujL+ZnAg==,type:str]
    QUI__DATABASE_PORT: ENC[AES256_GCM,data:vq9dyA==,iv:MIfzMhY+CnQbluwSGxG8Zyi3s7rjs3hiApJhu/GO9tU=,tag:5k0+++Rgfl07jBHlCq9V+w==,type:str]
    QUI__DATABASE_USER: ENC[AES256_GCM,data:uhtv,iv:RM82vfQU6Z0WqaIpL6QXOz+ugQYqK1xiFDjSaUSR/zk=,tag:M2VRY/tJMLMlstPxg37pSg==,type:str]
    QUI__DATABASE_PASSWORD: ENC[AES256_GCM,data:LJpiVt19Y+Jwb2ecK3l/tOuzjBUOVPnfiVlYlqF6eG38tmpEYywZALuJxA==,iv:nJR9VzahzSKUmeKdQ67LlYSSV96/Xt+pxSbQEELbjdU=,tag:FFcJl6zxp1uCqLqK4gjpPg==,type:str]
    QUI__DATABASE_NAME: ENC[AES256_GCM,data:BN40,iv:gWai+LCjfqEJs+7nC7HFEpDT5bX1Ud28BxtzKaFyG/8=,tag:bIFNxewHJ/TelLHWi2r+IA==,type:str]
    QUI__DATABASE_SSL_MODE: ENC[AES256_GCM,data:n+WDmc0asw==,iv:nu2TYDdZPbVqO/2DZwNU8bV+oN66KnxiPGp7FcXB6nI=,tag:IdbealsIKsTM9Tmiq2j3Og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbHg3T05HQmE3RWlwY1E0
            bFhXNFpqVGlsZmxvOVllcjVHZ0k4ditVakYwClBJZGdxb09jSlJBbGdaZDlzeFZv
            RFNBcEJLWXB4dWMwczRDdC9hMFJMTGcKLS0tIGhtL2pmc2Jidlh0M2ZtQUd2VkxW
            eHNBSE13aGtoTmttL3JEUzJoVmV6bTgKwOAnD0P25z4UMmAQclelLlng0xZoGa0V
            jmoK36Uq/iKnIXJ2nrZHjNlTICmnQRn1qJGj/8LL8UG//GDMKysE+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T19:35:10Z"
    mac: ENC[AES256_GCM,data:f9i2erMkGfZa78LI4DMUHUNv8iE/i05mBWSB9Pd4NKDo9jCiPs/d7djPLZJK1Cd+cE1PThQ0bCdykRb8LLxweduB7FPSmHdW29lWEH+io0/st9A8Liv7yU8RK2JRlVzhLqRYTQ8G8M7Sm+mZXSdqO2emYhkuIzh63IOFK5lcNCU=,iv:b0FA1i99LyT1wzwYWNdCc/L9zCjHDcn1r/y2lEI3ri0=,tag:w1EscXq+DN9BVRqlRlzm5Q==,type:str]
    version: 3.13.1
