apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
    namespace: media
stringData:
    QUI__DATABASE_ENGINE: ENC[AES256_GCM,data:I2lGEM6d14s=,iv:DtKae9NQQTzmFjhff1o7miwokd+eEgOR7Khltj82Jow=,tag:6G0x9B53vh2V8GU5sMI2sg==,type:str]
    QUI__DATABASE_HOST: ENC[AES256_GCM,data:vTwpz2PLuOCZqPSXAnBiwjBowImGm4l73bBTJYWjKxRGZe+/4fTGBOIepphCzYg=,iv:GyNdvpBLOjCaPJEUWg3V3yKEC6Wr/fvp7FRHzKw5YQQ=,tag:yPqiY0KHdyUVviQmEDe5eQ==,type:str]
    QUI__DATABASE_PORT: ENC[AES256_GCM,data:dIAuUw==,iv:xx5EliH6IsfSbaGNFwiaZEoQN35mV/XDxyzLmQLM6IE=,tag:rwa13qXsbntKOAnw97tSqA==,type:str]
    QUI__DATABASE_USER: ENC[AES256_GCM,data:Ks9H,iv:XR7WknE1/0ZusLn1Ad8aFsdma3T/J9RThiISC8pmVNo=,tag:pd+eyKyDjUBzhKSKAZU5IQ==,type:str]
    QUI__DATABASE_PASSWORD: ENC[AES256_GCM,data:gh9GGjjb8/CHRGsCObV6YJg2joiWhEzCR8UDEdYTFtlfcypcQH7thtbkLg==,iv:WKxf1FEvUMOPVdTmTxpyBobP6IWd+z/p6mp3XMIkWCg=,tag:YCO7Miu9cA034H70dPsytw==,type:str]
    QUI__DATABASE_NAME: ENC[AES256_GCM,data:c3Zt,iv:n4/ytUxw9GpSWzUFjfIp3R6MZolG8BaUC9O7qQ71vaQ=,tag:ahAuOq26OZZWDqNxxr8KYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWHJ4NHpSK0MxdVY5b1Nm
            d3kyUUptTGgyS2xtQ0p1QWJVRkk4MGxsOW1vCmdTUFpreG4wSGhQL2J0cXlzWTM3
            UncvMzdCUVdnVkIvWUtYVFk2bWtReTgKLS0tIDQ5UGQ5NmpKN2VhQmN1TTREc1gr
            bGpGQWQ4MEdERTc2WEFDai9URkYxMXcKnjqLho9MeUgD8pn5y9X4Zt/OPAdOourA
            BKcrODH344+4ECei3LCY74ofKTuV0tku00lZ8vhuwm1hgVlgo0O7kQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T18:33:09Z"
    mac: ENC[AES256_GCM,data:J6pBI1qd944Rv76f5J+oqsbjTlzIrWR2gVrnx4WJOpLdyek4W5OHQNPsXoFbidrAH2CY8ea87AMsE6SApcHmb3g9hE4XXAAP9UOMLPbPVY09JqPEylZbVo+sy70zp3sWQNh13Kn6/5FPxtMXHnkjTQOcgDwh/GGwZfkJV1g9I0Q=,iv:c8/3H27lc27hX0Ipq/cNnVTtAofytbEhG42veMUwW3g=,tag:fnI8lIf+/xj/OLeGdfv+wQ==,type:str]
    version: 3.13.1
