apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
    namespace: media
stringData:
    QUI__DATABASE_ENGINE: ENC[AES256_GCM,data:UFbo7meo6t0=,iv:utFcVtlaTdxg0W/Pzs5F0ng2ySh7NDHWS3UzhM6tzqY=,tag:ErPyWRU0TGSkrC3WqWKfoQ==,type:str]
    QUI__DATABASE_HOST: ENC[AES256_GCM,data:ffxasU9id+2FWlGzYOZmZVbeVl9ktUYf+nYSpPX5nH3I83Ri4oNnbw9PRB95qe4=,iv:dh8Z/PIoItA3sFFtNAJHK7lx3YVxjuQDpcYCwX0TMUo=,tag:0WJkQUGOMLtkCNvYYiV3Vg==,type:str]
    QUI__DATABASE_PORT: ENC[AES256_GCM,data:6pGE8A==,iv:72MZ/6JbSHogNJuH4qN1K0ECXKZOFImZg0v8d9NduNg=,tag:WmfoxytW2WceLu9z9ceeTg==,type:str]
    QUI__DATABASE_USER: ENC[AES256_GCM,data:98RE,iv:ImgDrcT11JmmRa2uV0MA/SSydPP2ytkiw6SSo/o4Dgg=,tag:iVJz3tpBQCrwP64hRFExSA==,type:str]
    QUI__DATABASE_PASSWORD: ENC[AES256_GCM,data:kVHgp7nhOmJXyOYZPzXNGpcldIj8CpQGcFK66EN4PC3myDAvtE2oZBLikA==,iv:MzBA2wAnB36WCRh+s8ueLT7F63P4AIlXkt14d9zzXQ8=,tag:hh1QD6PGYL3G5IX5Ty4Fjw==,type:str]
    QUI__DATABASE_NAME: ENC[AES256_GCM,data:Cl82,iv:dJNPINpeHQglw/pClYghHPWbwJoGzOoUsUyUBHZ16Wc=,tag:KjX2O0AHtKNrIoeZYSpVAA==,type:str]
    QUI__DATABASE_SSL_MODE: ENC[AES256_GCM,data:leX2h4xjEw==,iv:scOQy/WUhZ4n4RerhuZiPF/B+WA4ONfanfeYi6vDh9w=,tag:yt58Nr2TI59q5Cdsgl86cg==,type:str]
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:7QNhA9KRoektxAnfDHX8JfduNT/lpQ2Ltyr8dWC/bKmGoykq2tUkOiM+D8s=,iv:AeBcxHYeNXL2wVmLMAKR5FeHsXQikgWMBKyroUfOcNo=,tag:ofhDYFNMvrr0/Qx9zhVZoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OFV1QUpUWEljUnBGczhu
            OGVEdzRFVko2U0ZPMXEzU0FQS25ZRm1yaTJjCm5BamQrNnlnK2V5dFU5bk1ZeUtj
            cmNVYmFoVWNNWWpLVldFTktlNVVYQzAKLS0tIHc2WVEyTjBNZjloWUV1MnR4d1JR
            ZExFVy9TYjlOdDFrY0RZYzNWRVpJc3MKnmxUCbdjoBRqaaKt3PIhj/+c3v3Ffl4G
            On2O0jt8ihoob9TxYvXPlMyBmPlOr3B+gHZ/T1L4kSWmgzIK8Hurrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T22:48:54Z"
    mac: ENC[AES256_GCM,data:90VThEK4Cx1KzyxfChkYkqMYgtzKaZ+n8MLjzY9l5d7FQ46tW6AbgQ/hBVh3UMEGiif9sBbNksmoi4Osobvx6yAddr1NNciKnb96+5UlLuze3GIV2uU3N0Zj1THE9Q+V6EvuzwIfGE+Sv3BewHhztQcZjFWoY3YWPAO1xKjY7hg=,iv:48hMHR4rZ7c1mHY7u+bBGbT3WCNEOCXOCwDkQPV4HeM=,tag:qgbB20hs/NK8vq6LRy3oaQ==,type:str]
    version: 3.13.1
