- name: Install packages
  ansible.builtin.import_tasks:
    file: packages.yml
  tags: packages

- name: Prepare kubernetes tools
  ansible.builtin.import_tasks:
    file: kubernetes.yml
  tags: kubernetes

- name: Install sops
  ansible.builtin.import_tasks:
    file: sops.yml
  tags: sops

- name: Prepare devops configurations
  ansible.builtin.import_tasks:
    file: devops.yml
  tags: devops
