- name: Install SOPS on remote hosts
  ansible.builtin.include_role:
    name: community.sops.install
  vars:
    sops_version: latest

- name: Install SOPS on localhost
  ansible.builtin.include_role:
    name: community.sops.install
  vars:
    sops_install_on_localhost: true

- name: Output secrets to screen (BAD IDEA!)
  ansible.builtin.debug:
    msg: "Content: {{ lookup('community.sops.sops', '/path/to/sops-encrypted-file.enc.yaml') }}"

- name: Add SSH private key
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', user + '-id_rsa') }}"
    dest: /home/{{ user }}/.ssh/id_rsa
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
  no_log: true # avoid content to be written to log
