apiVersion: v1
kind: Secret
metadata:
    name: homepage-credentials
type: Opaque
stringData:
    PROXMOX_URL: ENC[AES256_GCM,data:ZgqPKVjRWVOKwlh+1dBp1Se204UpiSU7YbOjw04dK+ATdyxUq1M=,iv:iMEjEUGr2qilYjYunYhYDgWW8m2bcfiTVFkZxBCikTA=,tag:qpj04iwQ51lyQpS+SEQ7MA==,type:str]
    PROXMOX_TOKEN: ENC[AES256_GCM,data:uIkDmv1530mIUNxndvHr1g8=,iv:nsCERLIgLrC/4Cjj8au5UAYyEU3wfaqeqx6cWpU68Z8=,tag:4aXJLnk5W7O9mbDE+EKrhA==,type:str]
    PROXMOX_SECRET: ENC[AES256_GCM,data:cLZf1GgApT25nbJXFPTgDc4StRQqVn8sHmZIyy4F8HJwcdb6,iv:Dtef2/ZU2bnf783OuBrQty3IERcmxJhd8jJO/8QAk2o=,tag:7zPVP6LcyNN7iUksFiwsiQ==,type:str]
    RADARR_API: ENC[AES256_GCM,data:M/Y1Rzn6x0xIQyVOtprDXOb3YXRsKUF8KbPtwXkFwVE=,iv:VKuV9cCKUrnu/rG4uwXoor3pYp2rHPa31iWKwuOMQ/4=,tag:d+NGLe6X+22Ap6XS4iI3IA==,type:str]
    READARR_API: ENC[AES256_GCM,data:sr1uMzfUVn2tEwz/DjSbKD16Ou8mxyj3aMAE9j7riEI=,iv:g+pSSGX63RKVWobkl6/ckb5IVcG2JZXla/bKbzPwAl4=,tag:tn9SmeffINZIY5nt9NKYXA==,type:str]
    SONARR_API: ENC[AES256_GCM,data:YsneYIxE7PKZ6t1fmyJGD11QnxVcsWwpTvK/YEg3DUs=,iv:LHGSdJaTz8qgo3QubBf5+/CkXmIE4y2XSl+h/HCpU5o=,tag:pKjU8O6LDK5qpb+k+HV6Tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVajhod25NSHZRYmRuS1FJ
            SnpjQWJuR3l6MVFFbXA1MU13QldMVXhzcW5VCkVXWUVhaVZXeWRGZTE0VDNSclZr
            ZkhnUU85T1BYQVJYM0NGWWVXT1V1RzQKLS0tIEw0VnVLcmZ5aytDcGc4VUk2QllM
            RVlVbE8vVEVteXpZVFlMTUdueGlrcEkKuAu3FtttOBldiZJQYvFufBUXYwlk9hbr
            ly07HB1BGhdehhyncUgOdD8OzCS2rIILK0DzqesJ+Gc/I9LgTIunRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-19T05:29:25Z"
    mac: ENC[AES256_GCM,data:MUG+iEuqTWF+lp83Fsgn3nuvGoG75cjNVBzmT2II2WyuO49wYY6yIoiGx3vdSSVqFZb9RqZSPF6gkPwRGCaj9Vb0QGAdcaT9xfNEVOqsyp1MfqDzYElzB05EiL6NGZhJjuYkXydZaN18MD7CwLtNxAzLZy6ybEWcSGqhI4jxSsg=,iv:OOWT2Jf1bFX2Yh3URp+qVwR9EAUDCx97gBOY+cDlwlA=,tag:qX/hBAZEB0g34H/1Y38tkA==,type:str]
    version: 3.13.1
