- name: Install cockpit - server management UI
  ansible.builtin.include_role:
    name: linux-system-roles.cockpit
  vars:
    cockpit_packages: default
    cockpit_port: 9090
    cockpit_enabled: true
    cockpit_started: true
    cockpit_transactional_update_reboot_ok: true
