- name: Install cockpit - server management UI
  ansible.builtin.include_role:
    name: linux-system-roles.cockpit
  vars:
    cockpit_packages: default
    cockpit_port: 9090
    cockpit_enabled: true
    cockpit_started: true
    cockpit_transactional_update_reboot_ok: true

- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Allow http
  ansible.posix.firewalld:
    service: http
    zone: public
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true

- name: Disable and stop ufw
  ansible.builtin.systemd:
    name: ufw
    state: stopped
    enabled: false
  when: ansible_facts.services['ufw.service'] is defined

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Allow cockpit in firewalld
  ansible.posix.firewalld:
    service: cockpit
    zone: public
    permanent: true
    state: enabled
    immediate: true
