packages:
  official:
    - paru
  utilities:
    - btop
    - direnv
    - yq
    - age-plugin-yubikey
    - chezmoi
  applications:
    - zed
    - vesktop
  devops:
    - just
    - terraform
    - packer
    - vagrant
