apiVersion: ENC[AES256_GCM,data:gYk=,iv:/zuKcSmz9GIWRmJk/Ip9xwZsuNdeOyGspQjpCbYlsPs=,tag:+7zFDBcvCK+sIzM/m6MvsA==,type:str]
kind: ENC[AES256_GCM,data:TrsvhHhq,iv:hAYkiRoeROZt3u8cUhPjsq9MpSKzxHyinTRkf//vUM0=,tag:xK08gpSy94P/TUIuiAjKiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aC5/47xRPgbtINlqm/w=,iv:Cqk5FHGei/6yfZi2s/+Df5nLYw9GxD7ahkmIF6SQtjM=,tag:3+7vURMLAEqed2Naq6/Idw==,type:str]
    #ENC[AES256_GCM,data:F9iQSilFFzFDJ8IXzA==,iv:UA6GAVVdyHPl9n4cb3s9T4HW65qy7FgckJLwGezXqRM=,tag:TKs2yofLbx5VeXsKQB6D4Q==,type:comment]
    #ENC[AES256_GCM,data:tb4OBNjP8qY851zY59HFp8++MuJu8T6AfLTE7J0MX4H9vtqXmmN0j/Q=,iv:lKDuceYg3oHu+9yHF5zm0jqiWoJJCEM4nfleUo6g+VA=,tag:Nb5JXNo/1ovT9+KX9IpGdA==,type:comment]
type: ENC[AES256_GCM,data:7qRNNZwT,iv:OF6p/xf3JxjDEmCIQrDlEkzgv1Rb7xG/2TRHBp37ZG8=,tag:dvMt43J19oPm+xEo+8Q0YA==,type:str]
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:xx/H2z67J4djT75RJFoCbn2arHdPEGB/9jVLea9zCLU=,iv:jpvnvIOEA1P6wpG6BYm200dkGsWVGs/3B4Yhf/yXJXE=,tag:R0XRH7E6SKcmecttmAGwcg==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:hcpfN7jQs4h1wEpeJy/a/k4DMYu6TT80JwGxFkqyjWTvrUOp+qgtVyGDMCh9Kjt16eRqq6k=,iv:E6H4wbwV9zHTMMrEXAbO4cZskMmDRK2nVQOBJWMKkBg=,tag:oqYfz0gUWqufZVeuU75EaA==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:FXuSS3ze42rWBQ==,iv:Opm+Q2pph5Hj2sptPJjQ90rcuSgmrfk1cX8+3+npuBE=,tag:RE9E7fKymySeQWoat5eoBA==,type:str]
sops:
    age:
        - recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNlM5aU8zNmZLcWFKM1Z2
            WTRLL3RhRllzc3BEakNnakYrUkVGcHdCL2xZCmdWeWRtNHZlQzZpRDhMa3JlY1hL
            dDEzUzhkaXdJdlRaR3ROUmFsaEdPN3MKLS0tIGpKNldob25USTZTTVVUcThNL3RR
            MlAxQXZIcWxsU0ViWEdyTElBTVF5enMKx8bBw8vLdEEOTcqZFm6OPypnSXkpTlJe
            By4KgUCeFrBxRiLXIVArkLfz5vbopHcJJsOl3qSd/UPtt3n1v/EhGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T03:09:23Z"
    mac: ENC[AES256_GCM,data:PzBT+Ozhq3pMR7YPHPf6q3m0K+FhetyrnNOiZdZ5FM33ojqNFPh1AUIWdilImw2BHKx23e+A29LcuQxIy9oRLpG/94Ir6v3WbZyWn1Ycsp9ploPbukuFLmEJnk3klgwQvHyA4x+sNeClciYcNB4lyKOdy5JXC6uUMRJiYRkV6MI=,iv:jsL7sHcinMiSpOgUzV412wxx1bRR44TYKupH5bmHVMQ=,tag:VCeZUvEJGyiTaqhsqjfsNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
