apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
type: Opaque
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:py4wnujCzz/tqHO/g/MMIP/IeckdtvhIi6p7rmyG9Nc=,iv:zIOEyULIL3KdU9RYiO94SlZYexJXn/2oeFy/GqGg6lo=,tag:WY+EVdRcvpIKz/UNTfvEhQ==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:WJsQBlKPSsuKSxmS3imP/amP4h61BOx1n0gzmv2vIKE3W04sb2nt1HDxxA/vrGYi7Egyax8=,iv:sYhLEDaEffgEOxQiHEOWviG9E3Elf94nIj0PwAkfd+M=,tag:fn4bSzu5iG2pXOljIz+tZA==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:UpQkel1nsCy/aQ==,iv:qBjh/avYOSER61IPUFDIhN9DqYXHsIRPCjHD3QzOwYA=,tag:a5GVM9wY3Zu+rX3EZ+Q8Vg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWTVCUFlJcnVKOGhvOVFh
            ZDRnUVAxKzQvVDhrb2hoRVlVS2NRcE9tUVR3CmlTRnErZlZpNmVmNTUvSTFCWE9z
            czVLR1lHRDV2RVVtcU1mckVYdFViTjQKLS0tIGRVZWpHNEo2VzI4QTJOY09OQVhE
            MFJvaEJ4cWd6SHFCc2dKZXpvdFlreTQKGNVtHIfgHxA8yj+hHCNZnYJ2XPrJCpyT
            RJ86AfyXwLCUol4ranzEHoTHrZp5+Ht1c2vXGm6o5WBOrpZaXeE6yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T03:38:18Z"
    mac: ENC[AES256_GCM,data:xFqOn1wJCFx+VZ82JINHyKuz515O+pmZK/Rv3OZkA+Sq4iffNO323KA3O9OvAtAC0H37yxY7kqpY7TFO2zWc/ELnC8JXlvscI2zGdh3AbcfDQS19kuFcWtmsd+uhuU0EjuDiSwtlag2A7h07Me9Ionq6yjRAx+DgQBHSNrvI5Oc=,iv:nZf2HE1QY7RIjylQJlx38VZttmXypEfMjZWxexP+4wE=,tag:y+/Z+cAETcjmXQvbTIXXpA==,type:str]
    version: 3.13.1
