apiVersion: ENC[AES256_GCM,data:qfo=,iv:2EldYSNpe8ln3l13jApNL+YjUhOCfp5nAdr5we+xuyk=,tag:sjKqmd6Pb7bG+eHMd3/c2w==,type:str]
kind: ENC[AES256_GCM,data:DZqyD13U,iv:m1S3yYFXQAe6K6Y43veRw7zdlJEUvrCRtbTf0nBrMAo=,tag:IQjdLuocMnKbAN+rV7d+vg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ky319V8cgKchwBViHiA=,iv:bYfBQuX5Pehup2UWoFnh9HfBhC4QNHtgXvVJfAhWSxQ=,tag:tEt/4byfXpQ8uH1XTjlOcA==,type:str]
    #ENC[AES256_GCM,data:z6b0i4NY0bCOXIxuTg==,iv:HvOfPEnngwSoudXuMyLDncjdsIDNDtxnKcTbORIpPGk=,tag:EUC7sakDjqvDqGH26qUvbQ==,type:comment]
    #ENC[AES256_GCM,data:ZhJ49K2ADBaLG7C4ipoKNYHXTAndP3seipbQmE0ow80ELwOXxfQT7lQ=,iv:N5DxDtauQTepPb+wvwISHsy2f1OHlFNIddQs+XcNeHs=,tag:oEtFdNX1/Cck/i0JBJanqg==,type:comment]
type: ENC[AES256_GCM,data:2QOq07jq,iv:LM9+oN24QKyv18KhIXxganpiRy/2TKY1L2h+8RS5rfY=,tag:WBEEfs3gtG4pGtyxvCE6+Q==,type:str]
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:iQNEIsUO/xm9b5tiBxqqd9gmsqbm816VWK7SyOTt2xg=,iv:GH4pGPeMsllslSGUK28WgP46MqTUSNK6EkrvowvodPY=,tag:updkr79oSlQMI4FIjOJIqw==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:g16Ar26tBKlm0LqooaKRuwvlnTEpB1qWDzP038MCBNjUkzJjd4KzcqO9qNRzZLZ1vL9pfRk=,iv:vWqCh3IEeg/SeIPUgLSpejE6Jl0t25BX9T8SA7E1RD8=,tag:6P859Co7CLUfeGHYR5Y6ww==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:fWOJEDw8zfn1rA==,iv:dzJjzQzWWFXt2PUT8kbdLf0dWiH83Az9My2WLE01eFM=,tag:NzrTezF+UoNJUutrRNnyoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWEdRVGtPaWhzQ1RLcDRz
            U1pyb2orWGZaZWUyM2hXLzVrUkh4NU9xQ2dzCnFTQUd3M2tGNnk1UGwwMzBjdHNt
            VFhtUmk0RWZjL1FPUVh3bk1hSDM3T1UKLS0tIGVORDVMUEF3VFJGZTFXTlBIdm1h
            TkFtRFA1dmJtOEQyVkVYdVdzaFhSSG8KEGibrfZUsOLNScqVHCl/3SA5tSvhuWEs
            fHJ/iVKSqcCcCagqMn6z3nOd168ioPTCtX5Om0btk3qDq4tITWw9Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    lastmodified: "2026-05-26T02:58:58Z"
    mac: ENC[AES256_GCM,data:oCE/wg+CYUhCYz5NgXul1QJ6vn6y+Jxy/OdkhA9HcF58VbV/UVaq2I3m0Zumk3VkbCwxf1FiWmIHGSRSlR+4PS0dn+gzCq6LpySkF7HJYw+cBD40yyjLVbn305hFLRIbPwfpfwSOqXWC9DtuSqzHl1jczDMtz4SilQS0eMjVtWE=,iv:WDHQ5WqnyXwE5QMAPNitZN53sJyOQJ8FG1VoGpork7A=,tag:tne752tjZf/3f38hP0GqSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
