apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generate
  namespace: generate
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/generate
      sourceRef:
        kind: GitRepository
        name: generate
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    azureAd:
      domain: yourdomain.com
      tenantId: your-tenant-id
      clientId: your-client-id
    ingress:
      host: generate.theblacklodge.dev
    mssql:
      storage:
        className: longhorn
        size: 20Gi
