nameOverride: ""
fullnameOverride: "generate"

image:
  web:
    repository: ciididea/generate-web
    tag: "13.1"
    pullPolicy: IfNotPresent
  background:
    repository: ciididea/generate-background
    tag: "13.1"
    pullPolicy: IfNotPresent

app:
  userStoreType: OAUTH
  environment: production
  provisionJobs: false
  forwardedHeaders: true

azureAd:
  instance: "https://login.microsoftonline.com/"
  domain: ""
  tenantId: ""
  clientId: ""
  clientSecret:
    enabled: false
    secretKey: GENERATE_AAD_CLIENT_SECRET

database:
  host: generate-mssql
  port: 1433
  user: sa
  encrypt: true
  trustServerCertificate: true
  passwordSecretKey: GENERATE_DB_PASSWORD
  names:
    app: Generate
    ods: ODS
    staging: Staging
    rds: RDS

mssql:
  enabled: true
  image: mcr.microsoft.com/mssql/server:2022-latest
  pid: Developer
  storage:
    className: longhorn
    size: 20Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 4Gi

initDatabases:
  enabled: true
  image: mcr.microsoft.com/mssql-tools18:latest

secret:
  create: false
  values: {}


  valuesFrom:
    - kind: Secret
      name: authentik
      valuesKey: secret_key
      targetPath: authentik.secret_key

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  remoteKeys:
    dbPassword: GENERATE_DB_PASSWORD
    aadClientSecret: GENERATE_AAD_CLIENT_SECRET

web:
  replicas: 1
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

background:
  replicas: 1
  service:
    enabled: true
    port: 80
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

ingress:
  enabled: true
  className: nginx
  host: generate.theblacklodge.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: generate-tls
