apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: semaphore

resources:
  - ./ingressroute.yaml
  - ./namespace.yaml

helmCharts:
  - name: semaphore
    repo: https://semaphoreui.github.io/charts
    version: 16.2.2
    releaseName: semaphoreui
    namespace: semaphore
    valuesFile: values.yaml
    kubeVersion: v1.36.1

patches:
  - target:
      kind: (ServiceAccount|Role|RoleBinding|ConfigMap|Secret|Service|Deployment|DaemonSet|StatefulSet|Job|PersistentVolumeClaim|PodDisruptionBudget|NetworkPolicy|HorizontalPodAutoscaler)
    patch: |
      - op: add
        path: /metadata/namespace
        value: dagster
