apiVersion: v1
kind: Secret
metadata:
    name: semaphore
stringData:
    client_id: ENC[AES256_GCM,data:jHlrQ/Pe9ipneC3QivXNous2x4NSxfgVOBWMQKO89X48iwdhQUGMxQ==,iv:OixLieHTYIZMnFf011MRVfD66vwomJxhwxEiRPgcJdw=,tag:IFuvxFgJ+LwTjlXFTAQtyQ==,type:str]
    client_secret: ENC[AES256_GCM,data:fhO188nuGyZim66BVfYERtWi5zNh2+PAq0pXgUPF71kdMx+7zxS++t30pQBlm3YvWQ0DbmDmuU7pPBvSh2NDZl3b5nTLtbZeez8CIyuXoWUl0j/XCHBarLTGWRzozshQHHj+lgsBEzcO1xOaKgyZhxDsCkLE8NxyAmgJ9Y5RGK8=,iv:wbZAEKPADU8rmA7RUUSqwdJvJw0VMvug1lRTAJtQ+3w=,tag:ltBa1BSkAN4abrSR+KJn/A==,type:str]
    admin_username: ENC[AES256_GCM,data:HcynwOk=,iv:x1su4Dv56s0kZOV0DePe8JLjspzGDcWkK8LBCWopDAg=,tag:slFK93T0Sz69B98VVZqJrw==,type:str]
    admin_full_name: ENC[AES256_GCM,data:CV7QhB9wEF5fR/tS,iv:Oc7sR2HjbO+0+F2otDbPc7J9+/OHKKhBniW/LXhC0LY=,tag:vjFQkVnqECdkg/cTzD++hw==,type:str]
    admin_password: ENC[AES256_GCM,data:rJhjO2vpe5XbDm8foDbpSWI91lelmNJaD1JQokyirG43lm7KzMeNDSyH6Vc=,iv:XXHFI9U9lWd47t6gDbwVeo5hZeto4R/yp2iIvOao6oA=,tag:v+QEDMLSbMO5ToewkxB6kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWVo5cWwxYlhDd2JrZFVk
            bU0rSmxvL09qRDR4ektNUC9Vam5oZnk5c1ZZClFxRVJleS8xN0s0UjlVYXlRcXFJ
            OFVSYzBvVzFPNE9pUERrMVBnTk9iMjAKLS0tIERkKzZvRWtYRHM2NmoyRkg3dmJx
            NTNKNmwzSWR3STFYdlJ4WWo2VnE2YUEKID38nz2fWIdrLR//Jg5X5iBLYROOmGOn
            JqXjRCCviUQtmoiM6Dx4SmBDjDaTJ4aszfxiNDaUlShqmTPMXrjoiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-11T03:33:17Z"
    mac: ENC[AES256_GCM,data:8Zk/C8PjyY7RjJ8KgTxrdor+usbOSGzKdB/O6TvscDLKfm83puDg5PHYufR0ppeJ3K3X98gpWfvGOPzodziqXUcZAd+m7ixQfyFBR+5hFsy7YP7zkhTb9/VhFks2yRPn3IDVBBJw1hPOXtmMoxYxI0b0wNLUXLT9qNsKavZygQw=,iv:Bt7ipBhTdG9pOQte6sTAdyKjL8XIsLURj550ULmJdAI=,tag:e9xB+wMyZg/S9UmzzVuP5A==,type:str]
    version: 3.13.1
