apiVersion: v1
kind: Secret
metadata:
    name: semaphore
stringData:
    client_id: ENC[AES256_GCM,data:wA1Lim5LSfQKuR3cC+gFNQT35w0jIRArT1oBWAAAvRO4CkIbA8y5fg==,iv:AVwOzNAjiVzzTFSTRCVhDhv3Q6PI2KW5Vq9QWPCxu6g=,tag:Lo3H85e56MYYVXVEdIq4tw==,type:str]
    client_secret: ENC[AES256_GCM,data:yVLysQL+HKh1VZouP9O88JiE1N4n+YXkRVlqif49hYIObOlaQmoE5RowW0hvBKSSdW0/nWYq/kRJY0KCtPJEHDoIgDy53mdiSG+d0Y7sYbM7j0mjLgbg8VDXszOa/CyqIKMUSFn8TVRblL86RK0eoMrHIx3wecXkmbIO5/olvPU=,iv:WydWiOZ9NZ/5USkofaLL+nLr4gFC8XbWw+oL9NV1cwU=,tag:koDYv10rHDDfTJXGaDgP5Q==,type:str]
    admin_username: ENC[AES256_GCM,data:BoJDMk4=,iv:26O8IbJ9Og1e2mevMGmff4/8m1P9PjN71/th54OBQrI=,tag:LOx+zrqJxF+sn/DU3xNFRQ==,type:str]
    admin_full_name: ENC[AES256_GCM,data:LKRPRilmf/g/YCCs,iv:JmklPWVytYcf6Q/lHQuGj64CyIMzG6jXvCAsoLtwPwM=,tag:8hCKLfrK5h1yEnz7GdUGDQ==,type:str]
    admin_password: ENC[AES256_GCM,data:9Hfp84Y0+9Bw7PwLKHz8SoZYmBrRnidYCqyT7zFsr2GDv3aFAkN2G2E5CrA=,iv:FPUhq+rMi3wpLMjayahHh8Eb5L5unEyB5QcKsuv6zGk=,tag:zncmYDuRCUa5YVfRdjXFvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVGc1UXh3VlZLSTUrVlA2
            dFdOK0EzT0RkaWRnOWZQOVViUnlGNCs3a0hRCkUvaWM3QnJHaktCa2V2NStpczJJ
            ZnV5UHRJV2tRTkFOTnR4Um9uOXhHUFUKLS0tIDJsWk9rZ1UzMlNBYjArd2dqWjUx
            dStPdEdOdjE4Q0RldGd1UmF5aGV4QWMKjMg2HZphpCGzhQjOWtrJArwk5qAwBynt
            5O1sOcL5oNoh891YAVz/h70kc3VdP5c8E8WZ1qbNQ1sAggqnch4cbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-11T03:19:40Z"
    mac: ENC[AES256_GCM,data:TJa//K6/o/smUtEvVZaIYTocC+B4+lMRtqC+FhuhTmTw7Zxl121H4m8NBoBRZh13Vlh5mSFJ2kBYph/4voIk/p1ZGTF0zWkg7j3i0wYP4yzjix8old7syIVY3CtZqNKbnPrv7CJyx3QsAcgwuYFz6HlNEViTJtdnd7WIHWq0/xI=,iv:sCjDo4wIUbSqRpysASwkL4WuHaQXxUwSeLH82aaXZ4Q=,tag:uI0soDBZzF8lU+F5JU1YiQ==,type:str]
    version: 3.13.1
