apiVersion: v1
kind: Secret
metadata:
    name: semaphore
stringData:
    client_id: ENC[AES256_GCM,data:zgTK6ghBECyKSJR+fcACHiUfyCTWeo1HyJdlzGYPaVi4KqQ705Bkew==,iv:A4U8h4yu0muVzJp1UxEmagPIBnnaVquzMsHi598eLeM=,tag:PtImoQT2OaGu4LXo3Nh5BQ==,type:str]
    client_secret: ENC[AES256_GCM,data:b8pQK55FLIOdlGqHJshWKZFIzV2h4z6SOGo123suZRFvuz4/PpIlp+cM9/XZxF+KW2kRHx7rh2ziKoHp9uQhgQFaL7uwEu5FJoL4zpT6Lpxn5Mlz3oC0wsjGzqkDcNCYopmHLrwNjSk6G/sNy6fH2OxrXRGsNPafCWU4x0mzpF4=,iv:e2ejK7NxO0mRzEdP6IM0SH5BPy9macHGepclpDeUsOM=,tag:VndCcQUmgMvFFuHMrD80ag==,type:str]
    admin_username: ENC[AES256_GCM,data:Mb3Mn6U=,iv:Y5txiSySF/F0N0IPVzfjrR5as8Oy4qzMO1QolHjg64k=,tag:c4p1TAmcsCm3YuiV/IjUkA==,type:str]
    admin_full_name: ENC[AES256_GCM,data:wT9aRKn/quf+2D8y,iv:z0rTzfu8rmmqmMcvnynxcGpCKXqd1QrWWUIrQtzecT8=,tag:qOe2Im/Vy+X+z/gDkiLBUg==,type:str]
    admin_password: ENC[AES256_GCM,data:cVfqhUvOos4K9ZpMrb97vziWoOcgKn+LWO3/OqgxLB2hMeucoTYIEe4S8+M=,iv:wJwIJ/XfGLlHparFHse4rHbxEqkMRCsg80PYyI/EqXw=,tag:yVplabZ0UeT1IBbIWioBHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeXU2ZXIwQ0U3UHJud0xu
            aWYyUUY5VTF4U1NMa3JGajNVNVp3bG40QUdnCjFPL1BjS2JRTTFiQURkWHVNUExF
            ZjMrTG1LSXRUcWg2OUxkQjJ2VXdFZEkKLS0tIG4xbFdGczExbFREd05wSy9kc0wx
            NTk3MC9SZitwM0pUSVZENnlHVzBuY1EKhMNwNrABSKxdNj3+t45pUJc8eMJY7aa+
            ElF2C2bXSnaFXoYY+9/3yF8mVJ2M035ewTLSh549upC0DrJYdi8x/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-11T03:06:18Z"
    mac: ENC[AES256_GCM,data:hYQiKudI/yT3sBU1dXG3zDtHO4bov2LE/A9x/Puh/jomtsywBH1DNcj3Khzxph8CwBMdtm0TGy+9dGWBbGBxm9ZAudwvIvwa+ix69WMZV2ACOmPXohuYjcoZJA/87/GKd4AhEohlUCJ+NcqLI3KMDgtiocAD1z2tqy5XfVv+PnU=,iv:oep/muRrxYf4/Ok6KjHbKbcKOFmd87hut+SY0K+7Lcc=,tag:QCuQUkfvCkfzAEm/6DFr9A==,type:str]
    version: 3.13.1
