- name: Install open-iscsi
  become: true
  ansible.builtin.package:
    name: open-iscsi
    state: present

- name: Install nfs-utils
  become: true
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Install cryptsetup
  become: true
  ansible.builtin.package:
    name: cryptsetup
    state: present

- name: Install device-mapper
  become: true
  ansible.builtin.package:
    name: device-mapper
    state: present

- name: configure rshared root mount propagation for longhorn
  copy:
    dest: /etc/local.d/rshared-root.start
    mode: '0755'
    content: |
      #!/bin/sh
      mount --make-rshared /

- name: enable local service for rshared script
  service:
    name: local
    enabled: true

- name: apply rshared propagation to current session
  command: mount --make-rshared /
  changed_when: false
