- name: Preflight checks
  ansible.builtin.import_tasks:
    file: preflight.yml
- name: Install packages
  ansible.builtin.import_tasks:
    file: packages.yml
- name: Install scripts
  ansible.builtin.include_tasks: install_scripts.yml
  loop: "{{ install_scripts }}"
  loop_control:
    loop_var: install_script

- name: Longhorn preflight checks
  ansible.builtin.command: /tmp/longhornctl check preflight
  become: true
- name: Apply Traefik CRDs
  kubernetes.core.k8s:
    state: present
    src: "{{ traefik_crd_url }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
