# Prints all commands when running `just`
default:
    @just --list

# Runs a Packer build, taking `os` as a parameter
build os:
    packer build \
    -var-file=proxmox/{{ os }}.pkrvars.hcl \
    -var-file=shared/secrets.pkrvars.hcl \
    proxmox/
