# Prints all commands when running `just`
default:
    @just --list

# Runs a Packer build, taking `os` as a parameter
build os:
    cd {{ os }} && \
    sops exec-env {{ justfile_directory() }}/secret.yaml \
    'packer build .'
