- name: Install packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Install scripts
  ansible.builtin.include_tasks: install_scripts.yml
  loop: "{{ install_scripts }}"
  loop_control:
    loop_var: install_script

- name: Prepare kubernetes tools
  ansible.builtin.include_tasks:
    file: kubernetes.yml

- name: Configure firewall
  ansible.builtin.include_tasks:
    file: firewall.yml

#- name: Update fstab
#  ansible.builtin.include_tasks:
#    file: fstab.yml
