#### docker

- name: Install docker packages
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: enable and start docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: add user to docker group
  ansible.builtin.user:
    name: "austin"
    groups: docker
    append: true

- name: use default docker context
  command: docker context use default


#### kustomize

- name: check if kustomize is installed
  command: which kustomize
  register: kustomize_installed
  failed_when: false
  changed_when: false

- name: download kustomize cli
  get_url: 
    url: https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
    dest: /tmp/kustomize_install.sh
    mode: "0755"
  when: kustomize_installed.rc != 0

- name: Install kustomize
  script: /tmp/kustomize_install.sh
  when: kustomize_installed.rc != 0

#### ksops

- name: check if ksops is installed
  command: which ksops
  register: ksops_installed
  failed_when: false
  changed_when: false

- name: download ksops cli
  get_url: 
    url: https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh
    dest: /tmp/ksops_install.sh
    mode: "0755"
  when: ksops_installed.rc != 0

- name: Install ksops
  become: true
  script: /tmp/ksops_install.sh
  when: ksops_installed.rc != 0

#### k3d

- name: check if k3d is installed
  command: which k3d
  register: k3d_installed
  failed_when: false
  changed_when: false

- name: download k3d
  get_url: 
    url: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
    dest: /tmp/k3d_install.sh
    mode: "0755"
  when: k3d_installed.rc != 0 # rc is return code
  
- name: install k3d
  script: /tmp/k3d_install.sh
  when: k3d_installed.rc != 0

- name: check if k3d cluster exists
  ansible.builtin.command: k3d cluster get local-machine-cluster
  register: k3d_cluster_exists
  failed_when: false
  changed_when: false

- name: copy k3d config
  copy: 
    src: k3d_config.yaml # In files folder, sibling of tasks
    dest: "/home/{{ vault_workstation_user }}/tmp/k3d_config.yaml"
  when: k3d_cluster_exists.rc != 0

- name: configure k3d
  command: k3d cluster create --config "/home/{{ vault_workstation_user }}/tmp/k3d_config.yaml"
  when: k3d_cluster_exists.rc != 0

- name: start cluster
  command: k3d cluster start local-machine-cluster

#### flux

- name: check if flux is installed
  command: which flux
  register: flux_installed
  failed_when: false
  changed_when: false

- name: download flux cli
  get_url: 
    url: https://fluxcd.io/install.sh
    dest: /tmp/flux_install.sh
    mode: "0755"
  when: flux_installed.rc != 0

- name: Install flux
  script: /tmp/flux_install.sh
  when: flux_installed.rc != 0