apiVersion: v1
kind: Secret
metadata:
    name: kasm-brave
type: Opaque
stringData:
    vnc_password: ENC[AES256_GCM,data:aZJvEaMFYe9nwitfxKuLTY6B6x8sJA4kLNAYY9VeQlCzj7901KQQ,iv:dUgvVRpDcFKvhmIcet3sDo60LvtYYbqjh3aI934HiTA=,tag:tMQr0wJeqxck67cqGzDVEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eXA1WUxZY3BBSTBVYTVS
            cVNOc0xTblVHWTd1S0Y5NlNpNXhaSkorTkE4ClBVRWxuSmtKWVl4elJXTnhXWU1j
            NFhnR2V5TUs4TUwwaTd6ajdXM05xYTQKLS0tIDVvNmtmaFVWeWhMVjBSZzYrZ2Fv
            K3FUeGw4c0J2OUZkTjM5Nk1jWXlveHMKeanimeAYHXqqSy9ShdtyPGlyvNovPoDG
            xv82V7zCq7EbEcVOMheLxpE/IbhzJTwJcfrHhvziS6VBWcLvQENKUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-12T01:52:54Z"
    mac: ENC[AES256_GCM,data:Ptpyi3EzkpjPw1WXDWSbn6fjVnGOWfHxm+nFKuCXV4QgCY3kjcDsdPZqHT3cLtPBOk0P4NH9bqf0iVbuGpnmHboLxiRFoRsPWFwNFCL+LcRyJy+n4OOO5w0b8sZDhscEb4ig9PTIQbViekxVi/8DoKAD0P80/V1xuyeScXQ59c0=,iv:Wenf/6Bqv3aBUBhd5ngfeN+bJNID3R0Zl2aPWu0ircw=,tag:gHDv25NTi5nrMMNu8C9mPQ==,type:str]
    version: 3.13.1
