apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart: pgadmin4
      version: 1.62.0
      sourceRef:
        kind: HelmRepository
        name: pgadmin4
  valuesFrom:
    - kind: Secret
      name: pgadmin-pgpass
      valuesKey: pgadmin_password
      targetPath: env.password
  values:
    serverDefinitions:
      enabled: true
      resourceType: ConfigMap
      existingConfigmap: "pgadmin4"
    env:
      email: austindsmith@proton.me
      pgpassfile: /pgadmin4/pgpass/file.pgpass
    envVarsFromSecrets: [pgadmin-oauth, pgadmin-env]
    extraSecretMounts:
      - name: pgpass
        secret: pgadmin-pgpass
        mountPath: "/pgadmin4/pgpass/file.pgpass"
        subPath: pgpassfile
        defaultMode: "0600"
        readOnly: true
  servers:
#  firstServer:
#    Name: "Minimally Defined Server"
#    Group: "Servers"
#    Username: "postgres"
#    Host: "{{ .Values.example.host }}"
#    Port: "{{ .Values.example.port }}"
#    SSLMode: "prefer"
#    MaintenanceDB: "postgres"
