apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart: pgadmin4
      version: 1.62.0
      sourceRef:
        kind: HelmRepository
        name: pgadmin4
  values:
    env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: admin@local.home
      - name: PGADMIN_DEFAULT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pgadmin-admin
            key: password
      - name: PGADMIN_SERVER_JSON_FILE
        value: /pgadmin4/servers.json
    extraConfigmapMounts:
      - name: servers-config
        configMap: pgadmin-servers
        mountPath: /pgadmin4/servers.json
        subPath: servers.json
        readOnly: true
    extraSecretMounts:
      - name: pgpass
        secret: pgadmin-pgpass
        mountPath: /pgpassfile
        subPath: pgpassfile
        defaultMode: "0600"
        readOnly: true
