apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-pgpass
    namespace: pgadmin4
type: Opaque
stringData:
    pgpassfile: ENC[AES256_GCM,data:1Xsq8ptc9lYnp7m/lV4LHqU8RawArKri+ctKuizKnIWNOaQFVq6Y6Ov44Yx9L7SNk7Cz9X3Ijp0wvnoyHZb8ncHUPOPVSWFyc+DMrcU1ICrZQbxlv2bat5C8g1iuQnf8VzeBpK5HrOzUw8WjLIGLyVD3PPBN,iv:kHq9qWLw6tgpIi/s1NzgpOh9MfDvFkHBXVeA1G5nGZc=,tag:JV5bREYGb833S5XARecXsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a1NhVjdPWVh0Q0RESEEw
            dHhqTm9aUUZoQUNRZk1JaE9OL0hybll4UEI4CnFDZkx3bksxMmtvUmxoR0NkWVZP
            YlJKWlROS1IvNXRMeWwxRmVBL3VMekUKLS0tIHN6MzB1R3VCY2gyTlBLNkI5UU15
            UFFiejUycVhVUjR4bFRKdXZsNEExbDgKguvbp9asHet0O2WRAH+Lsa6Eeu+NwXw4
            asi/n885BKgerW0A69HbDbq/AP0dgrT9rYTsSZwLl4aNwDw4vNcWrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T05:03:53Z"
    mac: ENC[AES256_GCM,data:1cukHvSN0lxoA502rVlhM8XHX0Gcm8Rpur70h8GwBxnkpxPszZK80920nCrxhRy8ZbyCq55dYEavIe81yM9gd7luaBKgh5xNN4nrP+inMzSLyccvOb4ef+d4407aW4s/NflBhMLXIJL04dUd6Yx4tW3MLYWShBA6RqSZIUNEcQ8=,iv:swdu88UwPXFJ80LOugOYbsAlee3KQ/cBpDtY+/W4UGk=,tag:yZHPHG+YwjPRWmnIZMngdQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-oauth
    namespace: pgadmin4
type: Opaque
stringData:
    PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:ChktXrCz6EdgzCalTy+bQvKcW1dc5Q==,iv:Jb2ec0wEZ+r6fBuzSDFWnWZ48/KWEBHBsj6ib41NQF4=,tag:MMe6KVa2nzdSNS08EeN16A==,type:str]
    PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: ENC[AES256_GCM,data:WPoIRQ==,iv:MQQqsCmsYBlGnj0VpSFjK55j1oi8fLw78zqYeL6ePpU=,tag:URskANRIR5OJR0tVRgdtTg==,type:str]
    PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:UMfc1J27nN/SH5Z1nJpRTqf6kYYXxAUciMMFTND/DQ7ZJ7EBWbB0XJNq4ECJDgM3qWEHFZRbEdlvfe0qbPdsNUZtanwiSMi5+m2cEFrEpkUUisH/twBqadwr84rT+Jj8jNBRLOu//Qi3dFCHF5nC2lpnObbA+PPJuhnLdwsy0sc8h4uOYI2gtY4s14+OK01cfymhnrGS/bKdOjsbXxgCqZflHA4dNKWlOeKeUl/8SYYh249h0cjGJvFqZRnq5Ncotw/5Aa1Oh3QBOCM5TYW0rSsnbjIUHJbFi5aMpcWGGyPXT4JL1h7SX7hDrtJv8pf9dTtLmPixBZipmozfHLnxkHOWfl5yD5FKIudZmaDk242Tygv5S1BcFb+eRVOJqmJJqJWlYCsZP3Zykpw09Y7Ck6SmzGLCK/BcsH+Dyu4pLB02FDc7DHptdCM8/aT1n6Oz+7/FErSRtMsU8jXHBctkpacRlG9mhGBv6Jf6GD55wsHlSQFh3CBtKDiI4GlVY21A+rKyXTwOxcu7kZ6gHJ+5KrNy8jKD3wR9KsJ0GideI1MkH4OA7E6m5Egwhx1IDrLD8mcmiyMgucHpSbRciOb+t7eNvknT6cnCErwQ55+2sX66Yb0jUZ5h5S8nf/ZDxYfpLF/NpQDDoYlJmYlbgwHGwJl4iudDQ6PE9C+bV0g+EPPBasPirp6lierlrFG341cJM0LshuyjGJSvwP2dAak4a1TrZlcvwRYQI7uYt/1HdmMGs9KeWoNPDumeVMNDIvRN1nkWtySuWyKmZJynbDtFa/meLdgXZccdbAie9K7i2rzqXDYUGknYiqO9KtMr2B/05ShVyPTWZ9P8UTwBFedvkIi6ZS3qD3RJ8ubGGHpwwC4ExTjPmz6T774xIQQ9NAGb0B3aak8Qr5utvmDx77uOZWEOw2s2x2kIlZDuUjWIClKAlHkzQorJc3sYETNNgE5WKvRYgEt0fzPFrt+u53FgSrwjRWW1uVmjmXQ3kdoAUHZTCmynI8G5z6JinRs6uleXr8yPmqxzyxAFwO49Z3WA0W/oh+7iNeR5rAX5PPIXkBhYBwP2mDU/RYPk6+QXpe2s4gZQ,iv:gGl0czLaXy2EQKz10Sdf2cxSvDp+PNtR5fAu9ZNwNNw=,tag:WecGrBK4Oy2UwIOyZE3pdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a1NhVjdPWVh0Q0RESEEw
            dHhqTm9aUUZoQUNRZk1JaE9OL0hybll4UEI4CnFDZkx3bksxMmtvUmxoR0NkWVZP
            YlJKWlROS1IvNXRMeWwxRmVBL3VMekUKLS0tIHN6MzB1R3VCY2gyTlBLNkI5UU15
            UFFiejUycVhVUjR4bFRKdXZsNEExbDgKguvbp9asHet0O2WRAH+Lsa6Eeu+NwXw4
            asi/n885BKgerW0A69HbDbq/AP0dgrT9rYTsSZwLl4aNwDw4vNcWrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T05:03:53Z"
    mac: ENC[AES256_GCM,data:1cukHvSN0lxoA502rVlhM8XHX0Gcm8Rpur70h8GwBxnkpxPszZK80920nCrxhRy8ZbyCq55dYEavIe81yM9gd7luaBKgh5xNN4nrP+inMzSLyccvOb4ef+d4407aW4s/NflBhMLXIJL04dUd6Yx4tW3MLYWShBA6RqSZIUNEcQ8=,iv:swdu88UwPXFJ80LOugOYbsAlee3KQ/cBpDtY+/W4UGk=,tag:yZHPHG+YwjPRWmnIZMngdQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-env
    namespace: pgadmin4
type: Opaque
stringData:
    PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:xCLSFYU=,iv:n0MV21JrwljvEL/hJ9NHjcfwiABO+Qo+7DgavWMzVSU=,tag:38wq2jnT/Br91yY4WYYVjQ==,type:str]
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:UcV7tSBFlPtmhyizTl5WtY6+WdJong==,iv:yfC/7eWIYagZlHHF50BvtS6NenHMNCECZntWeU5hqRI=,tag:qCNGMvf0Vi8UU0HFVraPyA==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:4uBvQ4I0aRE=,iv:4Mz8k/utfdxDM09G9EieTCOmUaVe6QpmXetkqbZ7l04=,tag:S4e0e8cjNAasGeGmSO7m+Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KR8CJuuHHzUoitjynvt2SJ/2lcwyHbiVKLfGk3nNntIH62cX5UZJDxF30LGynElC1+Q=,iv:jm5E+ue3NZT3PgwtVv2Zb3LLYdY42MF+rVbHNUSEYPg=,tag:8lerrKEABfHag8oqg7LoPQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:085h7R3HVKelvlbRU5tlUI0+gVxBAtVOipBnjSD23tH8FuH2tMep44nzBQ==,iv:kuog8gJU1r1jD0VEvyBIKf+3CJYhM+o4AM9vMqR5d1E=,tag:hIE7SRSrXoKisHNjBz6czw==,type:str]
    PGADMIN_SERVER_JSON_FILE: ENC[AES256_GCM,data:ryPSqZUkRrQiJc7K92P7O996I5zzTg==,iv:KrYfr4a4+G9oMHUWaTF0wyfscxXPr+cqbcwJj2kKybA=,tag:c4zwRLpCdS1xNco19eaEhg==,type:str]
    PGADMIN_REPLACE_SERVERS_ON_STARTUP: ENC[AES256_GCM,data:mxKS9Q==,iv:gvWBtCeGoH8oQhNx4Fro3J3mJ6D8rKJ1+Q+jMy0Rlkc=,tag:XkmD3Ikt8mnlllKGBfwtTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a1NhVjdPWVh0Q0RESEEw
            dHhqTm9aUUZoQUNRZk1JaE9OL0hybll4UEI4CnFDZkx3bksxMmtvUmxoR0NkWVZP
            YlJKWlROS1IvNXRMeWwxRmVBL3VMekUKLS0tIHN6MzB1R3VCY2gyTlBLNkI5UU15
            UFFiejUycVhVUjR4bFRKdXZsNEExbDgKguvbp9asHet0O2WRAH+Lsa6Eeu+NwXw4
            asi/n885BKgerW0A69HbDbq/AP0dgrT9rYTsSZwLl4aNwDw4vNcWrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T05:03:53Z"
    mac: ENC[AES256_GCM,data:1cukHvSN0lxoA502rVlhM8XHX0Gcm8Rpur70h8GwBxnkpxPszZK80920nCrxhRy8ZbyCq55dYEavIe81yM9gd7luaBKgh5xNN4nrP+inMzSLyccvOb4ef+d4407aW4s/NflBhMLXIJL04dUd6Yx4tW3MLYWShBA6RqSZIUNEcQ8=,iv:swdu88UwPXFJ80LOugOYbsAlee3KQ/cBpDtY+/W4UGk=,tag:yZHPHG+YwjPRWmnIZMngdQ==,type:str]
    version: 3.13.1
