apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-pgpass
    namespace: cloudnative-pg
type: Opaque
stringData:
    pgpassfile: ENC[AES256_GCM,data:Fs/D/K5oRrZ+DO7ryThBjBrir7E58nISINwHybPSeqyO2ItznmkppImnJpaUG3PtUcY3gzc/aZLcfFkO1F+J62wUXM8ixTI7PImiVL5qSOFMdq6tPE04TIKDCOhj/DgkLCJMY+9SygQ9hk0dNnrBhepAA5UC,iv:5uAQV5R77TNERNH9Tg5VOz9dwg3yuMxz27yg/PxrpDQ=,tag:XQVigJyWROsaI7R0tLk8xg==,type:str]
    pgadmin_password: ENC[AES256_GCM,data:49e2fBhPWqvLc6ml2x5aL6hBD+ByRxFBrtAelQxpSw/nP1MtzOTGhs5n,iv:li/iBmqlajbobM+NK6hZhnbtA5zEfHfl4vqvV6dMm0w=,tag:2MuKTnJ0bsVsPxptDmkEQg==,type:str]
    postgres_password: ENC[AES256_GCM,data:dpOTyChqfCY0ZbK5RR6vcONVDJKySkgQQ/8nBBa8kYBYHuQy5YRyE/fftbaWDy9yth0=,iv:Z7FNbzHRuTT3AVvlB1XZLkgc4RfAuCveUgo0voNpVk0=,tag:w4NBOhCvUEpBfi0q0F7CuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByREtNZk91MndwcldKQjlo
            SlVvYVpSK3pnRkJBRGNqOGNuZVpOUDFjbWxzCnFFeTFnOXVtMHJNeTZKQ0hqNWJ6
            NjlPeW1INEVoTStRS0duSkJ5QStmOGMKLS0tIDR4WExHcGx4WHNlcEV2cEFpb0dk
            Y2RpUGtZODhjR2tJcWZpOGUxa0czaGcKRZTZBh3UmInwr874ELnb4GJr+DQV4rOD
            CUwyBDBjroWN8KhNY9dBJJI1o3yhRGhtJL0rRoOhikFft4sRLtu8gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T06:43:41Z"
    mac: ENC[AES256_GCM,data:mNwTn9itvaA72IeIkvKj/iqxtKdgvrVyenHtixW0f73w2ApGra63NoicHOW0YxcQvYvmei7XDWQX5b7oYv8yx5xJWTwUfCEYUm7kawuCPQS+H11Ak1Bk8r+OVervJwSVv+2SgIHqfRrvtWxXDm4EQAvuXUPuz/BIxrd+vBhkQNA=,iv:1VsfY0eclJMfdVe5FRC2Lag57r7SOGDjodWUTVtgqTA=,tag:KiS/U48oDL2zd+229X2LfQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-oauth
    namespace: cloudnative-pg
type: Opaque
stringData:
    PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:D6x3ADBSrVqIDYRClHD+S6PUkLcokg==,iv:ObxmrGfUV0QY5im2qvx2gZhNo+u/u6z8cTsZids9P7A=,tag:VmwIuCeaO7eLn5Fm05VkWA==,type:str]
    PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: ENC[AES256_GCM,data:UflYhA==,iv:qrBJDKURd6L0qluRb6YKOmlmCnBOWyG4TIKGr7Xlfak=,tag:FzgaxpKQgpxlFcc+IyU/QQ==,type:str]
    PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:qVfVl9u14WMpgRB25JR0jJyfv9HQzuLlsi6aoslQrv2kGqLD6OZXTtVF8SzcTTfFl27OKmhGj5akqpET5898D3ECFoiJWe5BIBOEaUxrVPJS0ybumWlWA97vAMgZz4BPdYmQDPunziStWdQao5ZB3Log4n8DCv06lymy1dSbYcxuQC27oTKNsx4rhYQmhNNlO4b3zIAT/Qq/2SFeNvRS0SS0a1qxsz0kN1/foz7evq381Lzzkhe8BynJNIsJH8w6pPheHl317C5m5frEGRJ1fg+MuCdQOhjoT4R34b2FWP0fxWRiiFMcAhuNShOFYvVXCHYRxIgsDctYJX4hjPfwWiYJm6dvkmpmFYlwIZ0HtIgc2mLFM54okDLEqOqwj3f/SZDC2wApIvRznljAjv/FoCl/AJCRpyvB7i0V/tdio3HQLPZT8VCvm9CHySJE85wpWue1XpaP1sBE5sGsUSsQO0xUWdI+i86SMWu/dQUkKlZSE8adxvATEAfGVQKfYVO6NfHHWii1IQa8hnoQ3/6X9IahejwJD38eMmoLK1evGRo/bY/Ytm4kvjFKN/IyTqhagzc8rqb95iRRxUz80Wj7Lxg3uVkHJvyY0bz5VIuAu9HJke7F+Lya5VgMDOQ2uBCIe1N5++WN4z+qntfNEbIoNAMqLkwTYD9YL/ik/x1uHjN7sQNNcknw/36gNIcWaLrgDCWB/ZbstSGh6xWow+mcNvY0VOXXlUUgp8O0bM5colYVcn47d3UgK/qdecPkJ71G3GqA4g8IexYAn+iFjF09uhJWb314N/A23juaNBwr0ZJnMPVMtcI1cmnJEiotuTpaRRD7/g2yIyScIvXxig+SBYqx2dqusbhTuhWanFIScGTS4j4La/h3ehT+glYyFtZ/m4BhTjz4ap8EpXrT4mBl9pn0Y84/kouGROEeyXWiKnBrt9m4sdgkK1o3AWjP7F6uw5FoVpXl22HMTfHki9qcS68fH06QluIu0LWOuy4vu2JT9UyURBL3020gteAsy/kdpCvEaQKZ5SAYhlIfyl7KhfGZbz2pRNJk1BdyMkAEX5BauoVHcKcuBSWnr5HsAZsPVOlA,iv:yBu+7zKXFSSrJRnR/cifCHOyMWE1tXaQzf/EdJGzSyQ=,tag:oiRj2cq3AaE+4D2icqrdEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByREtNZk91MndwcldKQjlo
            SlVvYVpSK3pnRkJBRGNqOGNuZVpOUDFjbWxzCnFFeTFnOXVtMHJNeTZKQ0hqNWJ6
            NjlPeW1INEVoTStRS0duSkJ5QStmOGMKLS0tIDR4WExHcGx4WHNlcEV2cEFpb0dk
            Y2RpUGtZODhjR2tJcWZpOGUxa0czaGcKRZTZBh3UmInwr874ELnb4GJr+DQV4rOD
            CUwyBDBjroWN8KhNY9dBJJI1o3yhRGhtJL0rRoOhikFft4sRLtu8gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T06:43:41Z"
    mac: ENC[AES256_GCM,data:mNwTn9itvaA72IeIkvKj/iqxtKdgvrVyenHtixW0f73w2ApGra63NoicHOW0YxcQvYvmei7XDWQX5b7oYv8yx5xJWTwUfCEYUm7kawuCPQS+H11Ak1Bk8r+OVervJwSVv+2SgIHqfRrvtWxXDm4EQAvuXUPuz/BIxrd+vBhkQNA=,iv:1VsfY0eclJMfdVe5FRC2Lag57r7SOGDjodWUTVtgqTA=,tag:KiS/U48oDL2zd+229X2LfQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-env
    namespace: cloudnative-pg
type: Opaque
stringData:
    PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:1FVEt+I=,iv:07lcmEJ79HPR8G9Ocp7Hg+rg2dk/Dp5A2GoyA9aeahs=,tag:fUVsy4lHttX+GiBcLEO4bQ==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:tjfda5KCl9o=,iv:PdQRJ7AGfE4qUgYQPAl7wvewOxSfFFXGqCjvDxMhxhY=,tag:wJ9ImQu7ZHH2Ok+TtiYk5Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:a2Apg75e3/w2nLFueBKTTNaeQF7IsEPpbhbEXPR2tEUrcsdYzAzyLR9keonUeHtuQ28=,iv:UxxTirp9nPnU0Wlq6NLCOKzOrm1GnD4hWZYIl6Ry9JU=,tag:kA2Zqgu53Kq0KVSeeVjYcg==,type:str]
    PGPASSFILE: ENC[AES256_GCM,data:uJ2oyzChIpfMMtE5tgdtXjHSKTzlX0xj76l3Mg==,iv:j26HxsR+4I5JyNixu6+cvBgdVLmvAMX8rKtgCizA6Ek=,tag:aFlwIYOcFam+5uNH3xANGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByREtNZk91MndwcldKQjlo
            SlVvYVpSK3pnRkJBRGNqOGNuZVpOUDFjbWxzCnFFeTFnOXVtMHJNeTZKQ0hqNWJ6
            NjlPeW1INEVoTStRS0duSkJ5QStmOGMKLS0tIDR4WExHcGx4WHNlcEV2cEFpb0dk
            Y2RpUGtZODhjR2tJcWZpOGUxa0czaGcKRZTZBh3UmInwr874ELnb4GJr+DQV4rOD
            CUwyBDBjroWN8KhNY9dBJJI1o3yhRGhtJL0rRoOhikFft4sRLtu8gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T06:43:41Z"
    mac: ENC[AES256_GCM,data:mNwTn9itvaA72IeIkvKj/iqxtKdgvrVyenHtixW0f73w2ApGra63NoicHOW0YxcQvYvmei7XDWQX5b7oYv8yx5xJWTwUfCEYUm7kawuCPQS+H11Ak1Bk8r+OVervJwSVv+2SgIHqfRrvtWxXDm4EQAvuXUPuz/BIxrd+vBhkQNA=,iv:1VsfY0eclJMfdVe5FRC2Lag57r7SOGDjodWUTVtgqTA=,tag:KiS/U48oDL2zd+229X2LfQ==,type:str]
    version: 3.13.1
