apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-pgpass
    namespace: cloudnative-pg
type: Opaque
stringData:
    pgpassfile: ENC[AES256_GCM,data:9RUX8RvzCZH7X/DTdb4xD9Vj4QvGuDsYKAtMhjTkSvHbeeQkWeVEPEtRkMuYxWyUj4PqWNj9IDZqJd8aFyGDZSnjFDnSSKZqfmH+suZcrxMouwaXTKTmIZrZDjaB1PWiVmvCRhpRfsPJvUVBSMXa0H7YQ2taNbGpRb1QTSzOCLwwcRDssnMytbcw47lj90BsRZbiAGop9AqXNOp0vzkPF1jRvAii,iv:Dc8mDUnl1XiF3Ptte0eWHJUuBqc7DSUWdvr22wZE5WE=,tag:2Fg4i2ygL2ER36Hu1Po0qA==,type:str]
    pgadmin_password: ENC[AES256_GCM,data:LeRz8mdhY3KBNQOlo0NTd0+0Np+3zbyORhCRUnPoyUXttyT6V775QUHD,iv:Qmt6BKHMh8FlzAk0uxKKPqtXJgHqzgp80SzWnY2/DIU=,tag:8V2Ze0Pfve7CY4ifTHV5jQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:a+2xwh/8AOVCjFUmWmwGXBE41U2N/GzWzeFTh3Uws/KgJ+XGhLEjN4k8tvo6wR4CEOc=,iv:muQvpeEVhk0AwdZT+BO4A/crUoytSJFzBZ9hh2AHmmI=,tag:xBFYhfklpVduLkNQHmF73g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeGRBbFgrdmNLTVdrdkxT
            dGk5RWFXTlltOEtyZjdENU03ZmhMWGppRWlBCnAyazZSYytXYUVDZ1R0V2haM2tr
            cGRxVExCV3pKL1ovOUlHeUlJNlZSMXMKLS0tIHhtaXJhR2JWdHFTOTBPb1BjVFJp
            NmFCcmtFbWhvQlhDVHZBSHdiaithMlkK2O50p1aq3Ko6bINRdujbVxNZR+OzHCbD
            D4tCuumBCs15XkMcay1YACIP/00/JpnxS7Gkhx5OmNmm6lRvDkAKbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T01:55:49Z"
    mac: ENC[AES256_GCM,data:DjnTqR6kETiROlAeiK7KPST4Pb8N8afxp0GAlc64J9wjc4EjwqEaaDOmznId+1lVss88umzutOypV30+tDuLvtNfnPcu0pIQv87C2cVz+eA7JU+M0Yx6wytUbqd6B9V7WSDpDkAh4HpSV05t+UfAaSSdRV6i0u+gs2BW/IetpiY=,iv:Ly79Fb4Q3vhNYJpC+YrpSFO/zqOxtf3MN0f0sRJDKg4=,tag:EjhT+bUg8/Ei65yhsfupfA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-oauth
    namespace: cloudnative-pg
type: Opaque
stringData:
    PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:y7J4LvISyCn4UvrzceanOrHz2nvNWg==,iv:Uy/GkeP+mGcCNhuGsLkelZgE1vmk3I/thCo9F+RcmSo=,tag:EonIzx7ubWBau80vBZRsLQ==,type:str]
    PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: ENC[AES256_GCM,data:+OXiTw==,iv:7WI8CySNabBbc34T/RVwCe0yLgwBr8UObf2PXNOqrqQ=,tag:5BQLn7zJvN1oWqrLqT8R4Q==,type:str]
    PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:5co+a8sh1LCsZXQhT95shjfLXwZsVpJEcDNN2b+aZK8I468udl0GqAfhzYKy6efoY7hVMH2MyXy21sgHOMeOrXYRU+S3nUS3GmlRxKLz0og+AisgJhN9gnP0rCXpVwzME87Gzao032zU3fdpfI/XQXQme9wzeiwr2MjRRL+DM3hyVd12gs9jL1QaSwhaiADXobrMW9NR/hCK7KZp/G/dNTvr4DvfReAcUM15XZQC/G3v/Oq1AyASVWBXzjxvGt6goOuclXuOk0j3hpAL6RmeWRqSMwSP8BpeCA3qZlkzTaCZ3X/QC0MZwnqSsHcHIKpVAb4FrPmW44DtY6JcHK1YDSW3Ayo+XovHMIA2dxV5xZHtULuuMr7PRI0ZfN3q11FueCdocObmLVvKbtgiXoLD9p3S9snIecXiV8QBfhj5wbhZKpCgbM02BZxs7Z/H1hV7VxUuDayY+iUe2k6bYBHAbfdS2+tV6Cz6ICTW/bJFlVtzQ0vrYS1V5Aq1lCXL3Iqv0kAlvPoGEd8nzp3W1hwA8fedPCGeNTtTkv3Sd78csMcUC6cVtFIuUoU3kSRqbpgCWJMDl2dkmo4njlS9py1Ts3OD0mAb4gkOscZegwdQVNwiOvrrfjzFNglo3U5wibJlKurXwKBgRv4O45IecI78T8gVUVN8RuIxunT9jxlaOzH356wX1jVAXGFa3OdZ8NhRQqMw8aJx7RtvUfLGBSOaKfG30JiimecvnV+THYZvVcRx9LQNjOBP33IyPGmTpu0bqIKcMLcifcDI4+z0as/u3jxQFc4ZR+25/sy1aJREyvuUKTqPtykHXmzfdJZqjT8GbFABpDdlX8cr32edu+M/4lNp50lgpEHVT0rJ4YbB3NdF/t6hHsJCLEDn0BpjixN1FQ5MQ9kSnEPYIBY/5oC2193gJU/gi/+bRy+cbQluR+0tWgmLdHJ9cgUikSrwoOFND0E14aY7/4/bM9fYDT6Uy7VOn/2fJd6ktylJCaNoH/5kGJFf9F4EmOYCl/vyynKVdXE5Pz8+iC5NTqVrIWJ3zqjSJCBKp1ZXmnQFE/ZTqpVT1ROCmtAr8GLjAH6LgiGRZ99j,iv:SdLbX49pJ4A6AlsdvqWulc2ll4vlqxpeAuQll2gx24c=,tag:MBk+N67S0VlGQoqJfjiAqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeGRBbFgrdmNLTVdrdkxT
            dGk5RWFXTlltOEtyZjdENU03ZmhMWGppRWlBCnAyazZSYytXYUVDZ1R0V2haM2tr
            cGRxVExCV3pKL1ovOUlHeUlJNlZSMXMKLS0tIHhtaXJhR2JWdHFTOTBPb1BjVFJp
            NmFCcmtFbWhvQlhDVHZBSHdiaithMlkK2O50p1aq3Ko6bINRdujbVxNZR+OzHCbD
            D4tCuumBCs15XkMcay1YACIP/00/JpnxS7Gkhx5OmNmm6lRvDkAKbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T01:55:49Z"
    mac: ENC[AES256_GCM,data:DjnTqR6kETiROlAeiK7KPST4Pb8N8afxp0GAlc64J9wjc4EjwqEaaDOmznId+1lVss88umzutOypV30+tDuLvtNfnPcu0pIQv87C2cVz+eA7JU+M0Yx6wytUbqd6B9V7WSDpDkAh4HpSV05t+UfAaSSdRV6i0u+gs2BW/IetpiY=,iv:Ly79Fb4Q3vhNYJpC+YrpSFO/zqOxtf3MN0f0sRJDKg4=,tag:EjhT+bUg8/Ei65yhsfupfA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-env
    namespace: cloudnative-pg
type: Opaque
stringData:
    PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:JRL7XD4=,iv:IHHJ6dKf5sotSEHfw3VM3D1RczYR/kYgYANFTejIdpc=,tag:NQkhBAiuwlTetKlICoFWRw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:Hfu3/AEbgbA=,iv:vC7JwcQVG6xeRt9GEjAZ0Fn3BjSoB3/tJm7aReid1xg=,tag:sNa+fatktq90FXZ5fZgh7w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QUIMGraJto/NarWoXfBgcG+I3fSYdgL4d+QCLwEZYcs8LN1YYOsyIKAUcC9RVAqkV6E=,iv:ZkEWSlg5MQVkY94Hq3pCVI3xxuqLHLFuEy128m7CJGw=,tag:fS0/XJQeHy2s07IjnIUUrQ==,type:str]
    PGPASSFILE: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeGRBbFgrdmNLTVdrdkxT
            dGk5RWFXTlltOEtyZjdENU03ZmhMWGppRWlBCnAyazZSYytXYUVDZ1R0V2haM2tr
            cGRxVExCV3pKL1ovOUlHeUlJNlZSMXMKLS0tIHhtaXJhR2JWdHFTOTBPb1BjVFJp
            NmFCcmtFbWhvQlhDVHZBSHdiaithMlkK2O50p1aq3Ko6bINRdujbVxNZR+OzHCbD
            D4tCuumBCs15XkMcay1YACIP/00/JpnxS7Gkhx5OmNmm6lRvDkAKbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T01:55:49Z"
    mac: ENC[AES256_GCM,data:DjnTqR6kETiROlAeiK7KPST4Pb8N8afxp0GAlc64J9wjc4EjwqEaaDOmznId+1lVss88umzutOypV30+tDuLvtNfnPcu0pIQv87C2cVz+eA7JU+M0Yx6wytUbqd6B9V7WSDpDkAh4HpSV05t+UfAaSSdRV6i0u+gs2BW/IetpiY=,iv:Ly79Fb4Q3vhNYJpC+YrpSFO/zqOxtf3MN0f0sRJDKg4=,tag:EjhT+bUg8/Ei65yhsfupfA==,type:str]
    version: 3.13.1
