apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api
  namespace: cloudflare-tunnel-ingress-controller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cloudflare-api
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare-api-token
    - secretKey: cloudflare-account-id
      remoteRef:
        key: cloudflare-account-id
    - secretKey: cloudflare-tunnel-name
      remoteRef:
        key: cloudflare-tunnel-name