- name: Install cloudflared
  hosts: proxmox
  tasks:
    - name: Add Cloudflare GPG key
      apt_key:
        url: https://pkg.cloudflare.com/cloudflare-main.gpg
        state: present

    - name: Add cloudflared repo
      apt_repository:
        repo: deb https://pkg.cloudflare.com/cloudflared any main
        state: present

    - name: Install cloudflared
      apt:
        name: cloudflared
        state: present
        update_cache: true

    - name: Install tunnel service
      command: cloudflared service install {{ vault_tunnel_token }}
      args:
        creates: /etc/systemd/system/cloudflared.service

    - name: Enable cloudflared
      systemd:
        name: cloudflared
        enabled: true
        state: started
