- name: Configure global settings
  hosts: all
  #become: true
  tasks:
    - name: Install SOPS
      ansible.builtin.include_role:
        name: community.sops.install
      vars:
        sops_version: latest


- hosts: all
  roles:
    - mdsketch.teleport
  vars:
    teleport_ssh_commands:
      - name: hostname
        command: [hostname]
        period: 60m0s
      - name: uptime
        command: [uptime, -p]
        period: 5m0s
      - name: version
        command: [teleport, version]
        period: 60m0s
      - name: ip-address
        command: ["/bin/sh", "-c", "hostname -I | awk '{print $1}'"]
        period: 60m0s
    teleport_auth_token: "{{ teleport.token }}"
    teleport_ca_pin: "{{ teleport.ca_pin }}"
    teleport_auth_server: "{{ teleport.auth_server }}"
