- name: Prepare VM for Kubernetes
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Run kubernetes role
      ansible.builtin.include_role:
        name: kubernetes


- name: Create k3s cluster
  ansible.builtin.import_playbook: k3s.orchestration.site

- name: Apply cluster post-install
  hosts: k3s_cluster
  gather_facts: false
  tasks:
    - name: Apply Traefik CRDs
      become: true
      kubernetes.core.k8s:
        state: present
        src: "{{ traefik_crd_url }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml

    - name: Apply Marimo CRDs
      become: true
      kubernetes.core.k8s:
        state: present
        src: "{{ marimo }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml

    - name: Apply CloudNative PG CRDs
      become: true
      kubernetes.core.k8s:
        state: present
        src: "{{ cloudnative_pg_crd_url }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml

    - name: run flux bootstrapper
      ansible.builtin.script: "{{ playbook_dir }}/files/flux_bootstrap.sh"
      delegate_to: localhost
      connection: local
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"

    - name: create flux secret
      ansible.builtin.script: "{{ playbook_dir }}/files/flux_secret.sh"
      delegate_to: localhost
      connection: local
      environment:
        KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
