- name: Bootstrap VMs
  hosts: tang, k8s-server-01
  become: true
  tasks:
    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: present

  roles:
    - role: cockpit
    - role: freeipa-client
    - role: tang