- name: Bootstrap VMs
  hosts: tang, k8s-server-01
  become: true
  tasks:
    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Add default zshrc to skel
      ansible.builtin.copy:
        dest: /etc/skel/.zshrc
        content: "# default zshrc\n"
        mode: "0644"
        
  roles:
    - role: cockpit
    - role: freeipa-client
    - role: tang