- hosts: all
  roles:
    - mdsketch.teleport
  vars:
    teleport_ssh_commands:
      - name: hostname
        command: [hostname]
        period: 60m0s
      - name: uptime
        command: [uptime, -p]
        period: 5m0s
      - name: version
        command: [teleport, version]
        period: 60m0s
      - name: ip-address
        command: ["/bin/sh", "-c", "hostname -I | awk '{print $1}'"]
        period: 60m0s
    teleport_auth_token: "{{ teleport_token }}"
    teleport_ca_pin: "{{ teleport_ca_pin }}"
    teleport_auth_server: "{{ teleport_auth_server }}"
