apiVersion: v1
kind: Secret
metadata:
    name: <release-name>-client-info
stringData:
    client-info.yaml: ENC[AES256_GCM,data:ElpBKk1KkNeeyIxhfHvO+fL3QleNsU8eXhtJd8XpxDus9SI38Kv62qQCbt4Zi5COOLaPV3LaS7nXGsPamHC6m5zluh40M4kLLjolEE5UqaRhX2ZWKtlAdlrZL0LHXXokLVUENRk7X3Fp2N8lgydTTxvhbYhSNn6926mp8EpsHU4wn3HbPqJXmffjmOxlMZJ2kSrqH+iYi6Fld1VSk4Wg+Jh+SL5iXYEmhnC+U2cxAtTNlNjpwcVY0WlrfRSdUg==,iv:Ua5MNJcTmCPmyOzmX8AKNpD557MyO8PAr/1SX6rqXvM=,tag:eunnrV7XymWMYKTa+Y73Zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMklqNld2Wk5uaGRzNzdR
            QllmeER5dGM2Rk5XS3NPQVl0S29pN1RkeUZJCjRiZlRRRzkvZmRsN1kzNU1PT2pZ
            WW56enVHbkhFR1lWZTRPTFhOcGl3T0kKLS0tIGZCdzFRWkcxOTVCUEN5aERLUDVN
            VU5YWHdYbTg4TlVyeUdmL3FMc29MVTgKUwUb20bGJcxU95Npt7474Fuv+uBr8kEG
            BxNV8uSTnkrcnloFGJonHtW7wRDXrKKO+NT++s44c2iHu2qbYQjV3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-18T02:26:25Z"
    mac: ENC[AES256_GCM,data:QXnDxBwZm4W/OB3U1BeTOaub5Barx8k96nHLT+exW5Zh7nYbilfhihnaPtInwbNnoe2/xVGoHS5c8rD56sTeci91JzsG8QTwP3+j2MNfceHG4ekwBbtnJ4nAf8VMStYg/ojtTjqpsqb/nytroCNIatyOKYiT5I2c8OVAaMMlyzo=,iv:pCYOlz65a0ss1s8H1OPzomn8S4brBtf37ggQmKp1IdA=,tag:tCKlM0IMZ1Bvp9+9Wy/Nsg==,type:str]
    version: 3.13.1
