apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:p9WXOLuev9V1tx+p5uTMfsrE6caLwW4TR+I=,iv:r9rPaIt65ilHUT9ncmPHdLEG2H8RujFq/EcN0U9F7OU=,tag:KLZlZDDrUjLrdW/I7ranMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OXh1WEdNWUFSNnc5TVpr
            SURmZTBmcS9ibmpIdFRnU1ZtMHhPc2tkTmdjCmc5dmRTQitMdEtVMG9VWS9XRnNC
            ektkaW55MG9kaHYzZGNHd3V2bVZxeHcKLS0tIFM2ZEtiWXVveEl0dVFFeG9rZEJp
            QjFHdXpIUVBVbU44U0twbWdwQU9kZU0KP/wfz/buFG3uf6EOkb/EO8yHa+QZDK1R
            KjCSnKP14/uok9DKcxCBdSZ0VHGCEVgKZgTJDTjz0s8QUMLkNXFGhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T02:31:00Z"
    mac: ENC[AES256_GCM,data:17h4D5X3cGwi4WNM3sQ+tx/U9E6ozHcof/uGe7KgTNrX98bFZ6Sb+BVauyX55MnqW62kXUcYPkGFamot4/0l95KV5WGkAIyROBH6WRlwXxcozADIngCoNAgjnLEQd3sro3FNRtD8idlS1LedbCkw16ajMTVqsnE3cer9XhTihOQ=,iv:yORM8RGPNdfnSfliph3iCV8xfF/tfGAFXNck1TvuAVA=,tag:KJmyyoEYnqjrAFQYbQC+RQ==,type:str]
    version: 3.13.1
