apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:npzvW4DC6+QwrmRox5ZdoS8G6cmnc8lswGk=,iv:ImsEu3CvlrC78JPpMKMYlKKSKBcuaISM148U/vsXzbQ=,tag:CLe3XumHNB9BHuxQl7YOYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZmtEYkJUQStubS9XcUJz
            MHNpeklyRHIyZVp5WXMwdWRKSzdhUjIyUEdBCjVXWDZCaTlXcDM5VjkzbGhEK0Q5
            MGEycVpDNzNXa05veUVMS2NWalErZEkKLS0tIFhPSUd6NWVnZnEzeXIvR1FwdEhS
            RnJVK0I2ZFBQOWNjUHJEcXk2SWJRVFEKigRnaZCpUkcduPO4dVl3qW7T9wLo6Xk3
            rBk22Jnd0uzqBtARoGBGyenuLoj0dZ1Y1Rsbb3eTfxETx1+gL0wyUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T02:34:37Z"
    mac: ENC[AES256_GCM,data:hQCptRSdsmjm7w5bU/Jl/Qw/q/mm3XDsfh+Qp5A6qZa0900ITFnSxDcm6wzGJ4ZLHZbb3aV8OlFwhI2Tdzj+eIbM+ciUqhyL1XGvr2W9z/7piZuZ4gEsug1GZ8gNdppDKksEfRcWkQ2MdIK06F1xKa60EvTHqVjZ/UXf+SEWpEI=,iv:42vWn3XO/6Ol1JBSNa6UoV5uAWp1I0vekbZ2pOEDwgI=,tag:TSz3dFDAcLxeMdtwvEVpCA==,type:str]
    version: 3.13.1
