apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:rBDBVJzIPhgycWEAZHUOJQKiuEzioy6+0h4=,iv:ox43tziuNQalPeiWRgbKP6XP27PgbJiB4Skse8w+6/M=,tag:N0b9HVgsl/wnYSQKsqv2kQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RjNFUDVrc3NpZXAvRTZ3
            L0pOV2pEK0VKMXREeGpHRndPQzZPdjFJZDNVClVDNlJoNHplYnJicmpwQXpMNC9s
            TWRBTW52cGdYUENMeFB0VzFueEFhVGcKLS0tIElKVVBVRXpodnVyVzRBZHNSOUVK
            RW9RUUZ5YWFjeWFRMjJKZ1FHSFltb00KrihXFJESVXxliqKBM8szEXaUtctPZ5uR
            iHzlHbQC0VwD9rUseCytlcMAZO3aVaNZqAx+P05U5WtbqQTOP2nlEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T03:23:49Z"
    mac: ENC[AES256_GCM,data:2tGrUTaBQjEo/SV9GIamaj8y17RaDLayHjjxkMvO05s/6qnGpIgnvUSvKrWm7jdfeo/2y1XyyjLkEVb5vAxgN6b94rq21Vi8IpdgUgu24MpumVNZkQ53ebJw/ZUUFbX+UW7wOXJ6mPXssZku/zjYWwuy7HOEKKztVEP6aiu9cdA=,iv:O/kGTM4BbRfEv0J4BVlmFlSbyq+wSNxaeZQOixxwnUs=,tag:H6TeTdD/Ya3EJ0Lgdg8POw==,type:str]
    version: 3.13.1
