apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:i+2mvjIO2dy3jyAiEbPzAQOAyQCKvYBV3yZuUsmevwfcK7G08ufR55MaY1EQuKyul3fw7bFpdEP6KajgkoSVifj4UDAD6ZTMRDSW9yj+qK6CJ9CdvBvFfn8hpii3Y0nCpWNULhliYj8Ms8Vddl8PufvnKpz9SpXwm6xO4VylYlls6M0JXksCVPSF0pF8R2WLsaSsVplTcgyip4H2JW3g26TCjOay9qXlfB7SVhnpcwkRhVPwa0G/ONTqol9n1ri4bnupJ1gWcyrj+eY588fvBYoLUBdAVO9qCVyvXNdfut8ijNvNLzM9CcxAQg4W5Tg2dW3ywa2ztMY6Y3NKB3ENJBMRPLCgm/x8REzSD6LkzpN3MpRUn848KbXnEbSP06/k990h3ISuRaCdvM/fBKkMYX66/OAG+YHxODINyO7jDEDym2FjwGiQbdQA7tvuOFHDZHkcsA7XbTrxzt+FqqZJHSJguwsteJxqVglsW4HbImCM,iv:9qjtgweJdqOzMqL5ho1GzkK1Zq5hBkRPJb7TrbPhPj4=,tag:zJgicwo3FXeVupbHE+xItg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWXNMbzhGS05mWnVBZHFK
            cFVyUE5GZjkrUUY0SUpuaTdwYTNicE5iZVRVCkNMYTVEVEE3OXBOWEZyZTQzUXpr
            SnRGOTNEOHY5NWhndWJLL1hOekNqa2MKLS0tIDFUdzlhbFFVWGQzUXoxZWVrdlZk
            eEZqR2R6U0Y5YitlNjU4SkFvaHVRaDAKjGyxTJIy9Wir7rVVq/EPG4wwazi/Ulq5
            OejZ1AjwtWd5d1I0HVAqMu/2RtzjrsxQDnqHeQuB6ZsUHyIDw/x3Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T02:02:03Z"
    mac: ENC[AES256_GCM,data:/qRzAuHyWZDWfcYTqdkNLVVlW589nsz3QGY0vzUwqQvy+pppv4YuMSRJ7kN/4kwRt6jg7r1ypWFWNQktRRMzoHrBaMNA3NLAsgBQh1CKCuw7ndaN0zjCv8TgCtsSXm/+EPdiFx1zeZz0j4Y0fegTbQ3iprdRcIUoi9gWD9isHjQ=,iv:V/Qja+WBv8th7PC2Snx8a9hQzVqBluR9zSaTVgBWVbI=,tag:SzmGHDLacaNzXnUHIO1rvw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-env
stringData:
    TZ: ENC[AES256_GCM,data:pW6lO14dEBQKn0f7EdM=,iv:BKJBdFY4iY/Zea3nvKpnDEMPf++kAxSVX6pXgPYSf5k=,tag:mOAoVLn8xcHkdeeNgBKw/w==,type:str]
    PUID: ENC[AES256_GCM,data:/xLyVQ==,iv:z2CCQ3nPNUpkOr6rb58/sNaYu9+Ts0I7DUaPBTDInY8=,tag:9xYW/VLVn9i/Vd3WYw5NKg==,type:str]
    PGID: ENC[AES256_GCM,data:cBJxFA==,iv:kzJTxy24Grt96XgtA3nAQaWHr0bzABU9OLgo13yuotM=,tag:1HtmID/9vwflSylGevZgGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWXNMbzhGS05mWnVBZHFK
            cFVyUE5GZjkrUUY0SUpuaTdwYTNicE5iZVRVCkNMYTVEVEE3OXBOWEZyZTQzUXpr
            SnRGOTNEOHY5NWhndWJLL1hOekNqa2MKLS0tIDFUdzlhbFFVWGQzUXoxZWVrdlZk
            eEZqR2R6U0Y5YitlNjU4SkFvaHVRaDAKjGyxTJIy9Wir7rVVq/EPG4wwazi/Ulq5
            OejZ1AjwtWd5d1I0HVAqMu/2RtzjrsxQDnqHeQuB6ZsUHyIDw/x3Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T02:02:03Z"
    mac: ENC[AES256_GCM,data:/qRzAuHyWZDWfcYTqdkNLVVlW589nsz3QGY0vzUwqQvy+pppv4YuMSRJ7kN/4kwRt6jg7r1ypWFWNQktRRMzoHrBaMNA3NLAsgBQh1CKCuw7ndaN0zjCv8TgCtsSXm/+EPdiFx1zeZz0j4Y0fegTbQ3iprdRcIUoi9gWD9isHjQ=,iv:V/Qja+WBv8th7PC2Snx8a9hQzVqBluR9zSaTVgBWVbI=,tag:SzmGHDLacaNzXnUHIO1rvw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-env
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:RotXfM2x7zty,iv:C2QK226iqEutQDhnvZ7kxri9B7vQg24o2zkxDX1ftmQ=,tag:Aj0Ibn+Jgxep4Y04a18C5g==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:b4zuWHY5M4qT,iv:WBhLcF1lhDHRWW0aw+6G8T6iWE8MPnSr30dTpFyNWHw=,tag:g+iVi8y9Fu/u1NhmibJHYg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:br/qyM1V49UhRvSCig==,iv:jEwQuzPlDuNJcCQMy7fdMn0MLdFlVuoKQQrVfwn3Noc=,tag:Dk1aXXS4V8Ge3PbuMrXWXA==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:sgD+,iv:IBazCjINcl2rD7Oz9fZXsoUiUxCPX96Jf4nm0uX6XdY=,tag:iKTtEk9qHAMqjZHz9j9mOw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:jVl1RX8io2dqsm7o9CklAF34CVzpPFk0yfnDcQvJ/Q==,iv:i/GQxz3D4g7gdFenZyBTVQ6FgVc+hm3SNwr7EwcHlqo=,tag:/Efrzjn3P0HRuE7AnsUT9A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:wfZUPfkWiBVYZeoh0+bv4KmoWvaL1L4I7cKg3OnXhvBwTc68uVzR3erOJgc=,iv:IfCEpRyjRTkm3kzGOe1EsZXtZRNwHQGAH5PNlKl8HHM=,tag:oXINnN08laQZEVl90mn+Nw==,type:str]
    DOT: ENC[AES256_GCM,data:xUzg,iv:grngZ61L0TTTE5FLmVQErGwIWJl2e3KKdMFlyTVdlk4=,tag:Xl5j6r8LADVP5BwKW4bn+Q==,type:str]
    DNS_KEEP_NAMESERVER: ENC[AES256_GCM,data:FKE=,iv:90Q1KSK1wH25Cqv0Lvk+diAVH0MYYof3lB/+UIMJPCA=,tag:bphWk8hVM3Zv6VcK3cpzCg==,type:str]
    DNS_UPSTREAM_RESOLVER_TYPE: ENC[AES256_GCM,data:S7qA,iv:lNfUofObi1FnKxbXd98itfLPEsqLO8pA49TIftKRDM8=,tag:RI964zWrSUCil4dV4CRPsg==,type:str]
    DNS_UPSTREAM_RESOLVERS: ENC[AES256_GCM,data:sACDL/0C8feGgQ==,iv:xiNvBGyaO6M9SbJDkH/yHSa5WQaNZ0xYTgnocI6VXRQ=,tag:f85GHUZlSeJg/1BIf6rEEw==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:yJBicUysqvcbn6H+QoSzDyBZxQ1xP7wpVA==,iv:yFlu+6VLeGgQ+H4SMHrAe/6d0bIrvfDD6aaQk/htyyQ=,tag:bJ9i+RegxhZIpprbPiFZJg==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:tQ8=,iv:wioN716csge+OSb1g5/5Td/xwI1DQkrzhI/dVd4LD6M=,tag:VHBmA/9F9oTUhpRFzSX7Nw==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:MvLcVTvo2snp,iv:HkUNlD5XHp6BzdtVwk5zigR6Lm48fsXVDMd/MjV7218=,tag:2Mro4Ry0tW6XoGg1YtvKlw==,type:str]
    SERVER_FEATURES: ENC[AES256_GCM,data:gMBs,iv:SyH5lhNy6bz84jCB/W7vZOtr4JPzUSHlOqNUA+q5t1E=,tag:Ne+s1fOOcJMyn7P5gRlx/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWXNMbzhGS05mWnVBZHFK
            cFVyUE5GZjkrUUY0SUpuaTdwYTNicE5iZVRVCkNMYTVEVEE3OXBOWEZyZTQzUXpr
            SnRGOTNEOHY5NWhndWJLL1hOekNqa2MKLS0tIDFUdzlhbFFVWGQzUXoxZWVrdlZk
            eEZqR2R6U0Y5YitlNjU4SkFvaHVRaDAKjGyxTJIy9Wir7rVVq/EPG4wwazi/Ulq5
            OejZ1AjwtWd5d1I0HVAqMu/2RtzjrsxQDnqHeQuB6ZsUHyIDw/x3Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T02:02:03Z"
    mac: ENC[AES256_GCM,data:/qRzAuHyWZDWfcYTqdkNLVVlW589nsz3QGY0vzUwqQvy+pppv4YuMSRJ7kN/4kwRt6jg7r1ypWFWNQktRRMzoHrBaMNA3NLAsgBQh1CKCuw7ndaN0zjCv8TgCtsSXm/+EPdiFx1zeZz0j4Y0fegTbQ3iprdRcIUoi9gWD9isHjQ=,iv:V/Qja+WBv8th7PC2Snx8a9hQzVqBluR9zSaTVgBWVbI=,tag:SzmGHDLacaNzXnUHIO1rvw==,type:str]
    version: 3.13.1
