apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:MKHtNal86EMs9PvLYnRmRS0SYTRSrmYQcygLnV1Lar3f/BkbxOswSxlYO675N+lgZvVR7imd9vktWvGLrsz6jfmBxK7AIwRNYrnDhtFbj9q+D2fr+RQ79NP01bSz6X8jMsp7KTYkmLcwcAsgPOvESiwLBHPZb/yrRIYpzDfSL3DWPsaoo6psrukOyfPUHdpQYUW7k5zO9W01g7zmwq4wd9Viv2oR74T1X4MRPQ05EsAb+0rfShmO/DwtCk93yjJlWNBvUg2xcZ+53v9uX/Kn90rY6U4tO+27NXix3oDq6JS6UFfx79mttZrUflupJeZK6sYm8YQBx3rSMkJeUISlesBuRARtSLEJxeFPl79jFkGPee8fzIFQAlkynjvz0nSlJk5QPOvM7BlJIId2FYvuNd+mjMOrjosb0fl9+Jx80ICecFotwmmZjwPlX4de8fOzOJRS1XfYRFNZiYRCwv8lBZVIdEN4B7zk6+R9HXIH4zRjTzN9e7VW7w3//INVhgCKcfM90mCCvjy+a8zSPlTO0pIuYMPokU/Isa6JoJA0tiH2rp2arGvTvOW/OfXfTjvPGG/Io2f5mMHrFxSG37tuZXJuwPdMURyCWTwuIoiloXYRVzrKDx1m/KNh/GqGCGTi0aEbjsrVaQEQM/fG32tijvSdtbXiHE6qCRTOV8lRfs08m80Oh9K8esqLFBcifboBGYmi9bKzUVfsLLXHJ5VN5K0C6JSJ0OUOVqDngEkLMlUWE58=,iv:mqekQkleiN87/T+PWaJ7xsS2EAAV3V2vO0ZVayCwMa8=,tag:H/jszKNHr2GdSNqJbhItWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWnBneXpKMWtDYjVBVm5z
            NUJkUnJLbEY4aDBtT1RHdThMUzFLa3BET2lvCkxiaFZkS1VKOHFneVpiM25EckFV
            VGJ0eks2UFVwaytqVUxlK0tnQUU0QlUKLS0tIE1jQ3lhdUNuWkxPTHE5RllaNjlW
            UVIrSWcvdlJjNE1HaFVsYVptM01uYncKwY1SP8Lc3zuCSVYTX/8VrExqLszx7xMQ
            bBZxxNmKCympUP4p6Spv5MlICDIlmoN8nK23O5oErTT8SJQFYNH0Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T01:04:39Z"
    mac: ENC[AES256_GCM,data:djrFxCWhZnuHiml4ZGiDEjIj8yCKRCkyvb595WN7EUYLmNMWbhfutDcWasDc1/Hy5KbbR7MjadRbOScWaY9Y+OC649VZwVI9HAtlogQnJ/AzUnwyjbBYvH8D+y3z+p3FIQgcANmgTLVHxHtuCoa3qrGX89XNkooR0zNCfEnmOnk=,iv:hDkbyVfiK+C5klG8ZuieZlPCdNBmPzUt79AsVhsJkhI=,tag:RgahLdwnIKOc4JyiKSNioA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-env
stringData:
    TZ: ENC[AES256_GCM,data:7nRwwvScKJXj3WZnGiY=,iv:s2DUYpptaEJwYszMbLD+BnsVJLSxbjKQjaujO4VWNYI=,tag:Xf1p+PWJW8HnzSX7QhRMQQ==,type:str]
    PUID: ENC[AES256_GCM,data:4ZB9Wg==,iv:LrxidIAIIyrZ3CyC8HA8g7s8jYSc2pJ0vMEqiPWvSvs=,tag:IC3XcodJg7Qb8ajDlZ/EEQ==,type:str]
    PGID: ENC[AES256_GCM,data:PnjS5Q==,iv:g+CsXiZNWCK+0vtoUJbTM5VtPJt1jyf3FBq/o5YJU8s=,tag:1S+DQXihoy3voIhIq0y/xQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWnBneXpKMWtDYjVBVm5z
            NUJkUnJLbEY4aDBtT1RHdThMUzFLa3BET2lvCkxiaFZkS1VKOHFneVpiM25EckFV
            VGJ0eks2UFVwaytqVUxlK0tnQUU0QlUKLS0tIE1jQ3lhdUNuWkxPTHE5RllaNjlW
            UVIrSWcvdlJjNE1HaFVsYVptM01uYncKwY1SP8Lc3zuCSVYTX/8VrExqLszx7xMQ
            bBZxxNmKCympUP4p6Spv5MlICDIlmoN8nK23O5oErTT8SJQFYNH0Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T01:04:39Z"
    mac: ENC[AES256_GCM,data:djrFxCWhZnuHiml4ZGiDEjIj8yCKRCkyvb595WN7EUYLmNMWbhfutDcWasDc1/Hy5KbbR7MjadRbOScWaY9Y+OC649VZwVI9HAtlogQnJ/AzUnwyjbBYvH8D+y3z+p3FIQgcANmgTLVHxHtuCoa3qrGX89XNkooR0zNCfEnmOnk=,iv:hDkbyVfiK+C5klG8ZuieZlPCdNBmPzUt79AsVhsJkhI=,tag:RgahLdwnIKOc4JyiKSNioA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-env
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:YAMdJdie5/BY,iv:QNuNY+Q2LcPlAgiRMUu2e+so6jdaAfJ5ywwoWE/fig4=,tag:lWvbXtd/ZObnFrnFJgxBEw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:EEMqdoyyhZsC,iv:v0884gAPHpWYydQD8eiufN9rMysl8h+NvxZzTAGLP8A=,tag:7AQblWVQFjW3cD1xRInr9w==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:O74jdzQusVZ179KHbQ==,iv:4i6MGyj1wI0pCNashPSpNcNVhdB/i7NezIY19vSH6sM=,tag:eCm2Q+DMD9y/pQ4CZF9Oeg==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:Qv3n,iv:Y15TCTlPXquPNnF9nZFy0wSbsg0WT3bLNWOa4Bnn4cg=,tag:Vi4ofj/MrId/kpm7JcBhDg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:iJrfHGo+4w1GeR6DPOfeB2WejRt+36ExeOXNSXH3nQ==,iv:OvidWnpjWUTLLmtgEmQ1QHPMGoDWgD9zzlfyMOQoAYs=,tag:YIoWi3d2s+NTeFuJaif6AQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:odsz8s82wflRkkC/SSYiakTHX2YC9PuoryfNwHk3nhlhqeL58u99RfqOwQ==,iv:nmRvXKFeXRStoSrXeQ7VxjW++g8iXEtGbNyGza/b81c=,tag:MOFJrd49SnbSspL9Lh1jHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWnBneXpKMWtDYjVBVm5z
            NUJkUnJLbEY4aDBtT1RHdThMUzFLa3BET2lvCkxiaFZkS1VKOHFneVpiM25EckFV
            VGJ0eks2UFVwaytqVUxlK0tnQUU0QlUKLS0tIE1jQ3lhdUNuWkxPTHE5RllaNjlW
            UVIrSWcvdlJjNE1HaFVsYVptM01uYncKwY1SP8Lc3zuCSVYTX/8VrExqLszx7xMQ
            bBZxxNmKCympUP4p6Spv5MlICDIlmoN8nK23O5oErTT8SJQFYNH0Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T01:04:39Z"
    mac: ENC[AES256_GCM,data:djrFxCWhZnuHiml4ZGiDEjIj8yCKRCkyvb595WN7EUYLmNMWbhfutDcWasDc1/Hy5KbbR7MjadRbOScWaY9Y+OC649VZwVI9HAtlogQnJ/AzUnwyjbBYvH8D+y3z+p3FIQgcANmgTLVHxHtuCoa3qrGX89XNkooR0zNCfEnmOnk=,iv:hDkbyVfiK+C5klG8ZuieZlPCdNBmPzUt79AsVhsJkhI=,tag:RgahLdwnIKOc4JyiKSNioA==,type:str]
    version: 3.13.1
