apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:PUVMiYecZaVAJobt/xmbc+WN9hzVEL6nVf7hJOGeKM7K/FFVS2RWoBcqnwHwfL6oSQBh9fLLsK8XS/JrES78R+dDwdB21/KbeXuY4Fm1slV5mqT1E2cmZgd08BxXlRU6xT8yi36lkkUVxZlcrddM24YMcRMdpuF1Xo2v+C0ieHOhTz4pD+DDjtKpMuQMCFZ/90MJS0PVIiKHkZIVC/gQ8fhoJFOjxkAfl1OZkr10z98geOw/MIfpJb+7dScb1d6MRKcXhDZ73RT+9yZAPgfNCn95bGbXU37hIgYGIGP2T5rMTEHynk8z5566/1ZOGSb6c+qoRT1u7GbC038eBpxH1QF9C6kAH+C1wOMjA1+AcgIt4P2NBXcGA+qd0rc1+NgZZvAp+SC59I7ii0n3zMR5gB7NZitZmUIT1UjzC2KdViXO4ckPqOzUUVDzVAGVXyQKRSDL5PbY8sqJxF0dAoZzrqDlNiU6VW+bf84R+VW8k7nZ,iv:bkYV9VOtLFD76pcjRzVUo+05vUq/+gTebArSCUVdp1Y=,tag:RHElj97Rbh67piY5tUgs2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYVJRQUx6NzNCQmF6YnJF
            eWJtdWFocWs3WTc5eStpeExUM3dFWFppUVJvCjQxN1cxQzdORDB3MmVMTFJSVUZk
            eTZvRnF2STNZVWduR1p6Ykk2Q0xwK00KLS0tIGNxWVRQcCtxM0lsR24zeHF2YlYv
            UTRocUcySFVYM2k0QmlyNzhRY2E1QWcKClYBjS2saKv0b1isa8c1l4OS/+jjhgJ9
            UhUzKMhinh3pavGNH97qMFWLWOwjQgw5xeYpGEJZRCEN0kK9uD0DWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T01:36:31Z"
    mac: ENC[AES256_GCM,data:TpLyMuinp4R1Nv+E6UC3GY+4n0nqaRWnwve6f7zFFOSg4MFngpsHwbpLZV0oA2g9lfzCJrNezlihKjMP+FOwIY9XWMn6x4szg3n9nghGIa/jvrCPHqZQPDXC6k21UOhd2/hQtwRr/f9LTpPSGFkQWOxiNA3GxzDFaScvKdqfeHQ=,iv:5yUHXI7NeOOoDrS+It/cznxE9kdlOoYixOlppIoEECs=,tag:iiIyH7KVSjltusu3QCU2oQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-env
stringData:
    TZ: ENC[AES256_GCM,data:GCrhy0F4CihgKNzQXpA=,iv:DPOVat9xROFVSwx2KvIhS/LVruwnjEZYwiEKplNnFW4=,tag:W+usUJjQnam0e1f8Gw8yWg==,type:str]
    PUID: ENC[AES256_GCM,data:ZuKiKw==,iv:0NzleqbQ+fKnS9NQgalqsDG185SvbWf3Ue2NNC+h8NM=,tag:tZTwZCeKTu4sESr9KT9I8g==,type:str]
    PGID: ENC[AES256_GCM,data:qqQpmQ==,iv:gdmQsHjIi14ZjmZa1fcCTepe6a1r0s6Z/ESOxunMT14=,tag:ibzSBSkANHtX+yWO4QyQaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYVJRQUx6NzNCQmF6YnJF
            eWJtdWFocWs3WTc5eStpeExUM3dFWFppUVJvCjQxN1cxQzdORDB3MmVMTFJSVUZk
            eTZvRnF2STNZVWduR1p6Ykk2Q0xwK00KLS0tIGNxWVRQcCtxM0lsR24zeHF2YlYv
            UTRocUcySFVYM2k0QmlyNzhRY2E1QWcKClYBjS2saKv0b1isa8c1l4OS/+jjhgJ9
            UhUzKMhinh3pavGNH97qMFWLWOwjQgw5xeYpGEJZRCEN0kK9uD0DWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T01:36:31Z"
    mac: ENC[AES256_GCM,data:TpLyMuinp4R1Nv+E6UC3GY+4n0nqaRWnwve6f7zFFOSg4MFngpsHwbpLZV0oA2g9lfzCJrNezlihKjMP+FOwIY9XWMn6x4szg3n9nghGIa/jvrCPHqZQPDXC6k21UOhd2/hQtwRr/f9LTpPSGFkQWOxiNA3GxzDFaScvKdqfeHQ=,iv:5yUHXI7NeOOoDrS+It/cznxE9kdlOoYixOlppIoEECs=,tag:iiIyH7KVSjltusu3QCU2oQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-env
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:ls2GI4iDjwEn,iv:JwG35caNd1MwdvZkb70xxBW3bg6hnB1aWue005m32vU=,tag:XsJXsZ3eBREQVnhbXs5HpQ==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:pjHO2R8xYphL,iv:WcUlIDrEQLvx4H6mmQ54hNoOS5V0YyQ6apmmFfHliqQ=,tag:QSJiYYmxCw64KkPR4qbG8Q==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:WWqsagFfV50n80SFwg==,iv:jwgcY8u0NWkB66SVkbu+TSdrNZbQ24fc9LqIT/U5Vn8=,tag:nLrIwI6+y61C11eLHkbAjw==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:IdZ3,iv:Fe9W5kwnsy+ceyM+wZvLAfILEptW96lzEhP/QRBPoYs=,tag:LU8xoogZ+5mkdoAW1+ZmTQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:nhi/1bh3lkzoO2PW05K84h9wC1nq2Y8eGUqc5tGqsg==,iv:8u9WhgShX3BmLVx3/64H7DyP1gshoAbSu/MKvGBvvMA=,tag:r+OSuvmDLX5TeZRNcM/YdA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Q528X32V7M2ZWL/e/N+TmfUx7FEBCkIepBu9y5mgafMFtLCLgFimHlKSqyI=,iv:/Q4AEem91v3+fiNadD9PBnEHnVmfig7jOisAUnNUFhs=,tag:MtHLUF+JMSZX0HZaAQWZdA==,type:str]
    DOT: ENC[AES256_GCM,data:rGIJ,iv:fYEGlisH5t34Ah7Sls76/lEU87PzEMsH6zfsnntBcvg=,tag:GISWrvNCNyVaGMp4JTCJQA==,type:str]
    DNS_KEEP_NAMESERVERS: ENC[AES256_GCM,data:AGY=,iv:2ZK/Xuj95y87D0zdmxU6qtMiNkotISS2KUAOJ9K3Qic=,tag:xzz76OCeDrao/At1kv8T4g==,type:str]
    DNS_UPSTREAM_RESOLVER_TYPE: ENC[AES256_GCM,data:W1kr,iv:fDfRRoWWiHLIM6kaqFnTKWk3lrE9CpxTQyUyj0mH5T8=,tag:cH8yzxDRA4jWv/Mjq6a0Fg==,type:str]
    DNS_UPSTREAM_RESOLVERS: ENC[AES256_GCM,data:jojkUzDKr2aqBw==,iv:4fOx608xQTB+1D3v6iNf1TDELzTNXYCtcbGpD8oMj4A=,tag:z0wx1FuK7R4CIvf44zZMgA==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:eILAqRKERg==,iv:tMWdOaeXqfbNtDofNQOGs0Ac2qYocMCf8W+8fVBjE/s=,tag:MgnAbLg3QT+f2gGDAhoMsg==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:N+MTp623zsoDhR9sCFz8/3c9/xU6HfY2NA==,iv:8/PyRu/FNMKfpRxAin6XlX5fJp1ZGR9NSvzVIQlWFF0=,tag:zto6mOHRw1QR3ELgGwYiTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYVJRQUx6NzNCQmF6YnJF
            eWJtdWFocWs3WTc5eStpeExUM3dFWFppUVJvCjQxN1cxQzdORDB3MmVMTFJSVUZk
            eTZvRnF2STNZVWduR1p6Ykk2Q0xwK00KLS0tIGNxWVRQcCtxM0lsR24zeHF2YlYv
            UTRocUcySFVYM2k0QmlyNzhRY2E1QWcKClYBjS2saKv0b1isa8c1l4OS/+jjhgJ9
            UhUzKMhinh3pavGNH97qMFWLWOwjQgw5xeYpGEJZRCEN0kK9uD0DWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T01:36:31Z"
    mac: ENC[AES256_GCM,data:TpLyMuinp4R1Nv+E6UC3GY+4n0nqaRWnwve6f7zFFOSg4MFngpsHwbpLZV0oA2g9lfzCJrNezlihKjMP+FOwIY9XWMn6x4szg3n9nghGIa/jvrCPHqZQPDXC6k21UOhd2/hQtwRr/f9LTpPSGFkQWOxiNA3GxzDFaScvKdqfeHQ=,iv:5yUHXI7NeOOoDrS+It/cznxE9kdlOoYixOlppIoEECs=,tag:iiIyH7KVSjltusu3QCU2oQ==,type:str]
    version: 3.13.1
