traefik_crd_url: https://raw.githubusercontent.com/traefik/traefik/v3.7/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
#cloudnative_pg_crd_url: https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.28/releases/cnpg-1.28.3.yaml
marimo: https://raw.githubusercontent.com/marimo-team/marimo-operator/main/deploy/install.yaml
