apiVersion: resources.teleport.dev/v3
kind: TeleportGithubConnector
metadata:
    name: github
spec:
    display: ENC[AES256_GCM,data:tdrkXeok,iv:wL6E0M+YLT8K5/xXTj38PBdpXdLmmd0DEM8s/7STDXg=,tag:F9GobfbkZZ8+KK7YzMvgXA==,type:str]
    client_id: ENC[AES256_GCM,data:Za9+etHb/Dv7EdLJjeUkMCDfgwU=,iv:eL6ZVig10PfpWakUSN4kpAcRbMauaikilGSKbsjG4Tw=,tag:mB+z5XnJDN5jskH++X0C5A==,type:str]
    client_secret: ENC[AES256_GCM,data:lYQPPzn+FOpW/DIpOqsanfrQKjn8hAd1vprsaGa/SGa1IfBbvzWXcg==,iv:w8k2G1uL13TS67ZwQr5w6TIaRmFyhcaUKUOqw/ra+7I=,tag:z/flpJUEE7DbRVTHgm46zg==,type:str]
    redirect_url: ENC[AES256_GCM,data:gQvC1ZDvZxNBrW+exv+utrLwyV2E8zgV+COB6gU3KCKsI9t/y8kpWS7OHBO2Ts96fygdnw==,iv:jVP5E6hvFOS+X/pSjbFkTridJGM0A24HtAGU67s5XAc=,tag:mLPGUL8pCf04VrSqwXky0Q==,type:str]
    teams_to_roles:
        - organization: ENC[AES256_GCM,data:NgBPJ5E2ZqkgGauWMpRdUpXEuE+VhWmyjuc=,iv:w5w1skK36crwDXkxLDWgL20/bzb61yYr1Ya+qri8Yys=,tag:HqvnJQO8gdB8vQaZ29LdHQ==,type:str]
          team: ENC[AES256_GCM,data:FZ0Uu5bTEY6JIMgJXASi,iv:IiBon0vnOOqGY8QdV40FDsAbuLCAC8yf7PBGEjgbloU=,tag:zTwNfuQYyjI8feA4lXE5wg==,type:str]
          roles:
            - ENC[AES256_GCM,data:16tjP622,iv:Sa/4+cu2PrXboCLRxam0uLCJ9IsHLePKWstmN5+M444=,tag:nTbv6nhuyTxXG1oTV4TlwQ==,type:str]
            - ENC[AES256_GCM,data:ey99E36J,iv:PypT1qSF7Vuuma0dfKM0xFDv3UoC+BFDvgq8r9XlUGA=,tag:MgSPTaOZPPPhg/wQtOjvag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN3ZuNnc5UkV5RVNFakR6
            OU44THBpVk5CR251RmIvVDhiVTRaYmNoSXlJCk55d2Z0VXprM1pwL2J4b2MrUmVR
            RWZZSVdya21DSGtTTlZqc3RJRnNlekUKLS0tIFpTS2RJaFQzdWNyQnB5Sks0bk1G
            bmJXdWtpKzdVTGZmTllXN0k0czcwZW8K6rqXwBnfUom5CJ/qZg1dlfqleOSLVwMA
            wmGPIWf24Qdm1yl0iGyX3fZFG6CBUhKIsynAWBmjJ3gYBqHspgfw8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-10T04:10:18Z"
    mac: ENC[AES256_GCM,data:DlAXVJe/iC7Tz8cv/yXuUYK8Uzi93k3phiDYbjl5xOC5pdTlHxrIfGzT5Y3YrwNRlU2yinJNJmd21hSp/JDb8Dz2dK1JtveQ8r51ZMg8E/zsD8iHwJ03vVYPaBItlRymC3b6jPoXsTPteOi9KAjncK3YGb/uUcZTjC8D0LbIJZE=,iv:toFKyLOQ0rO2UCBwnZ4eAvJxR0QTOsyVMmqmnNXMNqk=,tag:k2Y35Y49IWItcddE35D8yw==,type:str]
    version: 3.13.1
