apiVersion: resources.teleport.dev/v3
kind: TeleportGithubConnector
metadata:
    name: github
spec:
    client_id: ENC[AES256_GCM,data:38R2gi/JYgtplNGXLhJz5pDjKTY=,iv:wWWQsd51RViKlQFVtaCEx5vM7jwOcyiBJ3+D0yfP2j0=,tag:5lVcmtVfpCrS6/1hZPIQ1A==,type:str]
    client_secret: ENC[AES256_GCM,data:h6E0ntZPJ+8OngQUiVbonypsg6y8smmnupU3pKmRte+qNzoAdhDswA==,iv:CUZpKJenL9GIpeXR9e8XlxN/4ZDirUwIl+mrIh8zjmw=,tag:Mpk1y4g4ADcisCXpcczFWg==,type:str]
    redirect_url: ENC[AES256_GCM,data:McsegUt9Ml7tlehkhPFespBgBOWA4JOg6CwEmJiOaUQtE9d8YcDyrD5KdEX5Wa3uFVxfjlVi+B48ZIIL,iv:MXF2aIYX5tvylEos9XmMBL61qkXEHoTyAwErQyg3zlA=,tag:Baak2Zd9ue4E3IFgIiANxw==,type:str]
    teams_to_roles:
        - organization: ENC[AES256_GCM,data:JA8wRk3Ej+Vx9QF/WnNgv21Ky3kqPhkLyt4=,iv:JHA7yEPHFBbhqwWJN1mATzcgh+E+DRIRS2kqoCrHsGk=,tag:hwsdVlgp7rkoz6AavU9ITA==,type:str]
          team: ENC[AES256_GCM,data:Wd98byjdGbfRKVNwhQUW,iv:9h/E8vtqvNTPlC5xriHOPDL9nbN8n/ybz8orNprd0Pk=,tag:Z3FmNz4/wCL9R2Gkle5WLw==,type:str]
          roles:
            - ENC[AES256_GCM,data:VP6e0Ns=,iv:83WnEI3T11eKqp/lUDUABAqIfUmet0fSnNY9HHJH21I=,tag:YphiJFqgs+2mEyyC7aUgcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ3pnMWhpOTZpZWFPdG9W
            YytEZzBvbFdSTUNxTDJ3aE5WTGo5cTFWSmprCjB1MHpjRFZCRGJRTkdiWmVPWisx
            K2xGRDZ4eFVlU2pxMlVncUlUbndrbTQKLS0tIFJiUisvQXFFTjR6UUZ4VzVrVXlI
            aGFNWEdzTmJwVWI4eTFZYjlFWXFDSncKBS2+icX6GQWiZ029kQhU6deKs6xMRmtX
            78my0pyfcYmgdI+VLwFbJdyGxmvXDOSkv1AvFbWj19ktsRrrJ9VD3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-10T03:55:25Z"
    mac: ENC[AES256_GCM,data:XpU6CG55PCkQNLhQf5viaVj9s/qYD1e3qby1mIJh2dWms+a1+RrM1xWIKjj95J7vWBqd7rwaPyzT2043WEJdEOnhCx2nOpB6qSWi++jKrXe3/J4+0sWMSnkuP0RkwuUugFdZ3Dbs132XSa4wy5zloSZuTZ07EB7ARCDDrL4O6tA=,iv:pCbxo/5kiW9rHQmeuTX9d4FuUHRoF1y0QX/biQf9oro=,tag:kHRJPoYGdX4CLMCUydbHig==,type:str]
    version: 3.13.1
