apiVersion: resources.teleport.dev/v2
kind: TeleportUser
metadata:
  name: austin
spec:
  roles:
    - access
    - editor
    - db-access
  db_users:
    - "*"
  db_names:
    - "*"
  traits:
    logins:
      - root
      - ansible
      - austin
  allow:
    impersonate:
      users: ["Db"]
      roles: ["Db"]
