apiVersion: resources.teleport.dev/v5
kind: TeleportRole
metadata:
  name: db-access
spec:
  allow:
    db_labels:
      "*": "*"
    db_names:
      - "*"
    db_users:
      - postgres
      - authentik
      - semaphore
      - nextcloud
      - n8n
      - mealie
      - paperless-ngx
      - immich
