apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Jf6EVkXrwSa04WZNCFVC+PamShdDgWorRykyQcS/lg==,iv:8jvkAoUHyydXsok1qgBVuVb6VlscTZUKJciGtJI9tpc=,tag:4kndkLtR4JUjvlhzltHENw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:/Hbz6poD3RvvQN3cvMOyzgiYwRhAxOz9R9BEnVnOG4ZpxxkZgB/Xm6agn8w=,iv:x4gVRfUwVSwciMOsPKIBN2FCg5ewEBslBgxQ+c9F9Qs=,tag:uL2iZcPuOERbgiNQ1j7fDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VllWMjBMVElpcjdUbHln
            VXJoc2VXRnpMM1ZsU0x4YXVQbDlGS3JsdVZRCmRkYzF2ZkZUczVQRnhLN0FuVC9X
            VjArVjIrNXg5L0Y4b0hncTVIOTl1Z00KLS0tIEhnYWNleHliNERjR3BGTk9rRUNR
            aUNKNlUxcFJIb1VteWxJYUMzNkFiTGsK83WN7JuZyx6FLBtudpW5EABcIBC1Noae
            KAdJu8eOfvqS75ZdbiG1/ueBOt5QWHExDvj13OnV8D5c9MgP+vHNuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T00:29:34Z"
    mac: ENC[AES256_GCM,data:cvPu7I2iBKUpalawTjna5aKxe9W09llx9w7rZIEMUqiQsJsd61esSXxFIdpJMXDjbR6vth35fwUtt4Rq/fmdsRKGnTqZVnjWqcA9rkYVSAz5vE+PCtPvD+XZUEQHZnK8OKdQOvO5F+6TbmCr4oc6MGLMcZFRdozZw/37v/cVd0g=,iv:k2E1lZ4cKEQ5Lxli5h9j/7AqKqIhr5l3h+kzgqF3sTk=,tag:wvpRL37I3/hFIi+vU/DnYw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-seed
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    qbittorrent_password_hash: ENC[AES256_GCM,data:A49sSGpB8rreQgEhzgCqjRdwX+ji0ohG3Gb9p+MiSrA+UqTU/kXKT+RNfCyivoH5Q7267LlhDu1Q2z6ukKAJeis0+xwgaQvILKf0xPrFgPh7ZtzsFb1gBtLTCfybo+yVEtFr8i8oX+bfnEBJZ6tlMUFyq3kF4/AA39lpnFY=,iv:/nL5GRtSrnLaJ6oL2+zh+gBU+5k+sJh3vDOMjpKybVo=,tag:MC/vw9mrH74DMR+TssAspQ==,type:str]
    api_key: ENC[AES256_GCM,data:HpDi5m8EZb67D3tCfACxddUyVz63Dol5d5cQdoYAalI=,iv:odUi0e9PpaYghhf/Ule7ZnXHhMsNvfc7eMq0EkxmQgo=,tag:SDF0tQwYmOtSSVFsuw8gkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VllWMjBMVElpcjdUbHln
            VXJoc2VXRnpMM1ZsU0x4YXVQbDlGS3JsdVZRCmRkYzF2ZkZUczVQRnhLN0FuVC9X
            VjArVjIrNXg5L0Y4b0hncTVIOTl1Z00KLS0tIEhnYWNleHliNERjR3BGTk9rRUNR
            aUNKNlUxcFJIb1VteWxJYUMzNkFiTGsK83WN7JuZyx6FLBtudpW5EABcIBC1Noae
            KAdJu8eOfvqS75ZdbiG1/ueBOt5QWHExDvj13OnV8D5c9MgP+vHNuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T00:29:34Z"
    mac: ENC[AES256_GCM,data:cvPu7I2iBKUpalawTjna5aKxe9W09llx9w7rZIEMUqiQsJsd61esSXxFIdpJMXDjbR6vth35fwUtt4Rq/fmdsRKGnTqZVnjWqcA9rkYVSAz5vE+PCtPvD+XZUEQHZnK8OKdQOvO5F+6TbmCr4oc6MGLMcZFRdozZw/37v/cVd0g=,iv:k2E1lZ4cKEQ5Lxli5h9j/7AqKqIhr5l3h+kzgqF3sTk=,tag:wvpRL37I3/hFIi+vU/DnYw==,type:str]
    version: 3.13.1
