apiVersion: resources.teleport.dev/v5
kind: TeleportRole
metadata:
  name: db-access
spec:
  allow:
    impersonate:
      users: ["Db"]
      roles: ["Db"]
    db_labels:
      "*": "*"
    db_names:
      - source
      - staging
      - marts
      - scratch
      - authentik
      - immich
      - n8n
      - nextcloud
      - mealie
      - paperless_ngx
      - semaphore
      - postgres
      - wikijs
      - sabnzbd
      - wizarrr
      - romm
      - test
    db_users:
      - data
      - postgres
      - authentik
      - semaphore
      - nextcloud
      - n8n
      - mealie
      - paperless-ngx
      - immich
      - wikijs
      - sabnzbd
      - romm
      - wizarrr
      - test
