local action:
    @echo "Deploying local cluster"
    kubectl config use-context k3d-local-machine-cluster
    kustomize build clusters/staging \
      --enable-helm \
      --enable-alpha-plugins \
      --enable-exec \
    | kubectl {{ action }} -f -

server action:
    @echo "Deploying server cluster"
    kubectl config use-context k3s-ansible
    kustomize build clusters/staging \
      --enable-helm \
      --enable-alpha-plugins \
      --enable-exec \
    | kubectl {{ action }} \
    -f -

delete:
    kustomize build {{ invocation_directory() }} \
      --enable-helm \
      --enable-alpha-plugins \
      --enable-exec \
    | kubectl delete -f -
