vault_become_user: ENC[AES256_GCM,data:yDW481hlTw==,iv:P5/Dwf7jq8N4OSm78by0N9QJuyFblA25QkWK72zflI0=,tag:X8oFKl8j1yXntpPvX7noQw==,type:str]
vault_become_password: ENC[AES256_GCM,data:A6FBo2wlDFBW+rXYRJ6Z32kYN2f2+NkQQ5Qlg8SBxVdpSHbq9RPyKVxutcXVZg==,iv:+/YFHN8zf9NbMx1rOh7FSvOICusMc3QYQVAASYza9D4=,tag:FD/+wCkV2w8D635Fq7si8w==,type:str]
vault_workstation_user: ENC[AES256_GCM,data:3/HayKc+,iv:HSTJkrXl0xC3++ZwcwenacMjTfZWl6CM2CuivtO2/yY=,tag:MrcUOe/k+6n6bWnn9BQmBQ==,type:str]
vault_workstation_password: ENC[AES256_GCM,data:avdZdzv+8RSfYw1qBqifFSSt42NJoMILDb0i0mPFT8WgDV+cg/nQb7PZY119SA==,iv:MkjoM945OvF4o+GtirNH/LkGCh2LAS0DfRTCVyrC55Y=,tag:qY6DRWTYM99YOAV01MSFpQ==,type:str]
vault_workstation_ssh_private_key_file: ENC[AES256_GCM,data:lCNG2icrqXV+ibKzl4Sgn8zzi/3YATA6lMibWRbRnEdv5y7+,iv:xz3hxUajkrOvywjchh516/s562xq0VKFa3JTiH/W1As=,tag:paG2I7Nczlo2WDyZa3mPGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY2hxazZHSExScEJzalpy
            elM3dmI5VUpLejJ1TUYrYThkVnlLeWxIS0NnCjg2TXdNV3BBU1ZVVlJDYUNtYmh1
            ZURCeVl0UHkvU3BFNk04eUJoOUYwbXcKLS0tIGJvRTE4MzBQblZZN1VFNG5ST1hn
            VDQxVHdmWmlORDlwM0NaREdTZVNpVzQK6P9o/DcGvhXOMTXSwCscnwcOszLzURxr
            GPLtHTyNErrHyg82dMYng2xplpvn9KMaSFKDfc2KNrRkXothfPePTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    lastmodified: "2026-05-23T22:31:05Z"
    mac: ENC[AES256_GCM,data:KjOXPxwtS2PYFb3Jbg+mycpxUTBbnR952LfR1b4SMgmSRxMKD3A4rMqRfDgqdTfmfP4vMsuf5tYrSdY0VEiWz1uwg0rlAWtmpfCO5k5foOicKWbq8fO4hiH1ZU35X9lWyQ3LSFmhbSfHXZ0YhB8af/1xc+4rb363sXQVAjHx0Fc=,iv:DZZS4Zbz81zDwRjKdLcWBfwBF+GGo2GiFAA2rYhDVtw=,tag:Wp7XqGM8/ydHV+Ri6lkFaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
