apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
        - name: seed-qbittorrent-config
          image: alpine
          command:
            - sh
            - -c
            - |
              if [ ! -f /config/qBittorrent/qBittorrent.conf ]; then
                mkdir -p /config/qBittorrent
                cat > /config/qBittorrent/qBittorrent.conf <<EOF
              [Preferences]
              WebUI\AuthSubnetWhitelistEnabled=true
              WebUI\AuthSubnetWhitelist=0.0.0.0/0
              WebUI\LocalHostAuth=false
              EOF
              fi
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: creds
              mountPath: /creds
              readOnly: true
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: HTTP_CONTROL_SERVER
              value: "on"
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-creds
                  key: vpn-private-key
            - name: SERVER_COUNTRIES
              value: United States
            - name: FREE_ONLY
              value: "off"
          ports:
            - name: gluetun-api
              containerPort: 8000
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: America/Denver
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: data
              mountPath: /data

      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: data
          persistentVolumeClaim:
            claimName: media
        - name: creds
          secret:
            secretName: qbittorrent-creds
