apiVersion: ENC[AES256_GCM,data:LtU=,iv:hFK8aBo1qejdUqvasBUjcw2eF7eFJngw+A/P6zw3AB4=,tag:ogO7fr//BwUGKJRU8GWaVg==,type:str]
kind: ENC[AES256_GCM,data:xH3DnTDm,iv:D4mwVH9a+7yBKhv8iCC3prD12hoWaApE98tK4/ArrLg=,tag:fsDvqpQFSsGVr3EV8Me3bA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZAIDf/FvU0eCjSzygemaFm0=,iv:e+OWFttq/khijBZWdkpFZYa1oORiVE1TT7rDRwsbD1g=,tag:bdi2E+nJbVkE9WmKMkIM/g==,type:str]
    namespace: ENC[AES256_GCM,data:AZKtDL4=,iv:C5+6DNVNrTXMr5mGHYWvNzt+n7DZnHoNKCdvf+Cl1Gw=,tag:/xTh0/SbgpydMTH1wxRfJg==,type:str]
    annotations:
        argocd.argoproj.io/sync-wave: ENC[AES256_GCM,data:/kI=,iv:6xk02a3dN212aUBV6JmMwC5SghpcwTzBXOYT76VTNig=,tag:vEpAOA3aaK3AGRCvlIuMSw==,type:str]
type: ENC[AES256_GCM,data:8zU6i6b5,iv:HK2/r6aOYnrFZuNWIiaRu8trl27BQF6DFzJY5KIkFpg=,tag:uaKwvpE6TXuGQC7MLFQGtw==,type:str]
stringData:
    vpn-private-key: ENC[AES256_GCM,data:VLM6Rb2qPOIUEWjmtmZo5LKBnLhbosFROgJ3UygjWeiQsIRyKy8Q3sIxErU=,iv:z8rGNTOM/em1gLH6E64J5XQ2Ua0BTWe5HDN80345yMA=,tag:MCBtl3zfK0y9gvdZaYOJrw==,type:str]
    qbittorrent-username: ENC[AES256_GCM,data:35HGnQC9lsaG8+4=,iv:K4RA30FbrA3GE38iL9KkJma/CRcMwnPO0+JU3X5Bmv0=,tag:jOYMteS6dMRV1YOiRBHLPQ==,type:str]
    qbittorrent-password-hash: ENC[AES256_GCM,data:YkUVvY0tV+5Ki89u0kpWXh6F0k2mAyxnxtuKD4icGVnybc2lL1ZFPYmpjXtOzyMyxsJP867X7q6QLhSs+MB2P6fnn7APcmX3zHWDZjfZzYdBXo9PgY50cuVKNksa6kVEA3zMOut5TzcrBwAatiFw6kPuJF1vHi22W6vAolM=,iv:VOjMM1VjrhIDLzPNMqbrE9Jc1g/7NQzyTIQYv8o0oI8=,tag:ZTQZKCF3PnjX+JuOwgTc8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZHZiRkU4RGVEclVOWHli
            clNraWFTVS9salg4aWhwZzZWNkh3bE1yeGpzCmY3clpiQ2d5bFpPNTdUdHY3clBN
            ZUpCcUN0eVoxeHBTam1HVGFaN2ZXNjAKLS0tIHVCeFRQR0kyVGFWdXZCS3VPMUE4
            b1dTM1FKdGlWUXoycGZJL0ZDK3BOWFEKV+OXVjMoNsL17Qm12q/usQtmY/r2cdwW
            uXtFX4o7KrzkODlls3324V1KGnZOQ4uTKPeatQ0djQ7ell9WBDKsgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    lastmodified: "2026-05-27T01:58:50Z"
    mac: ENC[AES256_GCM,data:GbN6eGZP9xS/cdVH/Lsk70t61LroKNa2TEIQEm5qcIaF3gDFtMdusIavUZXB78QwkhmSrWhHnC/fLeUeqyrng0YJ3Q4MeNbce2iEVFiatF2jcOvygmanHNDv/1+eMb/LqW2klpgj9JKOzI/rjZUWBZJRgYmvN2ITacILBWUgIgk=,iv:PlvhCCi1MkoPHzcyKaflbsHO7Bpl8qL4JtSfTurJQy8=,tag:N7DQaOrMR5PP3p3moYfb7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
