apiVersion: v1
kind: Secret
metadata:
    name: test-credentials
    namespace: cloudnative-pg
stringData:
    username: ENC[AES256_GCM,data:Kk6O9A==,iv:7gU0TNYXEp0nKjeB8Ck/HhgyQAQuJ0q3PeJjQlM1ClY=,tag:fapTQVXa9o3ZzgyzKZUJEw==,type:str]
    password: ENC[AES256_GCM,data:DYPTP9UMGfjDTR58S9ZOxsZ7up4KNmlPJJIF5xPxo8ljL5AezL8W2HkyK4YYTXE=,iv:SgIrfTr/92wuHwHNvKTw2rNyEOYfP2RzHdB+DyPGL9k=,tag:1zkHRwgaDsCFrTB6km6gAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZjhLdmx1YlJZWHhONjkv
            U3VqdGNyV25DQVRFN1lhUzNFNnRabFRIZjJjClNmKzJydU0rdmgwMWcrUkwvRk5N
            OEFaclp3MFNuaGhucFY4SU5YaWhHdVkKLS0tIHJaRk45cFBPdlhnUmJyRGwwMUxT
            cEtCdjVrWndDcDhwUDF3eFdLTk9SelUKI/0QeeoQfHwKzJn7wBgmtMn6qpye84WW
            AatY7xP4rUkWc44LK+81rdJaQT4VbETyLAso/GZS3KhJr/6foSrNKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-20T00:03:19Z"
    mac: ENC[AES256_GCM,data:3+XxsX0pY2FreQFPfGWdF7KTIEHBmMD36d2ntkhbu78A4rNnZ/G5rA9KsbT0TxtH5KP79nhScu0Xft7gJhY5ljE8tdJGY94wtMmHbB9nfwPHTSQGnDQvMi+ZMwnH9/b32gUMh8168r4aAbUxWwygFCeridtVbP/bMGVBUdege8U=,iv:+/pjMWS5iHRlzG5KcIzddfwyAu0pKqyOi1bBa/sAITo=,tag:S9ZplE3MhBxnyMcCr3f2RA==,type:str]
    version: 3.13.1
