apiVersion: v1
kind: Secret
metadata:
    name: dbgate-cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:zZnntDy+,iv:l5kI7WAahyzA86q9ReX00lUKIuRI5IT8YPIGQGuyHwg=,tag:BKvUGu5az3fLeKksKL3TJg==,type:str]
    password: ENC[AES256_GCM,data:DqBtlXv33xF76Oevv6OR448bgEQCmM0iCr4zyqPb2wIUa/GbwtguFB48yqibMIfH5zVE,iv:+0XDrmTMAgcZLG0/5OJuhKOJj+YGALWIxFp+Vx9Oo5M=,tag:ZKKgAaGsG2pUZU9s5U5nyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNm9zR1lVUDMrd25TK3Vk
            ZzJQRGIzdjM1U2hNaXNOeFdBUEhkcG5rOFY4Clgwc2ZSUkdGRkxYRXR2bFBlcEt4
            dSs1WW9sMkhMbmk0emlYZ2VhdTEwYncKLS0tIFRzWkhFTmFzeTJ4TXJUNzhkbmV2
            Qk1NalBnVnlmU21mK1cwZHFZTnpLakEKCwT9fCg5b3ZHwRuLYcWVArP4I1tkzaJ3
            ItNkRwyEnfRu08euu10nf3oLdvVwp56unFbvKt6Ep+pKiVPkFE4AiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T04:12:12Z"
    mac: ENC[AES256_GCM,data:MEyOxeITHgQXjTM0vTzM9yuN3NUwZAujuTPTSg7l+e3ztYUxiO5i/VmE6qEMHevtncHe5YUEIvi8gLa10c1CqQF3JkUx8+a7GpW4acDLkI5zAuQjt3c50UyVV+R5oVSlFheq0n1hmSPqQZ9x+FL4hjuBA1HgnHwimvzAOLTEcB4=,iv:zSxxDCVDP3uvAUyNUn5Uro62f2ZOlntPMMz2U8PIpNs=,tag:q7t4b9PfI+CvzHNZ4Q8NZQ==,type:str]
    version: 3.13.1
