context: {}
entries:
- attrs:
    authentication: require_authenticated
    denied_action: message_continue
    designation: authorization
    layout: stacked
    name: Authorize Application
    policy_engine_mode: any
    title: Redirecting to %(app)s
  conditions: []
  identifiers:
    pk: 4461625f-71af-45eb-a2aa-b3072a11503b
    slug: default-provider-authorization-explicit-consent
  model: authentik_flows.flow
  permissions: []
  state: present
- attrs:
    consent_expire_in: weeks=4
    mode: expiring
  conditions: []
  identifiers:
    name: default-provider-authorization-consent
    pk: 0bce288a-5651-4d12-8bde-574f306e1d47
  model: authentik_stages_consent.consentstage
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 0
    pk: 8766b03f-f276-4299-996f-d92d1ca17e5a
    stage: 0bce288a-5651-4d12-8bde-574f306e1d47
    target: 4461625f-71af-45eb-a2aa-b3072a11503b
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2026-05-30 18:23:44.526251+00:00
version: 1
