context: {}
entries:
- attrs:
    authentication: none
    denied_action: message_continue
    designation: invalidation
    layout: stacked
    name: Logout
    policy_engine_mode: any
    title: Default Invalidation Flow
  conditions: []
  identifiers:
    pk: 34784c3e-b047-4523-a820-60e879f4e276
    slug: default-invalidation-flow
  model: authentik_flows.flow
  permissions: []
  state: present
- attrs: {}
  conditions: []
  identifiers:
    name: default-invalidation-logout
    pk: 62b86083-804d-4566-8b10-306645ce6ea6
  model: authentik_stages_user_logout.userlogoutstage
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 0
    pk: a635ce74-4a0d-4b7b-99ce-c6b1d6baee1a
    stage: 62b86083-804d-4566-8b10-306645ce6ea6
    target: 34784c3e-b047-4523-a820-60e879f4e276
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2026-05-30 18:24:09.397929+00:00
version: 1
