context: {}
entries:
- attrs:
    authentication: none
    denied_action: message_continue
    designation: invalidation
    layout: stacked
    name: Logged out of application
    policy_engine_mode: any
    title: You've logged out of %(app)s.
  conditions: []
  identifiers:
    pk: e1b8be59-b0c8-4342-bad5-bf0f6e09dd96
    slug: default-provider-invalidation-flow
  model: authentik_flows.flow
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2026-05-30 18:24:13.876360+00:00
version: 1
