context: {}
entries:
- attrs:
    authentication: none
    denied_action: message_continue
    designation: enrollment
    layout: stacked
    name: Welcome to authentik! Please select a username.
    policy_engine_mode: any
    title: Welcome to authentik! Please select a username.
  conditions: []
  identifiers:
    pk: e32048ef-ac2a-4011-a6d9-49f23457d206
    slug: default-source-enrollment
  model: authentik_flows.flow
  permissions: []
  state: present
- attrs:
    field_key: username
    label: Username
    name: default-source-enrollment-field-username
    order: 100
    placeholder: Username
    required: true
    type: username
  conditions: []
  identifiers:
    pk: 67b9be63-c4b7-41cc-8a21-947f9102370f
  model: authentik_stages_prompt.prompt
  permissions: []
  state: present
- attrs:
    expression: '# This policy ensures that this flow can only be used when the user

      # is in a SSO Flow (meaning they come from an external IdP)

      return ak_is_sso_flow'
    name: default-source-enrollment-if-sso
  conditions: []
  identifiers:
    pk: d7317453-05d5-443e-bb34-d2ccfc6ad909
  model: authentik_policies_expression.expressionpolicy
  permissions: []
  state: present
- attrs:
    expression: '# Check if we''''ve not been given a username by the external IdP

      # and trigger the enrollment flow

      return ''username'' not in context.get(''prompt_data'', {})'
    name: default-source-enrollment-if-username
  conditions: []
  identifiers:
    pk: afc896ca-d315-4737-9fe0-306ae5b8c3e1
  model: authentik_policies_expression.expressionpolicy
  permissions: []
  state: present
- attrs:
    fields:
    - 67b9be63-c4b7-41cc-8a21-947f9102370f
  conditions: []
  identifiers:
    name: default-source-enrollment-prompt
    pk: 8d7536ed-1ceb-4ef1-b263-ab16ac9678c4
  model: authentik_stages_prompt.promptstage
  permissions: []
  state: present
- attrs:
    geoip_binding: no_binding
    network_binding: no_binding
    remember_device: days=30
    remember_me_offset: seconds=0
    session_duration: seconds=0
  conditions: []
  identifiers:
    name: default-source-enrollment-login
    pk: c34b089d-db42-4a27-a7fb-16d6685d0230
  model: authentik_stages_user_login.userloginstage
  permissions: []
  state: present
- attrs:
    user_creation_mode: always_create
    user_type: external
  conditions: []
  identifiers:
    name: default-source-enrollment-write
    pk: e1fb5b18-1c3e-481a-9792-5a5e7ecc6ba0
  model: authentik_stages_user_write.userwritestage
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 0
    pk: 75c3ab9c-b409-4f99-aa17-0060cec8480a
    stage: 8d7536ed-1ceb-4ef1-b263-ab16ac9678c4
    target: e32048ef-ac2a-4011-a6d9-49f23457d206
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 1
    pk: 8fd58720-1d41-4a69-916c-f3366fda5abf
    stage: e1fb5b18-1c3e-481a-9792-5a5e7ecc6ba0
    target: e32048ef-ac2a-4011-a6d9-49f23457d206
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 2
    pk: 3f9cce6f-0a9a-47b5-929a-6485fe280e35
    stage: c34b089d-db42-4a27-a7fb-16d6685d0230
    target: e32048ef-ac2a-4011-a6d9-49f23457d206
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    enabled: true
    timeout: 30
  conditions: []
  identifiers:
    order: 0
    pk: 00baaa6e-c065-4482-a371-cd26c0edff66
    policy: d7317453-05d5-443e-bb34-d2ccfc6ad909
    target: e32048ef-ac2a-4011-a6d9-49f23457d206
  model: authentik_policies.policybinding
  permissions: []
  state: present
- attrs:
    enabled: true
    timeout: 30
  conditions: []
  identifiers:
    order: 0
    pk: a296ae4c-8f87-4768-aac8-b434a48aa5de
    policy: afc896ca-d315-4737-9fe0-306ae5b8c3e1
    target: 75c3ab9c-b409-4f99-aa17-0060cec8480a
  model: authentik_policies.policybinding
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2026-05-30 18:24:02.939099+00:00
version: 1
