context: {}
entries:
- attrs:
    authentication: none
    denied_action: message_continue
    designation: authentication
    layout: stacked
    name: Welcome to authentik!
    policy_engine_mode: any
    title: Welcome to authentik!
  conditions: []
  identifiers:
    pk: f8593771-dd61-405b-ac90-e90bc5ee7765
    slug: default-authentication-flow
  model: authentik_flows.flow
  permissions: []
  state: present
- attrs:
    expression: "flow_plan = request.context.get(\"flow_plan\")\nif not flow_plan:\n\
      \    return True\n# If the user does not have a backend attached to it, they\
      \ haven't\n# been authenticated yet and we need the password stage\nreturn not\
      \ hasattr(flow_plan.context.get(\"pending_user\"), \"backend\")"
    name: default-authentication-flow-password-stage
  conditions: []
  identifiers:
    pk: 9a8449de-81f4-4e71-a7b8-b91f73d0f251
  model: authentik_policies_expression.expressionpolicy
  permissions: []
  state: present
- attrs:
    expression: "flow_plan = request.context.get(\"flow_plan\")\nif not flow_plan:\n\
      \    return True\n# if the authentication method is webauthn (passwordless),\
      \ then we skip the authenticator\n# validation stage by returning false (true\
      \ will execute the stage)\nreturn not (flow_plan.context.get(\"auth_method\"\
      ) == \"auth_webauthn_pwl\")"
    name: default-authentication-flow-authenticator-validate-stage
  conditions: []
  identifiers:
    pk: 3bda961f-56f3-4535-848d-eb820b0cbf5a
  model: authentik_policies_expression.expressionpolicy
  permissions: []
  state: present
- attrs:
    backends:
    - authentik.core.auth.InbuiltBackend
    - authentik.sources.kerberos.auth.KerberosBackend
    - authentik.sources.ldap.auth.LDAPBackend
    - authentik.core.auth.TokenBackend
    configure_flow: 29fc0e85-74d3-49de-8613-9b540d128453
    failed_attempts_before_cancel: 5
  conditions: []
  identifiers:
    name: default-authentication-password
    pk: 01f92331-2345-4e58-abc7-02995c671642
  model: authentik_stages_password.passwordstage
  permissions: []
  state: present
- attrs:
    case_insensitive_matching: true
    pretend_user_exists: true
    show_matched_user: true
    user_fields:
    - email
    - username
  conditions: []
  identifiers:
    name: default-authentication-identification
    pk: 0747f3ee-7319-415b-936f-cc1891dd75eb
  model: authentik_stages_identification.identificationstage
  permissions: []
  state: present
- attrs:
    geoip_binding: no_binding
    network_binding: no_binding
    remember_device: days=30
    remember_me_offset: seconds=0
    session_duration: seconds=0
  conditions: []
  identifiers:
    name: default-authentication-login
    pk: 117dd91a-c946-4bf5-8d50-5c72ed201a10
  model: authentik_stages_user_login.userloginstage
  permissions: []
  state: present
- attrs:
    device_classes:
    - static
    - totp
    - webauthn
    - duo
    - sms
    - email
    last_auth_threshold: seconds=0
    not_configured_action: skip
    webauthn_user_verification: preferred
  conditions: []
  identifiers:
    name: default-authentication-mfa-validation
    pk: d097fab6-fb1c-4a6c-9da7-88446a8c85cf
  model: authentik_stages_authenticator_validate.authenticatorvalidatestage
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 10
    pk: a31adf60-6572-464b-89c8-b06ca47d4dfb
    stage: 0747f3ee-7319-415b-936f-cc1891dd75eb
    target: f8593771-dd61-405b-ac90-e90bc5ee7765
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 20
    pk: 7af5ead0-fc8e-4595-bf9f-b8b23505d820
    stage: 01f92331-2345-4e58-abc7-02995c671642
    target: f8593771-dd61-405b-ac90-e90bc5ee7765
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 30
    pk: 079cda25-a785-4306-87df-c9bc6f7451a3
    stage: d097fab6-fb1c-4a6c-9da7-88446a8c85cf
    target: f8593771-dd61-405b-ac90-e90bc5ee7765
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    invalid_response_action: retry
    policy_engine_mode: any
    re_evaluate_policies: true
  conditions: []
  identifiers:
    order: 100
    pk: dccf8dec-a546-4039-bcf5-35349f392e94
    stage: 117dd91a-c946-4bf5-8d50-5c72ed201a10
    target: f8593771-dd61-405b-ac90-e90bc5ee7765
  model: authentik_flows.flowstagebinding
  permissions: []
  state: present
- attrs:
    enabled: true
    failure_result: true
    timeout: 30
  conditions: []
  identifiers:
    order: 10
    pk: b11c86a8-5a09-437a-ae1c-db89b3eecf7e
    policy: 9a8449de-81f4-4e71-a7b8-b91f73d0f251
    target: 7af5ead0-fc8e-4595-bf9f-b8b23505d820
  model: authentik_policies.policybinding
  permissions: []
  state: present
- attrs:
    enabled: true
    failure_result: true
    timeout: 30
  conditions: []
  identifiers:
    order: 10
    pk: 3db03aeb-87b6-4f54-987b-0d85b6b32eb8
    policy: 3bda961f-56f3-4535-848d-eb820b0cbf5a
    target: 079cda25-a785-4306-87df-c9bc6f7451a3
  model: authentik_policies.policybinding
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2026-05-30 18:23:30.542346+00:00
version: 1
