- name: Configure firewall and Cockpit
  hosts: tang, k8s
  become: true
  tasks:
    - name: Install zsh
      ansible.builtin.package:
        name: zsh
        state: present

  roles:
    - role: firewall
    - role: cockpit
    - role: ipa-client
    - role: tang
    - role: kubernetes
      tags: kubernetes
