- name: Global configurations
  ansible.builtin.import_playbook: playbooks/global.yml

- name: Cockpit server management
  ansible.builtin.import_playbook: playbooks/cockpit.yml

- name: FreeIPA servers and clients
  ansible.builtin.import_playbook: playbooks/freeipa.yml

- name: Create Kubernetes cluster
  ansible.builtin.import_playbook: playbooks/kubernetes.yml

- name: Refresh workstations
  ansible.builtin.import_playbook: playbooks/workstations.yml

- name: Create tang server
  ansible.builtin.import_playbook: playbooks/tang.yml

- name: Create tang server
  ansible.builtin.import_playbook: playbooks/tang.yml
