apiVersion: v1
kind: Secret
metadata:
    name: bytebase
stringData:
    postgres_password: ENC[AES256_GCM,data:+Flnw65hYyXjyYxAFkWt4y/AKeCE8ELVZ2E82eh7zh4C4qYlo0doX2VD5XIngDsBRk89,iv:hX4K+rbbCnGaGjeF5ogvLYRa2hjZa+z23wETuO3sstY=,tag:bwX3KGEpCWk9WesFrUDo6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cVhDbG9mUExUYzVtd3ZX
            TE9MRGkyV1E0Vzk0NHhELzA2eGNoVFh3TzMwClVsN0I1a0d3K0hYVFNnandzNE5O
            VTdlbGFIYlB1cEdURjZDRzJDVFROTncKLS0tIDVnZEg4NnQxOUVYWStiQ1pKTG9u
            dEsvc2RybG9uUDhLQmQxUFNYdWlabVUK23i2wcM8SueVj8GFhHK5Lt6EABERs0RA
            zcsoS0tDBl9eqnl5u76638e3B9KJsEu8e/Kxw2pfH5A3gNGVR5nBEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T04:39:38Z"
    mac: ENC[AES256_GCM,data:/5a/f/sNjB4bL/w/oiJV8XlX0EkKlq35D6i3g+mDl03nKmjVgwIEHWffp3CbfF/7+598lQZI4qvq6Hgh20/XmYYoVV9fiRiPf+d42fc2ARfBPFPqhdDIlu7GBWn3Av44fySMNqt3dM8JepuMsdyId6lkhTdbcLpmO7RQxV/yUEw=,iv:hAr1p2cVAZHJlJM0BvDKTWp2vxm8X3onI3uZGu1kf44=,tag:zD7AsbSuZuLhc5vdm1m0kA==,type:str]
    version: 3.13.1
