apiVersion: v1
kind: Secret
metadata:
    name: bytebase
stringData:
    postgres_password: ENC[AES256_GCM,data:zGYo4SNfy9ejWVE6q4cmIpmmVAP78t/+E3Npt1zC1Q7pPu5geCvArFTMSdkS4H+T8O8=,iv:Os01KcHH22cC0qtjnohfkHspLnUVmJImj60k0/ULnCs=,tag:eVN13j9NmFlzvPp/nyUBxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN0VIMExQM2JhY2dUNVBx
            S2NSd0JVbVNkaml6YWtKWDhtUVZ0Z1cxNm5rCmNNM1RibGFPWGxyRU5YUHRnbGVE
            WUlsZzFRWjd5RXl6eUs5N1NCTlNNWGsKLS0tIDB6Z2VpdTVOWDRnMit1K3ZJQko4
            U21OZENwb3JZeUtEaWxYZHEyZnhaNWMKmEX4A5Ej5SzMerTl3GILXz6bfaaC9RsV
            BFoa79z1yw+Mh7DODtKwjJTKlxBEeJ0XR7AGdqFcIPtgvZY0CsROug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T01:59:22Z"
    mac: ENC[AES256_GCM,data:yqZVpRGkvKSdthsqEixYiUFExlyYiCyd2R8LjhQZGhMWCXL67/yTb9tmSO28FjrM3uVJuBmBgPEV00DUBxDjRRhNEFkrn27IjBIzWxh3zd20lfUhRoNNjPF3qTHLIOlU4uh2J1zAO8YeGz8zL5SdAB+Vkdxmgv9uaPAVjhAtZ4Y=,iv:1k4tzqRC4fAcg2e7WIBjGBzq8uX80z5TaOkiN08u1BI=,tag:aTQDVd6WQiV4UUvN3i6r2Q==,type:str]
    version: 3.13.1
