apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
stringData:
    client-info.yaml: ENC[AES256_GCM,data:xeamdqTQK/NYmkXPkrcVnNmEn+EaUioB7Pvjnt8JaBSvZBqyIy4wNCSPRq1D/XVdFzyl0MwMSkPUsKUENKjGtFOhg99+jHKr8NPZmP6kHHscGhz0wBtVAMjpxQil0G1RbKEoHB+EPCC7U1oKphkEsphPd9FU6V6A5Nt3aQn7rwrKCqUxvS0Hyxs9Bo+6IEJHu1TwkNF3+yMkwEc=,iv:Xxy4t58nQ4ynyMSnw/ZaGT5KNNLFyQRSmbB+QG5oPPc=,tag:wDW+HpfrgRWC5lhnv8gLtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRzViL2o4REZKekdXOThM
            ZGdGS0FSWW9tQmhYWDl2RE03a2NNUUhvTldJCmk3eVlCS0pMcm1HQ2xvMWZwYTF6
            RTRyWUxxSk4yeHZxMnZYQ1V6bDhsYlUKLS0tIHFsQ1lXVmljdjhMaUJrZ3ZlZ0Ew
            SHV0VXgremVvbDVOckd2S1NrTnRzajQKFYxLhRbrU+kdOBlM7+RNRTkC8qJ6/4Fy
            Kow2FYJtzqgJZHjtKaTAOKrX1OIrDVTOAPBgovANUCM5wkkkxFN1Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-18T02:26:38Z"
    mac: ENC[AES256_GCM,data:O6fELLT7AwcaxV2PbI2z+GhRd+raDqLgU7FnSpCb53EwkIqejEgJlut+0ybrMKblQ++wOvvBtz4FU8Ah8XtyT5e3bDX6NQY65p5stVtP94BjP+gVz4pWHjbXFeayjvE0NcLO+1utaHJUZBqczbUHubs3P0eW4cil9KBxy1kb6zw=,iv:/0y4LhiHIl0sC5t+9xNJcmlIwLp+kRFVe7fVo5OfJwE=,tag:5pyrfXL9VN//2CgUpH+UpQ==,type:str]
    version: 3.13.1
