apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
stringData:
    client-info.yaml: ENC[AES256_GCM,data:gkKBssTSr3LpFLKDqBjM/3m9pBJFOtRakr4IGmEfY8IbaUA06raO35OOV/FyvNQWEDrXWv8W/Ppp2rEBgckJe5/+BWSuK5dQom634l1V31pSHiO5b30JOxrK03lddcjbS1BIKlV4go4e7PnRSsHgD6/9+x81ER2ciVEH472ZeVJoj+81y6FYKw7r6novbuHI19iQXmz/4xAgrhCXBzH9OP6Bye5UtV/kpY7KClE3OpXfo+hU05vSWN+rOUpmsuT0eAt4hOxkzx0FY0/eh3ILGpby9i7MAjYzNNN74u57KuAX953zOYsg/kw=,iv:RWA0HBiCYo5aQvIyX+ssyft8lmG4fiuVavOQtt703nM=,tag:+os9oknLDTul6tVpLddj8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSDljMGhnTTEya0xrY2N0
            Mkg3TWhrNmh3bXQrRFJiQmF1STE5VTRtSUVBCmlodm52WjY3T1pJWmxJVWNSS3Jn
            dzhHZkdNM2swN21Bc2phb0owOERnSHMKLS0tIEVuelpLaGRQaWdPem5wODNwTjgw
            c2U5SU10K0dCMUpaR25TNGs1RHlBdmsKzQk3ll+h6Cf2AEkyJWpbd11DyWQHPirP
            KYM0XAHtLiJr2S//Nf2kws8PU6nKeYwvZwfD0fsRcVGTYfyQ8So/+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-19T01:01:33Z"
    mac: ENC[AES256_GCM,data:oYvYeLPawBKVYL/5+7n2f13lbcupRIEFkxurQqodwAdcadl6f22v3MUCdXrcr/7PAVdBjI9TiTqP4QDK2zuW2YoKA66gvrW23SX7JManrq1kTXhCMQztexfOW59aboJnFYvtPT3rXnZS62+SYdctF0SDroVX7biGt1ulLIGhonA=,iv:YLO6xbgtHgIoPBbUoluXXd+a2Y4yYiwztFxDNtEp0Ww=,tag:rLl6QKfIM6o7dMOIHKre9A==,type:str]
    version: 3.13.1
