apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
stringData:
    client-info.yaml: ENC[AES256_GCM,data:mu2dd+oao9ZhaQizafAqG3NSBMymM1yXaWEEL35r4babrGdGw2ujr4M51AxCyIzrmx3rnZhpbgADD5gHlPBEtO5jdlkKSdzoFpryZcri9EvikxpXZYB1ZN3s5u05SO7QZeNZZFWOMhz726/foYaQULefTIwTQYX4Dv1C/hXJLuyhGlyiII2hMGKQKDyFlSIo3XDbyY11CD7+3VT47tVM1w29Q5rlgZlP1rMKz3kXNpCT815u90nHpdTkG6KH57LjB9kPTZSRJS1CzTkoGps86MIGDFgg9qTgt2J47grr6BpOX2nhl5i+EbqpAON8gG2RQb0tzTXXssrNoU6OqPrjVo9dcJdDO1skyYDF3olIaRhO8637zqNtYDGGQSz2Cbx/+LZXWj4Azri7ZrhqA5IMIzs=,iv:twXi5nmbifPGrQau4HfD+EUfB6Vcp7VsJtA8RMVdbwo=,tag:zoytRFpfrgsuAgwBaed03Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQ2pQK2NzakJtQ2RpZmNx
            bWNKMVlXbytnUUxtaHd2WGsvL0V1NXBUbzBrCkNDSVd2RFpzR1l4blg0MnFZSnQ5
            Q2JGQVBGOVdldldHYzNsbXpaOGQvZjQKLS0tICtRR3B1OGJCaTFUR1lOVWFzeVdG
            dmJKSUpaMnZ0RGhibmlmbVBtc3VPYXcKjqBLd+P4D+WUp/v+bT+VBnZ9Q/2DX7BJ
            0pizg4V5nw/GGbwjgH5dEUwMcTvIGx0f1MQi0iwAMOXmXb7t8EIdvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-19T01:13:50Z"
    mac: ENC[AES256_GCM,data:NGjnQPkx1JjRQInMV5YOeklU60i2koBHFKCV0nhk3uT6DC+bHi7bohGsJ6IMgcNTmrATaxpSCIm+dKQkm98FzzmfIINcdPyuXsE53YhCIQ13M9pgRZIIPUxhyAtCF4jp9DvqaXp9mAp3os5SlNkM9htAfIcBfZPMwK1ZhdgGazE=,iv:XawJcxd/daZqOr5c5c6NEIgglOsZ0dY6NDBcHEPezsw=,tag:VJS0qwOr6eyMLS0TNMUX4g==,type:str]
    version: 3.13.1
