apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: newt
    repoURL: https://charts.fossorial.io
    targetRevision: 1.2.0
    helm:
      valuesObject:
        replicas: 1
        newtInstances:
        - name: main
          enabled: true
          auth:
            existingSecretName: newt-cred
            keys:
              endpointKey: PANGOLIN_ENDPOINT
              idKey: NEWT_ID
              secretKey: NEWT_SECRET
        ingress:
          ingressClassName: traefik
        startupProbe:
          failureThreshold: 60
          periodSeconds: 10
  destination:
    name: in-cluster
    namespace: pangolin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true