apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.13.3
    helm:
      valuesObject:
        ingress:
          ingressClassName: traefik
          servicePort: 30500
  destination:
    name: in-cluster
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true