apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.13.3
    helm:
      valuesObject:
        hostname: rancher.local
        replicas: 1
        bootstrapPassword: admin
        ingress:
          ingressClassName: traefik
        startupProbe:
          failureThreshold: 60
          periodSeconds: 10
  destination:
    name: in-cluster
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true