Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.box_version = "2511.0.0"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "/home/austin/code/work/work/dotfiles", destination: "C:/vagrant"
end
