helmDefaults:
  createNamespace: true
  
repositories:
- name: postgres
  url: https://cloudnative-pg.io/charts
releases:
- name: postgres
  namespace: postgres
  version: 0.28.0
  chart: cnpg/cloudnative-pg
  values:
    - values.yaml
