LOAD DATABASE
  FROM sqlite:///srv/arr/sonarr/sonarr.db
  INTO postgresql://postgres:pass@localhost/sonarr

WITH include drop, create tables, create indexes, reset sequences

SET work_mem to '128MB',
    maintenance_work_mem to '512MB'

CAST type datetime to timestamptz
       using midnight-install-type-of-nothing,
     type date to date
       drop default drop not null;
