apiVersion: ENC[AES256_GCM,data:5R0=,iv:ToT/KJ3GEDOVv/FKeL1W1K9Hr8/q03nq9OOsDgJCHSQ=,tag:PTyuE7GDnwHbT4VM2NnCaQ==,type:str]
kind: ENC[AES256_GCM,data:uOKj3gKi,iv:be8oyuAdp8OA1r7IRfzBMGx+8Rb5+liGQTXaQjqPFgU=,tag:oJrwuZR4WqlFk+7WspDRzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/ItXE7rl/mYK4mir47RIJ+0=,iv:ttjFiomKW3jy9BkAevrxZDvTzmWNeSUR+UVsTJKJ04c=,tag:6mcb6PMcFS3NTyTXscPsZg==,type:str]
type: ENC[AES256_GCM,data:TduAx1Cg84FARMMu/eFNomHLxa08JjOc,iv:KztQq9KGpxbK9NC1FvTiq9L1O+Y1qo+WFo0urMxUZIw=,tag:6vw9dHeI7ZIeaJuG1apE0A==,type:str]
stringData:
    dev_k3d_cloudflare_api_token: ENC[AES256_GCM,data:EcCxpfbEPDIPyAoV8LGJ+Smds5CILRmNdBEAJcY4iIq1lVZBcHwonJV4QujXm3aMk3mjrjQ=,iv:HTxo25hx2jTaOK8Km4OEn7RSIMzWlwC2c+PKDaS8AzI=,tag:F6ZB9YFoysRjgDE691YG5g==,type:str]
sops:
    age:
        - recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTmNDekx1SXcwS0JiUkZP
            TFFnY3QvUWtpa1g5bHE2TWxJSCtlS05BZ1NJCk9TMnFkeTFzNFpONHZQL0RQbytq
            RStMaGp5V0wxN0V4dCtTMElKRlAxcFEKLS0tIEdZZGF3UEtCekFIRUxzN3pnVjFz
            OTlPWGdBOU1paUZBVGtkVVFEQVpIeHMKI2MkbrA6LSJ354u1wpq+SgGakudygC+9
            8rx9YJiHF4yvgqhQZdSgVZ4FLUjvcCO4q6RT5aAozaC5VNMLImxrLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T04:20:31Z"
    mac: ENC[AES256_GCM,data:O1s6mdtLqscUZBcCC56oEnFOOBpzYR65A7dcVzS8SphTLHTZot2T03IpBvlMb6ql/+JPH9XSSI4hdjNrLzINFqPZuAJJGC+NcbN59vxivEEd428P3E5ykVr64VaQVYs1kZd601tNGIM9BDMF6irWOV8UkBnKkT5rvFo509UXgq0=,iv:zR4xANqa64ELD2EJiLKM4MdD7pGgb6iWCjjBtVVesFo=,tag:2EiDz3FEw+6bNrrbYIXP1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
