apiVersion: v1
kind: Secret
metadata:
    name: deduparr-secret
    namespace: media
stringData:
    DEDUPARR_RADARR_MOVIES_API_KEY: ENC[AES256_GCM,data:GfKrvFNVpe+XBA9FFGpb3Sjw0dTWIMzfH5/BfHPrZqg=,iv:N6RY99d3+qvGGzBjZYVvRgQWbwKazLmJww8uXZE120M=,tag:f9EHIAivIDkcDaTYzmScyA==,type:str]
    DEDUPARR_SONARR_SERIES_API_KEY: ENC[AES256_GCM,data:vnuZgbQpf0Z8pmlrdHYmzBF0ZaRjyCoEUmUqr3mkpzU=,iv:l1By3UgnCJ3u6sqNJJRuAyhegJySWLr2T1lyrP/NIuY=,tag:mXsrZbHqj2b8hBkC1xdFZw==,type:str]
    DATABASE_TYPE: ENC[AES256_GCM,data:FFUy2H4KPwo=,iv:sEVKQP2ZGesAZrGUmg7vfgosdWtZBbb+FOzQ6f6uP/c=,tag:FgdjBB6yhcd0VM6ed+SoGQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:5x/PhHQJpA0SrvWb5FKMApM8kGI+EdUOm0/NrQmgdBUGrPWsZdbEdMtTD4PDfpstOHK0gcpG+lNnk3bNgKW2HBJYTMqT48GqaVtn6Z1SWf7PwCkzTJO+Z3synoYiRlIX37zbrI4HVJyABR0nUNWOqs0Wdv9g4G2MR3B/06FQOYid7Unq3Mx5IO4=,iv:hjqjGNxKl9k8pvK6T6k0RbaGE8pyAQWqTASABijG28s=,tag:YJIUbEagaeDJ3RERj/cdmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSDcyY053VTMzelhzb2U3
            NDJsMnBjeWZ2WW9kMWVRSzJVWGZPVWRId1EwCnJXY2lteVdzb2hUazhmNUVNUGVI
            bWV2c2NxUnJtYklycC96MVJuaC9lWlEKLS0tIC9CeFM1MS9EZ2c2b0VTdC9ubDJw
            VEZKazN1cU95RkdXb2R1VXY2UTBRQzQKuzKNH50qZdc4L+eBhUfuDJF1bEn9WLkR
            bQ9YhUh4bEFWl5h4DtpyMR4FtZoszxf9ZtQLIyya0imtm/O3fi+TAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:22:49Z"
    mac: ENC[AES256_GCM,data:CzH0hBhZai8XgBTlVFbD3w6D03/LgW8Fa0LAJbM7Mkp3QBhKT7TdzySgv2xgLNfgXlBQs1Wd5j6sKbZEceXLNH1Mb3mJ1LtIRZTS9wOdhF62+M+YBk5MXxc/FAFZ3jy15fWCO9k5Xiv7JZXgewOWBAQEdljZ8zqZXZ4m6LjmDnc=,iv:a5CabNqr6TDHJssSg6lp8a8b7B8gvfDaCm8QFrwOHQM=,tag:7AM6jJHl1bFTdF6XDCZwJA==,type:str]
    version: 3.13.1
