---
- name: Install tang
  ansible.builtin.apt:
    name: tang
    state: present

- name: Enable tangd socket
  ansible.builtin.service:
    name: tangd.socket
    state: started
    enabled: true

- name: Allow http
  ansible.posix.firewalld:
    service: http
    zone: public
    permanent: true
    state: enabled
    immediate: true
