---
- name: Create connection to The Black Lodge VLAN
  become: true
  command: >
    nmcli connection add
    type vlan
    con-name vlan2
    ifname vlan2
    dev eno1
    id 2
    ipv4.method auto

- name: Bring VLAN connection up
  become: true
  command: nmcli connection up vlan2